import { PDFDocument, PDFFont, PDFTextField, StandardFonts } from 'pdf-lib';
import { getChampionsStats } from '../domain/champions';
import { STAT_KEYS, type ChampionsMon, type Division, type PlayerProfile } from '../domain/types';

/**
 * Team sheets are the OFFICIAL Play! Pokémon "Pokémon Video Game Team List" PDF with our data in
 * its form fields. `team-list-form.pdf` is that PDF plus named AcroForm fields, generated by
 * scripts/make-teamsheet-form.mjs — the page art (fonts, lines, labels) is Pokémon's, untouched.
 * Here we only fill the fields by name and flatten them into the page.
 *
 *   page 1 = "1 of 2: For Tournament Staff" (adds Player ID / DOB / Support ID + the stat column)
 *   page 2 = "2 of 2: For Opponents" (the Open Team Sheet)
 */
export type SheetPages = 'both' | 'staff' | 'open';

const DIVISION_FIELD: Record<Division, string> = {
  Junior: 'div_junior',
  Senior: 'div_senior',
  Master: 'div_master',
};

// Characters the WinAnsi-encoded standard font can't draw, mapped to what the game shows instead.
const REPLACE: Record<string, string> = { '♀': '-F', '♂': '-M', '’': "'", '‘': "'", '“': '"', '”': '"', '–': '-', '—': '-' };

/** Keep only characters the field font can encode (after the replacements above). */
function encodable(font: PDFFont, s: string): string {
  const ok = new Set(font.getCharacterSet());
  return [...s.replace(/[♀♂’‘“”–—]/g, (c) => REPLACE[c])]
    .filter((c) => ok.has(c.codePointAt(0)!))
    .join('');
}

/** Set a field's text, shrinking the font (never growing it) so long values fit the box. */
function put(field: PDFTextField, font: PDFFont, value: string, size: number): void {
  const text = encodable(font, value);
  const width = field.acroField.getWidgets()[0].getRectangle().width - 4;
  const fit = text ? Math.min(size, (size * width) / font.widthOfTextAtSize(text, size)) : size;
  field.setFontSize(Math.max(5, Math.floor(fit * 10) / 10));
  field.setText(text);
}

/**
 * Fill the form template with a player's details and team. Pure (no I/O) so it runs in Node tests
 * as well as the browser.
 */
export async function fillTeamsheet(
  template: Uint8Array | ArrayBuffer,
  profile: PlayerProfile,
  teamName: string,
  mons: ChampionsMon[],
  pages: SheetPages = 'both'
): Promise<Uint8Array> {
  const pdf = await PDFDocument.load(template);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const form = pdf.getForm();
  const set = (name: string, value: string, size = 11) => put(form.getTextField(name), font, value ?? '', size);

  set('player_name', profile.playerName, 12);
  set('trainer_name', profile.trainerNameInGame, 12);
  set('team_name', teamName, 12);
  set('switch_name', profile.switchProfileName, 12);
  set('player_id', profile.playerId, 12);
  set('support_id', profile.supportId ?? '', 12);
  // The template prints the two date slashes itself, so the date goes in as three parts.
  const dob = (profile.dateOfBirth ?? '').trim();
  const parts = dob.split(/\s*[/.-]\s*/);
  if (parts.length === 3) parts.forEach((p, k) => set(`dob_${k + 1}`, p, 12));
  else set('dob_1', dob, 12);
  form.getCheckBox(DIVISION_FIELD[profile.division]).check();

  mons.slice(0, 6).forEach((mon, i) => {
    const n = i + 1;
    // Champions: the old Tera Type row is "Stat Alignment" and shows the Nature.
    const nature = mon.nature || 'Serious';
    set(`p${n}_species`, mon.species, 13);
    set(`p${n}_nature`, nature);
    set(`p${n}_ability`, mon.ability);
    set(`p${n}_item`, mon.item || 'NO ITEM');
    for (let j = 0; j < 4; j++) set(`p${n}_move${j + 1}`, mon.moves[j] ?? '');
    const stats = getChampionsStats(mon.species, mon.evs, nature);
    for (const key of STAT_KEYS) set(`p${n}_${key}`, String(stats[key]));
  });

  form.updateFieldAppearances(font);
  form.flatten();
  if (pages === 'staff') pdf.removePage(1);
  if (pages === 'open') pdf.removePage(0);
  return pdf.save();
}
