// One-off: convert the reference repo's JS dictionaries into typed TS data modules.
// Run: node scripts/vendor-data.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const srcDir = join(root, 'vendor-src');
const outDir = join(root, 'src', 'data');

/** Parse `var NAME = { ... };` into a JS object. */
function parseVarObject(file) {
  const raw = readFileSync(join(srcDir, file), 'utf8');
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  const json = raw.slice(start, end + 1);
  return JSON.parse(json);
}

/** Evaluate a `... = { ...js object literal... };` file (unquoted keys) into a JS object. */
function evalVarObject(file) {
  const raw = readFileSync(join(srcDir, file), 'utf8');
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  const body = raw.slice(start, end + 1);
  // eslint-disable-next-line no-new-func
  return new Function(`return (${body});`)();
}

const pokedex = parseVarObject('pokedex.js');
const natures = parseVarObject('natures.js');
const pokesEn = parseVarObject('PokesEn.js');
const movesEn = parseVarObject('MovesEn.js');
const itemsEn = parseVarObject('ItemsEn.js');
const abilitiesEn = parseVarObject('AbilitiesEn.js');

const uniqSorted = (arr) =>
  [...new Set(arr.filter((s) => typeof s === 'string' && s.length))].sort((a, b) =>
    a.localeCompare(b)
  );

const vocab = {
  species: uniqSorted(Object.keys(pokedex)),
  moves: uniqSorted(Object.values(movesEn)),
  items: uniqSorted(Object.values(itemsEn)),
  abilities: uniqSorted(Object.values(abilitiesEn)),
  natures: uniqSorted(Object.keys(natures)),
};

const fullPokedex = evalVarObject('pokedex-full.js');
const speciesTypes = {};
const speciesAbilities = {};
for (const entry of Object.values(fullPokedex)) {
  if (!entry || typeof entry.name !== 'string') continue;
  if (Array.isArray(entry.types)) speciesTypes[entry.name] = entry.types;
  if (entry.abilities && typeof entry.abilities === 'object') {
    speciesAbilities[entry.name] = uniqSorted(Object.values(entry.abilities));
  }
}

// Emit with keys in a stable, codepoint-sorted order so regeneration is diff-friendly and
// byte-identical across machines/locales (locale-aware compare must never be used here).
const sortKeys = (obj) =>
  Object.fromEntries(
    Object.keys(obj)
      .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
      .map((k) => [k, obj[k]])
  );

const header = '// AUTO-GENERATED by scripts/vendor-data.mjs — do not edit by hand.\n';

writeFileSync(
  join(outDir, 'pokedex.ts'),
  header +
    'export interface BaseStats { hp: number; atk: number; def: number; spa: number; spd: number; spe: number }\n' +
    'export const pokedex: Record<string, BaseStats> = ' +
    JSON.stringify(pokedex, null, 2) +
    ';\n'
);

writeFileSync(
  join(outDir, 'natures.ts'),
  header +
    'export interface NatureMultipliers { hp: number; atk: number; def: number; spa: number; spd: number; spe: number }\n' +
    'export const natures: Record<string, NatureMultipliers> = ' +
    JSON.stringify(natures, null, 2) +
    ';\n'
);

writeFileSync(
  join(outDir, 'vocab.ts'),
  header +
    'export interface Vocab { species: string[]; moves: string[]; items: string[]; abilities: string[]; natures: string[] }\n' +
    'export const vocab: Vocab = ' +
    JSON.stringify(vocab, null, 2) +
    ';\n'
);

writeFileSync(
  join(outDir, 'species-types.ts'),
  header +
    'export const speciesTypes: Record<string, string[]> = ' +
    JSON.stringify(sortKeys(speciesTypes), null, 2) +
    ';\n'
);

writeFileSync(
  join(outDir, 'species-abilities.ts'),
  header +
    'export const speciesAbilities: Record<string, string[]> = ' +
    JSON.stringify(sortKeys(speciesAbilities), null, 2) +
    ';\n'
);

console.log('vendored:', {
  species: vocab.species.length,
  moves: vocab.moves.length,
  items: vocab.items.length,
  abilities: vocab.abilities.length,
  natures: vocab.natures.length,
  pokedexKeys: Object.keys(pokedex).length,
  speciesTypes: Object.keys(speciesTypes).length,
  speciesAbilities: Object.keys(speciesAbilities).length,
  poke1: pokesEn['001_000'],
});
