// Extract fixed-font digit templates (0-9) from the known stat values on both stats
// screenshots, and emit src/ocr/digit-templates.ts. Run: npx tsx tools/build-digit-templates.mts
import { loadImage, createCanvas } from '@napi-rs/canvas';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFileSync } from 'node:fs';
import { CARDS, within, toPixels, statsFields, Rect } from '../src/ocr/layout.js';
import { binarize, detectColumnClusters, RegionData } from '../src/ocr/pixels.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const TW = 14;
export const TH = 20;

// Known final-stat values, slot order 0..5, stat order hp,atk,def,spa,spd,spe.
const VALUES: any = {
  t1: [
    [206, 188, 140, 72, 123, 71],
    [159, 67, 111, 182, 101, 151],
    [155, 78, 111, 105, 95, 184],
    [163, 80, 104, 152, 120, 161],
    [185, 182, 115, 90, 105, 169],
    [189, 141, 90, 63, 84, 167],
  ],
  t2: [
    [189, 141, 90, 63, 84, 167],
    [163, 80, 104, 152, 120, 161],
    [155, 78, 111, 105, 95, 184],
    [185, 182, 115, 90, 105, 169],
    [159, 67, 111, 182, 101, 151],
    [206, 188, 140, 72, 123, 71],
  ],
};

function rd(img: any, frac: Rect): RegionData {
  const px = toPixels(frac, img.width, img.height);
  const c = createCanvas(px.w, px.h);
  const cx = c.getContext('2d');
  cx.drawImage(img, px.x, px.y, px.w, px.h, 0, 0, px.w, px.h);
  return { data: cx.getImageData(0, 0, px.w, px.h).data as any, width: px.w, height: px.h };
}

/** Normalize a sub-rect of a binarized region (its ink bounding box) to a TWxTH 0/1 grid. */
function normalizeGlyph(reg: RegionData, x0: number, x1: number): number[] {
  // ink bbox within [x0,x1]
  let minY = 1e9, maxY = -1, minX = 1e9, maxX = -1;
  for (let y = 0; y < reg.height; y++)
    for (let x = x0; x <= x1; x++)
      if (reg.data[(y * reg.width + x) * 4] < 128) { if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y; }
  if (maxX < 0) return new Array(TW * TH).fill(0);
  const gw = maxX - minX + 1, gh = maxY - minY + 1;
  const out = new Array(TW * TH).fill(0);
  // Area-average (must match normalizeGlyph in src/ocr/digits.ts) so templates and runtime glyphs
  // share one scale-invariant representation.
  for (let ty = 0; ty < TH; ty++)
    for (let tx = 0; tx < TW; tx++) {
      const sx0 = minX + Math.floor((tx / TW) * gw);
      const sx1 = Math.max(sx0 + 1, minX + Math.floor(((tx + 1) / TW) * gw));
      const sy0 = minY + Math.floor((ty / TH) * gh);
      const sy1 = Math.max(sy0 + 1, minY + Math.floor(((ty + 1) / TH) * gh));
      let ink = 0, total = 0;
      for (let sy = sy0; sy < sy1 && sy <= maxY; sy++)
        for (let sx = sx0; sx < sx1 && sx <= maxX; sx++) { total++; if (reg.data[(sy * reg.width + sx) * 4] < 128) ink++; }
      out[ty * TW + tx] = total > 0 && ink * 2 >= total ? 1 : 0;
    }
  return out;
}

const acc: Record<string, { sum: number[]; n: number }> = {};
for (let d = 0; d <= 9; d++) acc[d] = { sum: new Array(TW * TH).fill(0), n: 0 };

const imgs: any = { t1: await loadImage(join(root, 'sample/stats.jpg')), t2: await loadImage(join(root, 'sample/team2-stats.jpg')) };
for (const tk of ['t1', 't2']) {
  for (let slot = 0; slot < 6; slot++) {
    for (let s = 0; s < 6; s++) {
      const str = String(VALUES[tk][slot][s]);
      const reg = binarize(rd(imgs[tk], within(CARDS[slot], statsFields.statValue[s])), { threshold: 170 });
      const cl = detectColumnClusters(reg, { mergeGap: 1, minWidthFrac: 0.01, minInkFrac: 0.05 });
      if (cl.length !== str.length) continue; // skip ambiguous segmentation
      for (let i = 0; i < str.length; i++) {
        const g = normalizeGlyph(reg, cl[i].x0, cl[i].x1);
        const a = acc[str[i]];
        for (let k = 0; k < g.length; k++) a.sum[k] += g[k];
        a.n++;
      }
    }
  }
}

const templates: Record<string, number[]> = {};
for (let d = 0; d <= 9; d++) {
  const a = acc[d];
  templates[d] = a.sum.map((v) => (a.n && v / a.n >= 0.5 ? 1 : 0));
  console.log(`digit ${d}: ${a.n} samples`);
}

const packed = Object.fromEntries(Object.entries(templates).map(([d, t]) => [d, t.join('')]));
writeFileSync(
  join(root, 'src/ocr/digit-templates.ts'),
  '// AUTO-GENERATED by tools/build-digit-templates.mts — fixed-font digit templates.\n' +
    `export const TW = ${TW};\nexport const TH = ${TH};\n` +
    'export const DIGIT_TEMPLATES: Record<string, string> = ' + JSON.stringify(packed, null, 2) + ';\n'
);
console.log('wrote src/ocr/digit-templates.ts');
