// AUTO-GENERATED by scripts/vendor-data.mjs — do not edit by hand.
export const speciesTypes: Record<string, string[]> = {
  "Ababo": [
    "Fairy"
  ],
  "Abomasnow": [
    "Grass",
    "Ice"
  ],
  "Abomasnow-Mega": [
    "Grass",
    "Ice"
  ],
  "Abra": [
    "Psychic"
  ],
  "Absol": [
    "Dark"
  ],
  "Absol-Mega": [
    "Dark"
  ],
  "Absol-Mega-Z": [
    "Dark",
    "Ghost"
  ],
  "Accelgor": [
    "Bug"
  ],
  "Aegislash": [
    "Steel",
    "Ghost"
  ],
  "Aegislash-Blade": [
    "Steel",
    "Ghost"
  ],
  "Aerodactyl": [
    "Rock",
    "Flying"
  ],
  "Aerodactyl-Mega": [
    "Rock",
    "Flying"
  ],
  "Aggron": [
    "Steel",
    "Rock"
  ],
  "Aggron-Mega": [
    "Steel"
  ],
  "Aipom": [
    "Normal"
  ],
  "Alakazam": [
    "Psychic"
  ],
  "Alakazam-Mega": [
    "Psychic"
  ],
  "Alcremie": [
    "Fairy"
  ],
  "Alcremie-Gmax": [
    "Fairy"
  ],
  "Alomomola": [
    "Water"
  ],
  "Altaria": [
    "Dragon",
    "Flying"
  ],
  "Altaria-Mega": [
    "Dragon",
    "Fairy"
  ],
  "Amaura": [
    "Rock",
    "Ice"
  ],
  "Ambipom": [
    "Normal"
  ],
  "Amoonguss": [
    "Grass",
    "Poison"
  ],
  "Ampharos": [
    "Electric"
  ],
  "Ampharos-Mega": [
    "Electric",
    "Dragon"
  ],
  "Annihilape": [
    "Fighting",
    "Ghost"
  ],
  "Anorith": [
    "Rock",
    "Bug"
  ],
  "Appletun": [
    "Grass",
    "Dragon"
  ],
  "Appletun-Gmax": [
    "Grass",
    "Dragon"
  ],
  "Applin": [
    "Grass",
    "Dragon"
  ],
  "Araquanid": [
    "Water",
    "Bug"
  ],
  "Araquanid-Totem": [
    "Water",
    "Bug"
  ],
  "Arbok": [
    "Poison"
  ],
  "Arboliva": [
    "Grass",
    "Normal"
  ],
  "Arcanine": [
    "Fire"
  ],
  "Arcanine-Hisui": [
    "Fire",
    "Rock"
  ],
  "Arceus": [
    "Normal"
  ],
  "Arceus-Bug": [
    "Bug"
  ],
  "Arceus-Dark": [
    "Dark"
  ],
  "Arceus-Dragon": [
    "Dragon"
  ],
  "Arceus-Electric": [
    "Electric"
  ],
  "Arceus-Fairy": [
    "Fairy"
  ],
  "Arceus-Fighting": [
    "Fighting"
  ],
  "Arceus-Fire": [
    "Fire"
  ],
  "Arceus-Flying": [
    "Flying"
  ],
  "Arceus-Ghost": [
    "Ghost"
  ],
  "Arceus-Grass": [
    "Grass"
  ],
  "Arceus-Ground": [
    "Ground"
  ],
  "Arceus-Ice": [
    "Ice"
  ],
  "Arceus-Poison": [
    "Poison"
  ],
  "Arceus-Psychic": [
    "Psychic"
  ],
  "Arceus-Rock": [
    "Rock"
  ],
  "Arceus-Steel": [
    "Steel"
  ],
  "Arceus-Water": [
    "Water"
  ],
  "Archaludon": [
    "Steel",
    "Dragon"
  ],
  "Archen": [
    "Rock",
    "Flying"
  ],
  "Archeops": [
    "Rock",
    "Flying"
  ],
  "Arctibax": [
    "Dragon",
    "Ice"
  ],
  "Arctovish": [
    "Water",
    "Ice"
  ],
  "Arctozolt": [
    "Electric",
    "Ice"
  ],
  "Argalis": [
    "Bug",
    "Psychic"
  ],
  "Arghonaut": [
    "Water",
    "Fighting"
  ],
  "Ariados": [
    "Bug",
    "Poison"
  ],
  "Armaldo": [
    "Rock",
    "Bug"
  ],
  "Armarouge": [
    "Fire",
    "Psychic"
  ],
  "Aromatisse": [
    "Fairy"
  ],
  "Aron": [
    "Steel",
    "Rock"
  ],
  "Arrokuda": [
    "Water"
  ],
  "Articuno": [
    "Ice",
    "Flying"
  ],
  "Articuno-Galar": [
    "Psychic",
    "Flying"
  ],
  "Astrolotl": [
    "Fire",
    "Dragon"
  ],
  "Audino": [
    "Normal"
  ],
  "Audino-Mega": [
    "Normal",
    "Fairy"
  ],
  "Aurorus": [
    "Rock",
    "Ice"
  ],
  "Aurumoth": [
    "Bug",
    "Psychic"
  ],
  "Avalugg": [
    "Ice"
  ],
  "Avalugg-Hisui": [
    "Ice",
    "Rock"
  ],
  "Axew": [
    "Dragon"
  ],
  "Azelf": [
    "Psychic"
  ],
  "Azumarill": [
    "Water",
    "Fairy"
  ],
  "Azurill": [
    "Normal",
    "Fairy"
  ],
  "Bagon": [
    "Dragon"
  ],
  "Baltoy": [
    "Ground",
    "Psychic"
  ],
  "Banette": [
    "Ghost"
  ],
  "Banette-Mega": [
    "Ghost"
  ],
  "Barbaracle": [
    "Rock",
    "Water"
  ],
  "Barbaracle-Mega": [
    "Rock",
    "Fighting"
  ],
  "Barboach": [
    "Water",
    "Ground"
  ],
  "Barraskewda": [
    "Water"
  ],
  "Basculegion": [
    "Water",
    "Ghost"
  ],
  "Basculegion-F": [
    "Water",
    "Ghost"
  ],
  "Basculin": [
    "Water"
  ],
  "Basculin-Blue-Striped": [
    "Water"
  ],
  "Basculin-White-Striped": [
    "Water"
  ],
  "Bastiodon": [
    "Rock",
    "Steel"
  ],
  "Baxcalibur": [
    "Dragon",
    "Ice"
  ],
  "Baxcalibur-Mega": [
    "Dragon",
    "Ice"
  ],
  "Bayleef": [
    "Grass"
  ],
  "Beartic": [
    "Ice"
  ],
  "Beautifly": [
    "Bug",
    "Flying"
  ],
  "Beedrill": [
    "Bug",
    "Poison"
  ],
  "Beedrill-Mega": [
    "Bug",
    "Poison"
  ],
  "Beheeyem": [
    "Psychic"
  ],
  "Beldum": [
    "Steel",
    "Psychic"
  ],
  "Bellibolt": [
    "Electric"
  ],
  "Bellossom": [
    "Grass"
  ],
  "Bellsprout": [
    "Grass",
    "Poison"
  ],
  "Bergmite": [
    "Ice"
  ],
  "Bewear": [
    "Normal",
    "Fighting"
  ],
  "Bibarel": [
    "Normal",
    "Water"
  ],
  "Bidoof": [
    "Normal"
  ],
  "Binacle": [
    "Rock",
    "Water"
  ],
  "Bisharp": [
    "Dark",
    "Steel"
  ],
  "Blacephalon": [
    "Fire",
    "Ghost"
  ],
  "Blastoise": [
    "Water"
  ],
  "Blastoise-Gmax": [
    "Water"
  ],
  "Blastoise-Mega": [
    "Water"
  ],
  "Blaziken": [
    "Fire",
    "Fighting"
  ],
  "Blaziken-Mega": [
    "Fire",
    "Fighting"
  ],
  "Blipbug": [
    "Bug"
  ],
  "Blissey": [
    "Normal"
  ],
  "Blitzle": [
    "Electric"
  ],
  "Boldore": [
    "Rock"
  ],
  "Boltund": [
    "Electric"
  ],
  "Bombirdier": [
    "Flying",
    "Dark"
  ],
  "Bonsly": [
    "Rock"
  ],
  "Bouffalant": [
    "Normal"
  ],
  "Bounsweet": [
    "Grass"
  ],
  "Braixen": [
    "Fire"
  ],
  "Brambleghast": [
    "Grass",
    "Ghost"
  ],
  "Bramblin": [
    "Grass",
    "Ghost"
  ],
  "Brattler": [
    "Dark",
    "Grass"
  ],
  "Braviary": [
    "Normal",
    "Flying"
  ],
  "Braviary-Hisui": [
    "Psychic",
    "Flying"
  ],
  "Breezi": [
    "Poison",
    "Flying"
  ],
  "Breloom": [
    "Grass",
    "Fighting"
  ],
  "Brionne": [
    "Water"
  ],
  "Bronzong": [
    "Steel",
    "Psychic"
  ],
  "Bronzor": [
    "Steel",
    "Psychic"
  ],
  "Brute Bonnet": [
    "Grass",
    "Dark"
  ],
  "Bruxish": [
    "Water",
    "Psychic"
  ],
  "Budew": [
    "Grass",
    "Poison"
  ],
  "Buizel": [
    "Water"
  ],
  "Bulbasaur": [
    "Grass",
    "Poison"
  ],
  "Buneary": [
    "Normal"
  ],
  "Bunnelby": [
    "Normal"
  ],
  "Burmy": [
    "Bug"
  ],
  "Butterfree": [
    "Bug",
    "Flying"
  ],
  "Butterfree-Gmax": [
    "Bug",
    "Flying"
  ],
  "Buzzwole": [
    "Bug",
    "Fighting"
  ],
  "Cacnea": [
    "Grass"
  ],
  "Cacturne": [
    "Grass",
    "Dark"
  ],
  "Caimanoe": [
    "Water",
    "Steel"
  ],
  "Calyrex": [
    "Psychic",
    "Grass"
  ],
  "Calyrex-Ice": [
    "Psychic",
    "Ice"
  ],
  "Calyrex-Shadow": [
    "Psychic",
    "Ghost"
  ],
  "Camerupt": [
    "Fire",
    "Ground"
  ],
  "Camerupt-Mega": [
    "Fire",
    "Ground"
  ],
  "Capsakid": [
    "Grass"
  ],
  "Carbink": [
    "Rock",
    "Fairy"
  ],
  "Caribolt": [
    "Grass",
    "Electric"
  ],
  "Carkol": [
    "Rock",
    "Fire"
  ],
  "Carnivine": [
    "Grass"
  ],
  "Carracosta": [
    "Water",
    "Rock"
  ],
  "Carvanha": [
    "Water",
    "Dark"
  ],
  "Cascoon": [
    "Bug"
  ],
  "Castform": [
    "Normal"
  ],
  "Castform-Rainy": [
    "Water"
  ],
  "Castform-Snowy": [
    "Ice"
  ],
  "Castform-Sunny": [
    "Fire"
  ],
  "Caterpie": [
    "Bug"
  ],
  "Cawdet": [
    "Steel",
    "Flying"
  ],
  "Cawmodore": [
    "Steel",
    "Flying"
  ],
  "Celebi": [
    "Psychic",
    "Grass"
  ],
  "Celesteela": [
    "Steel",
    "Flying"
  ],
  "Centiskorch": [
    "Fire",
    "Bug"
  ],
  "Centiskorch-Gmax": [
    "Fire",
    "Bug"
  ],
  "Ceruledge": [
    "Fire",
    "Ghost"
  ],
  "Cetitan": [
    "Ice"
  ],
  "Cetoddle": [
    "Ice"
  ],
  "Chandelure": [
    "Ghost",
    "Fire"
  ],
  "Chandelure-Mega": [
    "Ghost",
    "Fire"
  ],
  "Chansey": [
    "Normal"
  ],
  "Charcadet": [
    "Fire"
  ],
  "Charizard": [
    "Fire",
    "Flying"
  ],
  "Charizard-Gmax": [
    "Fire",
    "Flying"
  ],
  "Charizard-Mega-X": [
    "Fire",
    "Dragon"
  ],
  "Charizard-Mega-Y": [
    "Fire",
    "Flying"
  ],
  "Charjabug": [
    "Bug",
    "Electric"
  ],
  "Charmander": [
    "Fire"
  ],
  "Charmeleon": [
    "Fire"
  ],
  "Chatot": [
    "Normal",
    "Flying"
  ],
  "Cherrim": [
    "Grass"
  ],
  "Cherrim-Sunshine": [
    "Grass"
  ],
  "Cherubi": [
    "Grass"
  ],
  "Chesnaught": [
    "Grass",
    "Fighting"
  ],
  "Chesnaught-Mega": [
    "Grass",
    "Fighting"
  ],
  "Chespin": [
    "Grass"
  ],
  "Chewtle": [
    "Water"
  ],
  "Chi-Yu": [
    "Dark",
    "Fire"
  ],
  "Chien-Pao": [
    "Dark",
    "Ice"
  ],
  "Chikorita": [
    "Grass"
  ],
  "Chimchar": [
    "Fire"
  ],
  "Chimecho": [
    "Psychic"
  ],
  "Chimecho-Mega": [
    "Psychic",
    "Steel"
  ],
  "Chinchou": [
    "Water",
    "Electric"
  ],
  "Chingling": [
    "Psychic"
  ],
  "Chromera": [
    "Dark",
    "Normal"
  ],
  "Chuggalong": [
    "Dragon",
    "Poison"
  ],
  "Chuggon": [
    "Dragon",
    "Poison"
  ],
  "Cinccino": [
    "Normal"
  ],
  "Cinderace": [
    "Fire"
  ],
  "Cinderace-Gmax": [
    "Fire"
  ],
  "Clamperl": [
    "Water"
  ],
  "Clauncher": [
    "Water"
  ],
  "Clawitzer": [
    "Water"
  ],
  "Claydol": [
    "Ground",
    "Psychic"
  ],
  "Clefable": [
    "Fairy"
  ],
  "Clefable-Mega": [
    "Fairy",
    "Flying"
  ],
  "Clefairy": [
    "Fairy"
  ],
  "Cleffa": [
    "Fairy"
  ],
  "Clobbopus": [
    "Fighting"
  ],
  "Clodsire": [
    "Poison",
    "Ground"
  ],
  "Cloyster": [
    "Water",
    "Ice"
  ],
  "Coalossal": [
    "Rock",
    "Fire"
  ],
  "Coalossal-Gmax": [
    "Rock",
    "Fire"
  ],
  "Cobalion": [
    "Steel",
    "Fighting"
  ],
  "Cofagrigus": [
    "Ghost"
  ],
  "Colossoil": [
    "Ground",
    "Dark"
  ],
  "Combee": [
    "Bug",
    "Flying"
  ],
  "Combusken": [
    "Fire",
    "Fighting"
  ],
  "Comfey": [
    "Fairy"
  ],
  "Conkeldurr": [
    "Fighting"
  ],
  "Copperajah": [
    "Steel"
  ],
  "Copperajah-Gmax": [
    "Steel"
  ],
  "Coribalis": [
    "Water",
    "Bug"
  ],
  "Corphish": [
    "Water"
  ],
  "Corsola": [
    "Water",
    "Rock"
  ],
  "Corsola-Galar": [
    "Ghost"
  ],
  "Corviknight": [
    "Flying",
    "Steel"
  ],
  "Corviknight-Gmax": [
    "Flying",
    "Steel"
  ],
  "Corvisquire": [
    "Flying"
  ],
  "Cosmoem": [
    "Psychic"
  ],
  "Cosmog": [
    "Psychic"
  ],
  "Cottonee": [
    "Grass",
    "Fairy"
  ],
  "Crabominable": [
    "Fighting",
    "Ice"
  ],
  "Crabominable-Mega": [
    "Fighting",
    "Ice"
  ],
  "Crabrawler": [
    "Fighting"
  ],
  "Cradily": [
    "Rock",
    "Grass"
  ],
  "Cramorant": [
    "Flying",
    "Water"
  ],
  "Cramorant-Gorging": [
    "Flying",
    "Water"
  ],
  "Cramorant-Gulping": [
    "Flying",
    "Water"
  ],
  "Cranidos": [
    "Rock"
  ],
  "Crawdaunt": [
    "Water",
    "Dark"
  ],
  "Cresceidon": [
    "Water",
    "Fairy"
  ],
  "Cresselia": [
    "Psychic"
  ],
  "Croagunk": [
    "Poison",
    "Fighting"
  ],
  "Crobat": [
    "Poison",
    "Flying"
  ],
  "Crocalor": [
    "Fire"
  ],
  "Croconaw": [
    "Water"
  ],
  "Crucibelle": [
    "Rock",
    "Poison"
  ],
  "Crucibelle-Mega": [
    "Rock",
    "Poison"
  ],
  "Crustle": [
    "Bug",
    "Rock"
  ],
  "Cryogonal": [
    "Ice"
  ],
  "Cubchoo": [
    "Ice"
  ],
  "Cubone": [
    "Ground"
  ],
  "Cufant": [
    "Steel"
  ],
  "Cupra": [
    "Bug",
    "Psychic"
  ],
  "Cursola": [
    "Ghost"
  ],
  "Cutiefly": [
    "Bug",
    "Fairy"
  ],
  "Cyclizar": [
    "Dragon",
    "Normal"
  ],
  "Cyclohm": [
    "Electric",
    "Dragon"
  ],
  "Cyndaquil": [
    "Fire"
  ],
  "Dachsbun": [
    "Fairy"
  ],
  "Darkrai": [
    "Dark"
  ],
  "Darkrai-Mega": [
    "Dark"
  ],
  "Darmanitan": [
    "Fire"
  ],
  "Darmanitan-Galar": [
    "Ice"
  ],
  "Darmanitan-Galar-Zen": [
    "Ice",
    "Fire"
  ],
  "Darmanitan-Zen": [
    "Fire",
    "Psychic"
  ],
  "Dartrix": [
    "Grass",
    "Flying"
  ],
  "Darumaka": [
    "Fire"
  ],
  "Darumaka-Galar": [
    "Ice"
  ],
  "Decidueye": [
    "Grass",
    "Ghost"
  ],
  "Decidueye-Hisui": [
    "Grass",
    "Fighting"
  ],
  "Dedenne": [
    "Electric",
    "Fairy"
  ],
  "Deerling": [
    "Normal",
    "Grass"
  ],
  "Deino": [
    "Dark",
    "Dragon"
  ],
  "Delcatty": [
    "Normal"
  ],
  "Delibird": [
    "Ice",
    "Flying"
  ],
  "Delphox": [
    "Fire",
    "Psychic"
  ],
  "Delphox-Mega": [
    "Fire",
    "Psychic"
  ],
  "Deoxys": [
    "Psychic"
  ],
  "Deoxys-Attack": [
    "Psychic"
  ],
  "Deoxys-Defense": [
    "Psychic"
  ],
  "Deoxys-Speed": [
    "Psychic"
  ],
  "Dewgong": [
    "Water",
    "Ice"
  ],
  "Dewott": [
    "Water"
  ],
  "Dewpider": [
    "Water",
    "Bug"
  ],
  "Dhelmise": [
    "Ghost",
    "Grass"
  ],
  "Dialga": [
    "Steel",
    "Dragon"
  ],
  "Dialga-Origin": [
    "Steel",
    "Dragon"
  ],
  "Diancie": [
    "Rock",
    "Fairy"
  ],
  "Diancie-Mega": [
    "Rock",
    "Fairy"
  ],
  "Diggersby": [
    "Normal",
    "Ground"
  ],
  "Diglett": [
    "Ground"
  ],
  "Diglett-Alola": [
    "Ground",
    "Steel"
  ],
  "Dipplin": [
    "Grass",
    "Dragon"
  ],
  "Ditto": [
    "Normal"
  ],
  "Dodrio": [
    "Normal",
    "Flying"
  ],
  "Doduo": [
    "Normal",
    "Flying"
  ],
  "Dolliv": [
    "Grass",
    "Normal"
  ],
  "Dondozo": [
    "Water"
  ],
  "Donphan": [
    "Ground"
  ],
  "Dorsoil": [
    "Ground"
  ],
  "Dottler": [
    "Bug",
    "Psychic"
  ],
  "Doublade": [
    "Steel",
    "Ghost"
  ],
  "Dracovish": [
    "Water",
    "Dragon"
  ],
  "Dracozolt": [
    "Electric",
    "Dragon"
  ],
  "Dragalge": [
    "Poison",
    "Dragon"
  ],
  "Dragalge-Mega": [
    "Poison",
    "Dragon"
  ],
  "Dragapult": [
    "Dragon",
    "Ghost"
  ],
  "Draggalong": [
    "Dragon",
    "Poison"
  ],
  "Dragonair": [
    "Dragon"
  ],
  "Dragonite": [
    "Dragon",
    "Flying"
  ],
  "Dragonite-Mega": [
    "Dragon",
    "Flying"
  ],
  "Drakloak": [
    "Dragon",
    "Ghost"
  ],
  "Drampa": [
    "Normal",
    "Dragon"
  ],
  "Drampa-Mega": [
    "Normal",
    "Dragon"
  ],
  "Drapion": [
    "Poison",
    "Dark"
  ],
  "Dratini": [
    "Dragon"
  ],
  "Drednaw": [
    "Water",
    "Rock"
  ],
  "Drednaw-Gmax": [
    "Water",
    "Rock"
  ],
  "Dreepy": [
    "Dragon",
    "Ghost"
  ],
  "Drifblim": [
    "Ghost",
    "Flying"
  ],
  "Drifloon": [
    "Ghost",
    "Flying"
  ],
  "Drilbur": [
    "Ground"
  ],
  "Drizzile": [
    "Water"
  ],
  "Drowzee": [
    "Psychic"
  ],
  "Druddigon": [
    "Dragon"
  ],
  "Dubwool": [
    "Normal"
  ],
  "Ducklett": [
    "Water",
    "Flying"
  ],
  "Dudunsparce": [
    "Normal"
  ],
  "Dudunsparce-Three-Segment": [
    "Normal"
  ],
  "Dugtrio": [
    "Ground"
  ],
  "Dugtrio-Alola": [
    "Ground",
    "Steel"
  ],
  "Dunsparce": [
    "Normal"
  ],
  "Duohm": [
    "Electric",
    "Dragon"
  ],
  "Duosion": [
    "Psychic"
  ],
  "Duraludon": [
    "Steel",
    "Dragon"
  ],
  "Duraludon-Gmax": [
    "Steel",
    "Dragon"
  ],
  "Durant": [
    "Bug",
    "Steel"
  ],
  "Dusclops": [
    "Ghost"
  ],
  "Dusknoir": [
    "Ghost"
  ],
  "Duskull": [
    "Ghost"
  ],
  "Dustox": [
    "Bug",
    "Poison"
  ],
  "Dwebble": [
    "Bug",
    "Rock"
  ],
  "Eelektrik": [
    "Electric"
  ],
  "Eelektross": [
    "Electric"
  ],
  "Eelektross-Mega": [
    "Electric"
  ],
  "Eevee": [
    "Normal"
  ],
  "Eevee-Gmax": [
    "Normal"
  ],
  "Eevee-Starter": [
    "Normal"
  ],
  "Eiscue": [
    "Ice"
  ],
  "Eiscue-Noice": [
    "Ice"
  ],
  "Ekans": [
    "Poison"
  ],
  "Eldegoss": [
    "Grass"
  ],
  "Electabuzz": [
    "Electric"
  ],
  "Electivire": [
    "Electric"
  ],
  "Electrelk": [
    "Grass",
    "Electric"
  ],
  "Electrike": [
    "Electric"
  ],
  "Electrode": [
    "Electric"
  ],
  "Electrode-Hisui": [
    "Electric",
    "Grass"
  ],
  "Elekid": [
    "Electric"
  ],
  "Elgyem": [
    "Psychic"
  ],
  "Embirch": [
    "Fire",
    "Grass"
  ],
  "Emboar": [
    "Fire",
    "Fighting"
  ],
  "Emboar-Mega": [
    "Fire",
    "Fighting"
  ],
  "Emolga": [
    "Electric",
    "Flying"
  ],
  "Empoleon": [
    "Water",
    "Steel"
  ],
  "Enamorus": [
    "Fairy",
    "Flying"
  ],
  "Enamorus-Therian": [
    "Fairy",
    "Flying"
  ],
  "Entei": [
    "Fire"
  ],
  "Equilibra": [
    "Steel",
    "Ground"
  ],
  "Escavalier": [
    "Bug",
    "Steel"
  ],
  "Espathra": [
    "Psychic"
  ],
  "Espeon": [
    "Psychic"
  ],
  "Espurr": [
    "Psychic"
  ],
  "Eternatus": [
    "Poison",
    "Dragon"
  ],
  "Eternatus-Eternamax": [
    "Poison",
    "Dragon"
  ],
  "Excadrill": [
    "Ground",
    "Steel"
  ],
  "Excadrill-Mega": [
    "Ground",
    "Steel"
  ],
  "Exeggcute": [
    "Grass",
    "Psychic"
  ],
  "Exeggutor": [
    "Grass",
    "Psychic"
  ],
  "Exeggutor-Alola": [
    "Grass",
    "Dragon"
  ],
  "Exploud": [
    "Normal"
  ],
  "Falinks": [
    "Fighting"
  ],
  "Falinks-Mega": [
    "Fighting"
  ],
  "Farfetch’d": [
    "Normal",
    "Flying"
  ],
  "Farfetch’d-Galar": [
    "Fighting"
  ],
  "Farigiraf": [
    "Normal",
    "Psychic"
  ],
  "Fawnifer": [
    "Grass"
  ],
  "Fearow": [
    "Normal",
    "Flying"
  ],
  "Feebas": [
    "Water"
  ],
  "Fennekin": [
    "Fire"
  ],
  "Feraligatr": [
    "Water"
  ],
  "Feraligatr-Mega": [
    "Water",
    "Dragon"
  ],
  "Ferroseed": [
    "Grass",
    "Steel"
  ],
  "Ferrothorn": [
    "Grass",
    "Steel"
  ],
  "Fezandipiti": [
    "Poison",
    "Fairy"
  ],
  "Fidgit": [
    "Poison",
    "Ground"
  ],
  "Fidough": [
    "Fairy"
  ],
  "Finizen": [
    "Water"
  ],
  "Finneon": [
    "Water"
  ],
  "Flaaffy": [
    "Electric"
  ],
  "Flabébé": [
    "Fairy"
  ],
  "Flamigo": [
    "Flying",
    "Fighting"
  ],
  "Flapple": [
    "Grass",
    "Dragon"
  ],
  "Flapple-Gmax": [
    "Grass",
    "Dragon"
  ],
  "Flarelm": [
    "Fire",
    "Grass"
  ],
  "Flareon": [
    "Fire"
  ],
  "Fletchinder": [
    "Fire",
    "Flying"
  ],
  "Fletchling": [
    "Normal",
    "Flying"
  ],
  "Flittle": [
    "Psychic"
  ],
  "Floatoy": [
    "Water"
  ],
  "Floatzel": [
    "Water"
  ],
  "Floette": [
    "Fairy"
  ],
  "Floette-Eternal": [
    "Fairy"
  ],
  "Floette-Mega": [
    "Fairy"
  ],
  "Floragato": [
    "Grass"
  ],
  "Florges": [
    "Fairy"
  ],
  "Flox": [
    "Normal",
    "Electric"
  ],
  "Flutter Mane": [
    "Ghost",
    "Fairy"
  ],
  "Flygon": [
    "Ground",
    "Dragon"
  ],
  "Fomantis": [
    "Grass"
  ],
  "Foongus": [
    "Grass",
    "Poison"
  ],
  "Forretress": [
    "Bug",
    "Steel"
  ],
  "Fraxure": [
    "Dragon"
  ],
  "Frigibax": [
    "Dragon",
    "Ice"
  ],
  "Frillish": [
    "Water",
    "Ghost"
  ],
  "Froakie": [
    "Water"
  ],
  "Frogadier": [
    "Water"
  ],
  "Froslass": [
    "Ice",
    "Ghost"
  ],
  "Froslass-Mega": [
    "Ice",
    "Ghost"
  ],
  "Frosmoth": [
    "Ice",
    "Bug"
  ],
  "Fuecoco": [
    "Fire"
  ],
  "Furfrou": [
    "Normal"
  ],
  "Furret": [
    "Normal"
  ],
  "Gabite": [
    "Dragon",
    "Ground"
  ],
  "Gallade": [
    "Psychic",
    "Fighting"
  ],
  "Gallade-Mega": [
    "Psychic",
    "Fighting"
  ],
  "Galvantula": [
    "Bug",
    "Electric"
  ],
  "Garbodor": [
    "Poison"
  ],
  "Garbodor-Gmax": [
    "Poison"
  ],
  "Garchomp": [
    "Dragon",
    "Ground"
  ],
  "Garchomp-Mega": [
    "Dragon",
    "Ground"
  ],
  "Garchomp-Mega-Z": [
    "Dragon"
  ],
  "Gardevoir": [
    "Psychic",
    "Fairy"
  ],
  "Gardevoir-Mega": [
    "Psychic",
    "Fairy"
  ],
  "Garganacl": [
    "Rock"
  ],
  "Gastly": [
    "Ghost",
    "Poison"
  ],
  "Gastrodon": [
    "Water",
    "Ground"
  ],
  "Genesect": [
    "Bug",
    "Steel"
  ],
  "Genesect-Burn": [
    "Bug",
    "Steel"
  ],
  "Genesect-Chill": [
    "Bug",
    "Steel"
  ],
  "Genesect-Douse": [
    "Bug",
    "Steel"
  ],
  "Genesect-Shock": [
    "Bug",
    "Steel"
  ],
  "Gengar": [
    "Ghost",
    "Poison"
  ],
  "Gengar-Gmax": [
    "Ghost",
    "Poison"
  ],
  "Gengar-Mega": [
    "Ghost",
    "Poison"
  ],
  "Geodude": [
    "Rock",
    "Ground"
  ],
  "Geodude-Alola": [
    "Rock",
    "Electric"
  ],
  "Gholdengo": [
    "Steel",
    "Ghost"
  ],
  "Gible": [
    "Dragon",
    "Ground"
  ],
  "Gigalith": [
    "Rock"
  ],
  "Gimmighoul": [
    "Ghost"
  ],
  "Gimmighoul-Roaming": [
    "Ghost"
  ],
  "Girafarig": [
    "Normal",
    "Psychic"
  ],
  "Giratina": [
    "Ghost",
    "Dragon"
  ],
  "Giratina-Origin": [
    "Ghost",
    "Dragon"
  ],
  "Glaceon": [
    "Ice"
  ],
  "Glalie": [
    "Ice"
  ],
  "Glalie-Mega": [
    "Ice"
  ],
  "Glameow": [
    "Normal"
  ],
  "Glastrier": [
    "Ice"
  ],
  "Gligar": [
    "Ground",
    "Flying"
  ],
  "Glimmet": [
    "Rock",
    "Poison"
  ],
  "Glimmora": [
    "Rock",
    "Poison"
  ],
  "Glimmora-Mega": [
    "Rock",
    "Poison"
  ],
  "Gliscor": [
    "Ground",
    "Flying"
  ],
  "Gloom": [
    "Grass",
    "Poison"
  ],
  "Gogoat": [
    "Grass"
  ],
  "Golbat": [
    "Poison",
    "Flying"
  ],
  "Goldeen": [
    "Water"
  ],
  "Golduck": [
    "Water"
  ],
  "Golem": [
    "Rock",
    "Ground"
  ],
  "Golem-Alola": [
    "Rock",
    "Electric"
  ],
  "Golett": [
    "Ground",
    "Ghost"
  ],
  "Golisopod": [
    "Bug",
    "Water"
  ],
  "Golisopod-Mega": [
    "Bug",
    "Steel"
  ],
  "Golurk": [
    "Ground",
    "Ghost"
  ],
  "Golurk-Mega": [
    "Ground",
    "Ghost"
  ],
  "Goodra": [
    "Dragon"
  ],
  "Goodra-Hisui": [
    "Steel",
    "Dragon"
  ],
  "Goomy": [
    "Dragon"
  ],
  "Gorebyss": [
    "Water"
  ],
  "Gossifleur": [
    "Grass"
  ],
  "Gothita": [
    "Psychic"
  ],
  "Gothitelle": [
    "Psychic"
  ],
  "Gothorita": [
    "Psychic"
  ],
  "Gouging Fire": [
    "Fire",
    "Dragon"
  ],
  "Gourgeist": [
    "Ghost",
    "Grass"
  ],
  "Gourgeist-Large": [
    "Ghost",
    "Grass"
  ],
  "Gourgeist-Small": [
    "Ghost",
    "Grass"
  ],
  "Gourgeist-Super": [
    "Ghost",
    "Grass"
  ],
  "Grafaiai": [
    "Poison",
    "Normal"
  ],
  "Granbull": [
    "Fairy"
  ],
  "Grapploct": [
    "Fighting"
  ],
  "Graveler": [
    "Rock",
    "Ground"
  ],
  "Graveler-Alola": [
    "Rock",
    "Electric"
  ],
  "Great Tusk": [
    "Ground",
    "Fighting"
  ],
  "Greavard": [
    "Ghost"
  ],
  "Greedent": [
    "Normal"
  ],
  "Greninja": [
    "Water",
    "Dark"
  ],
  "Greninja-Ash": [
    "Water",
    "Dark"
  ],
  "Greninja-Bond": [
    "Water",
    "Dark"
  ],
  "Greninja-Mega": [
    "Water",
    "Dark"
  ],
  "Grimer": [
    "Poison"
  ],
  "Grimer-Alola": [
    "Poison",
    "Dark"
  ],
  "Grimmsnarl": [
    "Dark",
    "Fairy"
  ],
  "Grimmsnarl-Gmax": [
    "Dark",
    "Fairy"
  ],
  "Grookey": [
    "Grass"
  ],
  "Grotle": [
    "Grass"
  ],
  "Groudon": [
    "Ground"
  ],
  "Groudon-Primal": [
    "Ground",
    "Fire"
  ],
  "Grovyle": [
    "Grass"
  ],
  "Growlithe": [
    "Fire"
  ],
  "Growlithe-Hisui": [
    "Fire",
    "Rock"
  ],
  "Grubbin": [
    "Bug"
  ],
  "Grumpig": [
    "Psychic"
  ],
  "Gulpin": [
    "Poison"
  ],
  "Gumshoos": [
    "Normal"
  ],
  "Gumshoos-Totem": [
    "Normal"
  ],
  "Gurdurr": [
    "Fighting"
  ],
  "Guzzlord": [
    "Dark",
    "Dragon"
  ],
  "Gyarados": [
    "Water",
    "Flying"
  ],
  "Gyarados-Mega": [
    "Water",
    "Dark"
  ],
  "Hakamo-o": [
    "Dragon",
    "Fighting"
  ],
  "Happiny": [
    "Normal"
  ],
  "Hariyama": [
    "Fighting"
  ],
  "Hatenna": [
    "Psychic"
  ],
  "Hatterene": [
    "Psychic",
    "Fairy"
  ],
  "Hatterene-Gmax": [
    "Psychic",
    "Fairy"
  ],
  "Hattrem": [
    "Psychic"
  ],
  "Haunter": [
    "Ghost",
    "Poison"
  ],
  "Hawlucha": [
    "Fighting",
    "Flying"
  ],
  "Hawlucha-Mega": [
    "Fighting",
    "Flying"
  ],
  "Haxorus": [
    "Dragon"
  ],
  "Heatmor": [
    "Fire"
  ],
  "Heatran": [
    "Fire",
    "Steel"
  ],
  "Heatran-Mega": [
    "Fire",
    "Steel"
  ],
  "Heliolisk": [
    "Electric",
    "Normal"
  ],
  "Helioptile": [
    "Electric",
    "Normal"
  ],
  "Hemogoblin": [
    "Fairy",
    "Fire"
  ],
  "Heracross": [
    "Bug",
    "Fighting"
  ],
  "Heracross-Mega": [
    "Bug",
    "Fighting"
  ],
  "Herdier": [
    "Normal"
  ],
  "Hippopotas": [
    "Ground"
  ],
  "Hippowdon": [
    "Ground"
  ],
  "Hitmonchan": [
    "Fighting"
  ],
  "Hitmonlee": [
    "Fighting"
  ],
  "Hitmontop": [
    "Fighting"
  ],
  "Ho-Oh": [
    "Fire",
    "Flying"
  ],
  "Honchkrow": [
    "Dark",
    "Flying"
  ],
  "Honedge": [
    "Steel",
    "Ghost"
  ],
  "Hoopa": [
    "Psychic",
    "Ghost"
  ],
  "Hoopa-Unbound": [
    "Psychic",
    "Dark"
  ],
  "Hoothoot": [
    "Normal",
    "Flying"
  ],
  "Hoppip": [
    "Grass",
    "Flying"
  ],
  "Horsea": [
    "Water"
  ],
  "Houndoom": [
    "Dark",
    "Fire"
  ],
  "Houndoom-Mega": [
    "Dark",
    "Fire"
  ],
  "Houndour": [
    "Dark",
    "Fire"
  ],
  "Houndstone": [
    "Ghost"
  ],
  "Huntail": [
    "Water"
  ],
  "Hydrapple": [
    "Grass",
    "Dragon"
  ],
  "Hydreigon": [
    "Dark",
    "Dragon"
  ],
  "Hypno": [
    "Psychic"
  ],
  "Igglybuff": [
    "Normal",
    "Fairy"
  ],
  "Illumise": [
    "Bug"
  ],
  "Impidimp": [
    "Dark",
    "Fairy"
  ],
  "Incineroar": [
    "Fire",
    "Dark"
  ],
  "Indeedee": [
    "Psychic",
    "Normal"
  ],
  "Indeedee-F": [
    "Psychic",
    "Normal"
  ],
  "Infernape": [
    "Fire",
    "Fighting"
  ],
  "Inkay": [
    "Dark",
    "Psychic"
  ],
  "Inteleon": [
    "Water"
  ],
  "Inteleon-Gmax": [
    "Water"
  ],
  "Iron Boulder": [
    "Rock",
    "Psychic"
  ],
  "Iron Bundle": [
    "Ice",
    "Water"
  ],
  "Iron Crown": [
    "Steel",
    "Psychic"
  ],
  "Iron Hands": [
    "Fighting",
    "Electric"
  ],
  "Iron Jugulis": [
    "Dark",
    "Flying"
  ],
  "Iron Leaves": [
    "Grass",
    "Psychic"
  ],
  "Iron Moth": [
    "Fire",
    "Poison"
  ],
  "Iron Thorns": [
    "Rock",
    "Electric"
  ],
  "Iron Treads": [
    "Ground",
    "Steel"
  ],
  "Iron Valiant": [
    "Fairy",
    "Fighting"
  ],
  "Ivysaur": [
    "Grass",
    "Poison"
  ],
  "Jangmo-o": [
    "Dragon"
  ],
  "Jellicent": [
    "Water",
    "Ghost"
  ],
  "Jigglypuff": [
    "Normal",
    "Fairy"
  ],
  "Jirachi": [
    "Steel",
    "Psychic"
  ],
  "Jolteon": [
    "Electric"
  ],
  "Joltik": [
    "Bug",
    "Electric"
  ],
  "Jumbao": [
    "Grass",
    "Fairy"
  ],
  "Jumpluff": [
    "Grass",
    "Flying"
  ],
  "Justyke": [
    "Steel",
    "Ground"
  ],
  "Jynx": [
    "Ice",
    "Psychic"
  ],
  "Kabuto": [
    "Rock",
    "Water"
  ],
  "Kabutops": [
    "Rock",
    "Water"
  ],
  "Kadabra": [
    "Psychic"
  ],
  "Kakuna": [
    "Bug",
    "Poison"
  ],
  "Kangaskhan": [
    "Normal"
  ],
  "Kangaskhan-Mega": [
    "Normal"
  ],
  "Karrablast": [
    "Bug"
  ],
  "Kartana": [
    "Grass",
    "Steel"
  ],
  "Kecleon": [
    "Normal"
  ],
  "Keldeo": [
    "Water",
    "Fighting"
  ],
  "Keldeo-Resolute": [
    "Water",
    "Fighting"
  ],
  "Kerfluffle": [
    "Fairy",
    "Fighting"
  ],
  "Kilowattrel": [
    "Electric",
    "Flying"
  ],
  "Kingambit": [
    "Dark",
    "Steel"
  ],
  "Kingdra": [
    "Water",
    "Dragon"
  ],
  "Kingler": [
    "Water"
  ],
  "Kingler-Gmax": [
    "Water"
  ],
  "Kirlia": [
    "Psychic",
    "Fairy"
  ],
  "Kitsunoh": [
    "Ghost",
    "Steel"
  ],
  "Klang": [
    "Steel"
  ],
  "Klawf": [
    "Rock"
  ],
  "Kleavor": [
    "Bug",
    "Rock"
  ],
  "Klefki": [
    "Steel",
    "Fairy"
  ],
  "Klink": [
    "Steel"
  ],
  "Klinklang": [
    "Steel"
  ],
  "Koffing": [
    "Poison"
  ],
  "Komala": [
    "Normal"
  ],
  "Kommo-o": [
    "Dragon",
    "Fighting"
  ],
  "Kommo-o-Totem": [
    "Dragon",
    "Fighting"
  ],
  "Koraidon": [
    "Fighting",
    "Dragon"
  ],
  "Krabby": [
    "Water"
  ],
  "Kricketot": [
    "Bug"
  ],
  "Kricketune": [
    "Bug"
  ],
  "Krilowatt": [
    "Electric",
    "Water"
  ],
  "Krokorok": [
    "Ground",
    "Dark"
  ],
  "Krookodile": [
    "Ground",
    "Dark"
  ],
  "Kubfu": [
    "Fighting"
  ],
  "Kyogre": [
    "Water"
  ],
  "Kyogre-Primal": [
    "Water"
  ],
  "Kyurem": [
    "Dragon",
    "Ice"
  ],
  "Kyurem-Black": [
    "Dragon",
    "Ice"
  ],
  "Kyurem-White": [
    "Dragon",
    "Ice"
  ],
  "Lairon": [
    "Steel",
    "Rock"
  ],
  "Lampent": [
    "Ghost",
    "Fire"
  ],
  "Landorus": [
    "Ground",
    "Flying"
  ],
  "Landorus-Therian": [
    "Ground",
    "Flying"
  ],
  "Lanturn": [
    "Water",
    "Electric"
  ],
  "Lapras": [
    "Water",
    "Ice"
  ],
  "Lapras-Gmax": [
    "Water",
    "Ice"
  ],
  "Larvesta": [
    "Bug",
    "Fire"
  ],
  "Larvitar": [
    "Rock",
    "Ground"
  ],
  "Latias": [
    "Dragon",
    "Psychic"
  ],
  "Latias-Mega": [
    "Dragon",
    "Psychic"
  ],
  "Latios": [
    "Dragon",
    "Psychic"
  ],
  "Latios-Mega": [
    "Dragon",
    "Psychic"
  ],
  "Leafeon": [
    "Grass"
  ],
  "Leavanny": [
    "Bug",
    "Grass"
  ],
  "Lechonk": [
    "Normal"
  ],
  "Ledian": [
    "Bug",
    "Flying"
  ],
  "Ledyba": [
    "Bug",
    "Flying"
  ],
  "Lickilicky": [
    "Normal"
  ],
  "Lickitung": [
    "Normal"
  ],
  "Liepard": [
    "Dark"
  ],
  "Lileep": [
    "Rock",
    "Grass"
  ],
  "Lilligant": [
    "Grass"
  ],
  "Lilligant-Hisui": [
    "Grass",
    "Fighting"
  ],
  "Lillipup": [
    "Normal"
  ],
  "Linoone": [
    "Normal"
  ],
  "Linoone-Galar": [
    "Dark",
    "Normal"
  ],
  "Litleo": [
    "Fire",
    "Normal"
  ],
  "Litten": [
    "Fire"
  ],
  "Litwick": [
    "Ghost",
    "Fire"
  ],
  "Lokix": [
    "Bug",
    "Dark"
  ],
  "Lombre": [
    "Water",
    "Grass"
  ],
  "Lopunny": [
    "Normal"
  ],
  "Lopunny-Mega": [
    "Normal",
    "Fighting"
  ],
  "Lotad": [
    "Water",
    "Grass"
  ],
  "Loudred": [
    "Normal"
  ],
  "Lucario": [
    "Fighting",
    "Steel"
  ],
  "Lucario-Mega": [
    "Fighting",
    "Steel"
  ],
  "Lucario-Mega-Z": [
    "Fighting",
    "Steel"
  ],
  "Ludicolo": [
    "Water",
    "Grass"
  ],
  "Lugia": [
    "Psychic",
    "Flying"
  ],
  "Lumineon": [
    "Water"
  ],
  "Lunala": [
    "Psychic",
    "Ghost"
  ],
  "Lunatone": [
    "Rock",
    "Psychic"
  ],
  "Lurantis": [
    "Grass"
  ],
  "Lurantis-Totem": [
    "Grass"
  ],
  "Luvdisc": [
    "Water"
  ],
  "Luxio": [
    "Electric"
  ],
  "Luxray": [
    "Electric"
  ],
  "Lycanroc": [
    "Rock"
  ],
  "Lycanroc-Dusk": [
    "Rock"
  ],
  "Lycanroc-Midnight": [
    "Rock"
  ],
  "Mabosstiff": [
    "Dark"
  ],
  "Machamp": [
    "Fighting"
  ],
  "Machamp-Gmax": [
    "Fighting"
  ],
  "Machoke": [
    "Fighting"
  ],
  "Machop": [
    "Fighting"
  ],
  "Magby": [
    "Fire"
  ],
  "Magcargo": [
    "Fire",
    "Rock"
  ],
  "Magearna": [
    "Steel",
    "Fairy"
  ],
  "Magearna-Mega": [
    "Steel",
    "Fairy"
  ],
  "Magearna-Original": [
    "Steel",
    "Fairy"
  ],
  "Magearna-Original-Mega": [
    "Steel",
    "Fairy"
  ],
  "Magikarp": [
    "Water"
  ],
  "Magmar": [
    "Fire"
  ],
  "Magmortar": [
    "Fire"
  ],
  "Magnemite": [
    "Electric",
    "Steel"
  ],
  "Magneton": [
    "Electric",
    "Steel"
  ],
  "Magnezone": [
    "Electric",
    "Steel"
  ],
  "Makuhita": [
    "Fighting"
  ],
  "Malaconda": [
    "Dark",
    "Grass"
  ],
  "Malamar": [
    "Dark",
    "Psychic"
  ],
  "Malamar-Mega": [
    "Dark",
    "Psychic"
  ],
  "Mamoswine": [
    "Ice",
    "Ground"
  ],
  "Manaphy": [
    "Water"
  ],
  "Mandibuzz": [
    "Dark",
    "Flying"
  ],
  "Manectric": [
    "Electric"
  ],
  "Manectric-Mega": [
    "Electric"
  ],
  "Mankey": [
    "Fighting"
  ],
  "Mantine": [
    "Water",
    "Flying"
  ],
  "Mantyke": [
    "Water",
    "Flying"
  ],
  "Maractus": [
    "Grass"
  ],
  "Mareanie": [
    "Poison",
    "Water"
  ],
  "Mareep": [
    "Electric"
  ],
  "Marill": [
    "Water",
    "Fairy"
  ],
  "Marowak": [
    "Ground"
  ],
  "Marowak-Alola": [
    "Fire",
    "Ghost"
  ],
  "Marowak-Alola-Totem": [
    "Fire",
    "Ghost"
  ],
  "Marshadow": [
    "Fighting",
    "Ghost"
  ],
  "Marshtomp": [
    "Water",
    "Ground"
  ],
  "Maschiff": [
    "Dark"
  ],
  "Masquerain": [
    "Bug",
    "Flying"
  ],
  "Maushold": [
    "Normal"
  ],
  "Maushold-Four": [
    "Normal"
  ],
  "Mawile": [
    "Steel",
    "Fairy"
  ],
  "Mawile-Mega": [
    "Steel",
    "Fairy"
  ],
  "Medicham": [
    "Fighting",
    "Psychic"
  ],
  "Medicham-Mega": [
    "Fighting",
    "Psychic"
  ],
  "Meditite": [
    "Fighting",
    "Psychic"
  ],
  "Meganium": [
    "Grass"
  ],
  "Meganium-Mega": [
    "Grass",
    "Fairy"
  ],
  "Melmetal": [
    "Steel"
  ],
  "Melmetal-Gmax": [
    "Steel"
  ],
  "Meloetta": [
    "Normal",
    "Psychic"
  ],
  "Meloetta-Pirouette": [
    "Normal",
    "Fighting"
  ],
  "Meltan": [
    "Steel"
  ],
  "Meowscarada": [
    "Grass",
    "Dark"
  ],
  "Meowstic": [
    "Psychic"
  ],
  "Meowstic-F": [
    "Psychic"
  ],
  "Meowstic-F-Mega": [
    "Psychic"
  ],
  "Meowstic-M-Mega": [
    "Psychic"
  ],
  "Meowth": [
    "Normal"
  ],
  "Meowth-Alola": [
    "Dark"
  ],
  "Meowth-Galar": [
    "Steel"
  ],
  "Meowth-Gmax": [
    "Normal"
  ],
  "Mesprit": [
    "Psychic"
  ],
  "Metagross": [
    "Steel",
    "Psychic"
  ],
  "Metagross-Mega": [
    "Steel",
    "Psychic"
  ],
  "Metang": [
    "Steel",
    "Psychic"
  ],
  "Metapod": [
    "Bug"
  ],
  "Mew": [
    "Psychic"
  ],
  "Mewtwo": [
    "Psychic"
  ],
  "Mewtwo-Mega-X": [
    "Psychic",
    "Fighting"
  ],
  "Mewtwo-Mega-Y": [
    "Psychic"
  ],
  "Miasmaw": [
    "Bug",
    "Dragon"
  ],
  "Miasmite": [
    "Bug",
    "Dragon"
  ],
  "Mienfoo": [
    "Fighting"
  ],
  "Mienshao": [
    "Fighting"
  ],
  "Mightyena": [
    "Dark"
  ],
  "Milcery": [
    "Fairy"
  ],
  "Milotic": [
    "Water"
  ],
  "Miltank": [
    "Normal"
  ],
  "Mime Jr.": [
    "Psychic",
    "Fairy"
  ],
  "Mimikyu": [
    "Ghost",
    "Fairy"
  ],
  "Mimikyu-Busted": [
    "Ghost",
    "Fairy"
  ],
  "Mimikyu-Busted-Totem": [
    "Ghost",
    "Fairy"
  ],
  "Mimikyu-Totem": [
    "Ghost",
    "Fairy"
  ],
  "Minccino": [
    "Normal"
  ],
  "Minior": [
    "Rock",
    "Flying"
  ],
  "Minior-Meteor": [
    "Rock",
    "Flying"
  ],
  "Minun": [
    "Electric"
  ],
  "Miraidon": [
    "Electric",
    "Dragon"
  ],
  "Misdreavus": [
    "Ghost"
  ],
  "Mismagius": [
    "Ghost"
  ],
  "MissingNo.": [
    "Bird",
    "Normal"
  ],
  "Mollux": [
    "Fire",
    "Poison"
  ],
  "Moltres": [
    "Fire",
    "Flying"
  ],
  "Moltres-Galar": [
    "Dark",
    "Flying"
  ],
  "Monferno": [
    "Fire",
    "Fighting"
  ],
  "Monohm": [
    "Electric"
  ],
  "Morelull": [
    "Grass",
    "Fairy"
  ],
  "Morgrem": [
    "Dark",
    "Fairy"
  ],
  "Morpeko": [
    "Electric",
    "Dark"
  ],
  "Morpeko-Hangry": [
    "Electric",
    "Dark"
  ],
  "Mothim": [
    "Bug",
    "Flying"
  ],
  "Mr. Mime": [
    "Psychic",
    "Fairy"
  ],
  "Mr. Mime-Galar": [
    "Ice",
    "Psychic"
  ],
  "Mr. Rime": [
    "Ice",
    "Psychic"
  ],
  "Mudbray": [
    "Ground"
  ],
  "Mudkip": [
    "Water"
  ],
  "Mudsdale": [
    "Ground"
  ],
  "Muk": [
    "Poison"
  ],
  "Muk-Alola": [
    "Poison",
    "Dark"
  ],
  "Mumbao": [
    "Grass",
    "Fairy"
  ],
  "Munchlax": [
    "Normal"
  ],
  "Munkidori": [
    "Poison",
    "Psychic"
  ],
  "Munna": [
    "Psychic"
  ],
  "Murkrow": [
    "Dark",
    "Flying"
  ],
  "Musharna": [
    "Psychic"
  ],
  "Nacli": [
    "Rock"
  ],
  "Naclstack": [
    "Rock"
  ],
  "Naganadel": [
    "Poison",
    "Dragon"
  ],
  "Natu": [
    "Psychic",
    "Flying"
  ],
  "Naviathan": [
    "Water",
    "Steel"
  ],
  "Necrozma": [
    "Psychic"
  ],
  "Necrozma-Dawn-Wings": [
    "Psychic",
    "Ghost"
  ],
  "Necrozma-Dusk-Mane": [
    "Psychic",
    "Steel"
  ],
  "Necrozma-Ultra": [
    "Psychic",
    "Dragon"
  ],
  "Necturine": [
    "Grass",
    "Ghost"
  ],
  "Necturna": [
    "Grass",
    "Ghost"
  ],
  "Nickit": [
    "Dark"
  ],
  "Nidoking": [
    "Poison",
    "Ground"
  ],
  "Nidoqueen": [
    "Poison",
    "Ground"
  ],
  "Nidoran-F": [
    "Poison"
  ],
  "Nidoran-M": [
    "Poison"
  ],
  "Nidorina": [
    "Poison"
  ],
  "Nidorino": [
    "Poison"
  ],
  "Nihilego": [
    "Rock",
    "Poison"
  ],
  "Nincada": [
    "Bug",
    "Ground"
  ],
  "Ninetales": [
    "Fire"
  ],
  "Ninetales-Alola": [
    "Ice",
    "Fairy"
  ],
  "Ninjask": [
    "Bug",
    "Flying"
  ],
  "Noctowl": [
    "Normal",
    "Flying"
  ],
  "Nohface": [
    "Ghost"
  ],
  "Noibat": [
    "Flying",
    "Dragon"
  ],
  "Noivern": [
    "Flying",
    "Dragon"
  ],
  "Nosepass": [
    "Rock"
  ],
  "Numel": [
    "Fire",
    "Ground"
  ],
  "Nuzleaf": [
    "Grass",
    "Dark"
  ],
  "Nymble": [
    "Bug"
  ],
  "Obliteryx": [
    "Dark",
    "Flying"
  ],
  "Obstagoon": [
    "Dark",
    "Normal"
  ],
  "Octillery": [
    "Water"
  ],
  "Oddish": [
    "Grass",
    "Poison"
  ],
  "Ogerpon": [
    "Grass"
  ],
  "Ogerpon-Cornerstone": [
    "Grass",
    "Rock"
  ],
  "Ogerpon-Cornerstone-Tera": [
    "Grass",
    "Rock"
  ],
  "Ogerpon-Hearthflame": [
    "Grass",
    "Fire"
  ],
  "Ogerpon-Hearthflame-Tera": [
    "Grass",
    "Fire"
  ],
  "Ogerpon-Teal-Tera": [
    "Grass"
  ],
  "Ogerpon-Wellspring": [
    "Grass",
    "Water"
  ],
  "Ogerpon-Wellspring-Tera": [
    "Grass",
    "Water"
  ],
  "Oinkologne": [
    "Normal"
  ],
  "Oinkologne-F": [
    "Normal"
  ],
  "Okidogi": [
    "Poison",
    "Fighting"
  ],
  "Omanyte": [
    "Rock",
    "Water"
  ],
  "Omastar": [
    "Rock",
    "Water"
  ],
  "Onix": [
    "Rock",
    "Ground"
  ],
  "Oranguru": [
    "Normal",
    "Psychic"
  ],
  "Orbeetle": [
    "Bug",
    "Psychic"
  ],
  "Orbeetle-Gmax": [
    "Bug",
    "Psychic"
  ],
  "Oricorio": [
    "Fire",
    "Flying"
  ],
  "Oricorio-Pa'u": [
    "Psychic",
    "Flying"
  ],
  "Oricorio-Pom-Pom": [
    "Electric",
    "Flying"
  ],
  "Oricorio-Sensu": [
    "Ghost",
    "Flying"
  ],
  "Orthworm": [
    "Steel"
  ],
  "Oshawott": [
    "Water"
  ],
  "Overqwil": [
    "Dark",
    "Poison"
  ],
  "Pachirisu": [
    "Electric"
  ],
  "Pajantom": [
    "Dragon",
    "Ghost"
  ],
  "Palafin": [
    "Water"
  ],
  "Palafin-Hero": [
    "Water"
  ],
  "Palkia": [
    "Water",
    "Dragon"
  ],
  "Palkia-Origin": [
    "Water",
    "Dragon"
  ],
  "Palossand": [
    "Ghost",
    "Ground"
  ],
  "Palpitoad": [
    "Water",
    "Ground"
  ],
  "Pancham": [
    "Fighting"
  ],
  "Pangoro": [
    "Fighting",
    "Dark"
  ],
  "Panpour": [
    "Water"
  ],
  "Pansage": [
    "Grass"
  ],
  "Pansear": [
    "Fire"
  ],
  "Paras": [
    "Bug",
    "Grass"
  ],
  "Parasect": [
    "Bug",
    "Grass"
  ],
  "Passimian": [
    "Fighting"
  ],
  "Patrat": [
    "Normal"
  ],
  "Pawmi": [
    "Electric"
  ],
  "Pawmo": [
    "Electric",
    "Fighting"
  ],
  "Pawmot": [
    "Electric",
    "Fighting"
  ],
  "Pawniard": [
    "Dark",
    "Steel"
  ],
  "Pecharunt": [
    "Poison",
    "Ghost"
  ],
  "Pelipper": [
    "Water",
    "Flying"
  ],
  "Perrserker": [
    "Steel"
  ],
  "Persian": [
    "Normal"
  ],
  "Persian-Alola": [
    "Dark"
  ],
  "Petilil": [
    "Grass"
  ],
  "Phanpy": [
    "Ground"
  ],
  "Phantump": [
    "Ghost",
    "Grass"
  ],
  "Pheromosa": [
    "Bug",
    "Fighting"
  ],
  "Phione": [
    "Water"
  ],
  "Pichu": [
    "Electric"
  ],
  "Pichu-Spiky-eared": [
    "Electric"
  ],
  "Pidgeot": [
    "Normal",
    "Flying"
  ],
  "Pidgeot-Mega": [
    "Normal",
    "Flying"
  ],
  "Pidgeotto": [
    "Normal",
    "Flying"
  ],
  "Pidgey": [
    "Normal",
    "Flying"
  ],
  "Pidove": [
    "Normal",
    "Flying"
  ],
  "Pignite": [
    "Fire",
    "Fighting"
  ],
  "Pikachu": [
    "Electric"
  ],
  "Pikachu-Alola": [
    "Electric"
  ],
  "Pikachu-Belle": [
    "Electric"
  ],
  "Pikachu-Cosplay": [
    "Electric"
  ],
  "Pikachu-Gmax": [
    "Electric"
  ],
  "Pikachu-Hoenn": [
    "Electric"
  ],
  "Pikachu-Kalos": [
    "Electric"
  ],
  "Pikachu-Libre": [
    "Electric"
  ],
  "Pikachu-Original": [
    "Electric"
  ],
  "Pikachu-Partner": [
    "Electric"
  ],
  "Pikachu-PhD": [
    "Electric"
  ],
  "Pikachu-Pop-Star": [
    "Electric"
  ],
  "Pikachu-Rock-Star": [
    "Electric"
  ],
  "Pikachu-Sinnoh": [
    "Electric"
  ],
  "Pikachu-Starter": [
    "Electric"
  ],
  "Pikachu-Unova": [
    "Electric"
  ],
  "Pikachu-World": [
    "Electric"
  ],
  "Pikipek": [
    "Normal",
    "Flying"
  ],
  "Piloswine": [
    "Ice",
    "Ground"
  ],
  "Pincurchin": [
    "Electric"
  ],
  "Pineco": [
    "Bug"
  ],
  "Pinsir": [
    "Bug"
  ],
  "Pinsir-Mega": [
    "Bug",
    "Flying"
  ],
  "Piplup": [
    "Water"
  ],
  "Plasmanta": [
    "Electric",
    "Poison"
  ],
  "Pluffle": [
    "Fairy"
  ],
  "Plusle": [
    "Electric"
  ],
  "Poipole": [
    "Poison"
  ],
  "Pokestar Black Belt": [
    "Fighting"
  ],
  "Pokestar Black Door": [
    "Grass"
  ],
  "Pokestar Brycen-Man": [
    "Dark",
    "Psychic"
  ],
  "Pokestar F-00": [
    "Steel",
    "Normal"
  ],
  "Pokestar F-002": [
    "Steel",
    "Normal"
  ],
  "Pokestar Giant": [
    "Normal"
  ],
  "Pokestar Humanoid": [
    "Normal"
  ],
  "Pokestar MT": [
    "Steel"
  ],
  "Pokestar MT2": [
    "Steel",
    "Electric"
  ],
  "Pokestar Monster": [
    "Dark"
  ],
  "Pokestar Smeargle": [
    "Normal"
  ],
  "Pokestar Spirit": [
    "Dark",
    "Ghost"
  ],
  "Pokestar Transport": [
    "Steel"
  ],
  "Pokestar UFO": [
    "Flying",
    "Electric"
  ],
  "Pokestar UFO-2": [
    "Psychic",
    "Electric"
  ],
  "Pokestar UFO-PropU2": [
    "Psychic",
    "Electric"
  ],
  "Pokestar White Door": [
    "Fire"
  ],
  "Politoed": [
    "Water"
  ],
  "Poliwag": [
    "Water"
  ],
  "Poliwhirl": [
    "Water"
  ],
  "Poliwrath": [
    "Water",
    "Fighting"
  ],
  "Poltchageist": [
    "Grass",
    "Ghost"
  ],
  "Poltchageist-Artisan": [
    "Grass",
    "Ghost"
  ],
  "Polteageist": [
    "Ghost"
  ],
  "Polteageist-Antique": [
    "Ghost"
  ],
  "Ponyta": [
    "Fire"
  ],
  "Ponyta-Galar": [
    "Psychic"
  ],
  "Poochyena": [
    "Dark"
  ],
  "Popplio": [
    "Water"
  ],
  "Porygon": [
    "Normal"
  ],
  "Porygon-Z": [
    "Normal"
  ],
  "Porygon2": [
    "Normal"
  ],
  "Primarina": [
    "Water",
    "Fairy"
  ],
  "Primeape": [
    "Fighting"
  ],
  "Prinplup": [
    "Water"
  ],
  "Privatyke": [
    "Water",
    "Fighting"
  ],
  "Probopass": [
    "Rock",
    "Steel"
  ],
  "Protowatt": [
    "Electric",
    "Water"
  ],
  "Psyduck": [
    "Water"
  ],
  "Pumpkaboo": [
    "Ghost",
    "Grass"
  ],
  "Pumpkaboo-Large": [
    "Ghost",
    "Grass"
  ],
  "Pumpkaboo-Small": [
    "Ghost",
    "Grass"
  ],
  "Pumpkaboo-Super": [
    "Ghost",
    "Grass"
  ],
  "Pupitar": [
    "Rock",
    "Ground"
  ],
  "Purrloin": [
    "Dark"
  ],
  "Purugly": [
    "Normal"
  ],
  "Pyroak": [
    "Fire",
    "Grass"
  ],
  "Pyroar": [
    "Fire",
    "Normal"
  ],
  "Pyroar-Mega": [
    "Fire",
    "Normal"
  ],
  "Pyukumuku": [
    "Water"
  ],
  "Quagsire": [
    "Water",
    "Ground"
  ],
  "Quaquaval": [
    "Water",
    "Fighting"
  ],
  "Quaxly": [
    "Water"
  ],
  "Quaxwell": [
    "Water"
  ],
  "Quilava": [
    "Fire"
  ],
  "Quilladin": [
    "Grass"
  ],
  "Qwilfish": [
    "Water",
    "Poison"
  ],
  "Qwilfish-Hisui": [
    "Dark",
    "Poison"
  ],
  "Raboot": [
    "Fire"
  ],
  "Rabsca": [
    "Bug",
    "Psychic"
  ],
  "Raging Bolt": [
    "Electric",
    "Dragon"
  ],
  "Raichu": [
    "Electric"
  ],
  "Raichu-Alola": [
    "Electric",
    "Psychic"
  ],
  "Raichu-Mega-X": [
    "Electric"
  ],
  "Raichu-Mega-Y": [
    "Electric"
  ],
  "Raikou": [
    "Electric"
  ],
  "Ralts": [
    "Psychic",
    "Fairy"
  ],
  "Ramnarok": [
    "Fire",
    "Steel"
  ],
  "Ramnarok-Radiant": [
    "Fire",
    "Ice"
  ],
  "Rampardos": [
    "Rock"
  ],
  "Rapidash": [
    "Fire"
  ],
  "Rapidash-Galar": [
    "Psychic",
    "Fairy"
  ],
  "Raticate": [
    "Normal"
  ],
  "Raticate-Alola": [
    "Dark",
    "Normal"
  ],
  "Raticate-Alola-Totem": [
    "Dark",
    "Normal"
  ],
  "Rattata": [
    "Normal"
  ],
  "Rattata-Alola": [
    "Dark",
    "Normal"
  ],
  "Rayquaza": [
    "Dragon",
    "Flying"
  ],
  "Rayquaza-Mega": [
    "Dragon",
    "Flying"
  ],
  "Rebble": [
    "Rock"
  ],
  "Regice": [
    "Ice"
  ],
  "Regidrago": [
    "Dragon"
  ],
  "Regieleki": [
    "Electric"
  ],
  "Regigigas": [
    "Normal"
  ],
  "Regirock": [
    "Rock"
  ],
  "Registeel": [
    "Steel"
  ],
  "Relicanth": [
    "Water",
    "Rock"
  ],
  "Rellor": [
    "Bug"
  ],
  "Remoraid": [
    "Water"
  ],
  "Reshiram": [
    "Dragon",
    "Fire"
  ],
  "Reuniclus": [
    "Psychic"
  ],
  "Revavroom": [
    "Steel",
    "Poison"
  ],
  "Revenankh": [
    "Ghost",
    "Fighting"
  ],
  "Rhydon": [
    "Ground",
    "Rock"
  ],
  "Rhyhorn": [
    "Ground",
    "Rock"
  ],
  "Rhyperior": [
    "Ground",
    "Rock"
  ],
  "Ribombee": [
    "Bug",
    "Fairy"
  ],
  "Ribombee-Totem": [
    "Bug",
    "Fairy"
  ],
  "Rillaboom": [
    "Grass"
  ],
  "Rillaboom-Gmax": [
    "Grass"
  ],
  "Riolu": [
    "Fighting"
  ],
  "Roaring Moon": [
    "Dragon",
    "Dark"
  ],
  "Rockruff": [
    "Rock"
  ],
  "Rockruff-Dusk": [
    "Rock"
  ],
  "Roggenrola": [
    "Rock"
  ],
  "Rolycoly": [
    "Rock"
  ],
  "Rookidee": [
    "Flying"
  ],
  "Roselia": [
    "Grass",
    "Poison"
  ],
  "Roserade": [
    "Grass",
    "Poison"
  ],
  "Rotom": [
    "Electric",
    "Ghost"
  ],
  "Rotom-Fan": [
    "Electric",
    "Flying"
  ],
  "Rotom-Frost": [
    "Electric",
    "Ice"
  ],
  "Rotom-Heat": [
    "Electric",
    "Fire"
  ],
  "Rotom-Mow": [
    "Electric",
    "Grass"
  ],
  "Rotom-Wash": [
    "Electric",
    "Water"
  ],
  "Rowlet": [
    "Grass",
    "Flying"
  ],
  "Rufflet": [
    "Normal",
    "Flying"
  ],
  "Runerigus": [
    "Ground",
    "Ghost"
  ],
  "Sableye": [
    "Dark",
    "Ghost"
  ],
  "Sableye-Mega": [
    "Dark",
    "Ghost"
  ],
  "Saharaja": [
    "Ground"
  ],
  "Saharascal": [
    "Ground"
  ],
  "Salamence": [
    "Dragon",
    "Flying"
  ],
  "Salamence-Mega": [
    "Dragon",
    "Flying"
  ],
  "Salandit": [
    "Poison",
    "Fire"
  ],
  "Salazzle": [
    "Poison",
    "Fire"
  ],
  "Salazzle-Totem": [
    "Poison",
    "Fire"
  ],
  "Samurott": [
    "Water"
  ],
  "Samurott-Hisui": [
    "Water",
    "Dark"
  ],
  "Sandaconda": [
    "Ground"
  ],
  "Sandaconda-Gmax": [
    "Ground"
  ],
  "Sandile": [
    "Ground",
    "Dark"
  ],
  "Sandshrew": [
    "Ground"
  ],
  "Sandshrew-Alola": [
    "Ice",
    "Steel"
  ],
  "Sandslash": [
    "Ground"
  ],
  "Sandslash-Alola": [
    "Ice",
    "Steel"
  ],
  "Sandy Shocks": [
    "Electric",
    "Ground"
  ],
  "Sandygast": [
    "Ghost",
    "Ground"
  ],
  "Sawk": [
    "Fighting"
  ],
  "Sawsbuck": [
    "Normal",
    "Grass"
  ],
  "Scatterbug": [
    "Bug"
  ],
  "Scattervein": [
    "Fairy"
  ],
  "Sceptile": [
    "Grass"
  ],
  "Sceptile-Mega": [
    "Grass",
    "Dragon"
  ],
  "Scizor": [
    "Bug",
    "Steel"
  ],
  "Scizor-Mega": [
    "Bug",
    "Steel"
  ],
  "Scolipede": [
    "Bug",
    "Poison"
  ],
  "Scolipede-Mega": [
    "Bug",
    "Poison"
  ],
  "Scorbunny": [
    "Fire"
  ],
  "Scovillain": [
    "Grass",
    "Fire"
  ],
  "Scovillain-Mega": [
    "Grass",
    "Fire"
  ],
  "Scrafty": [
    "Dark",
    "Fighting"
  ],
  "Scrafty-Mega": [
    "Dark",
    "Fighting"
  ],
  "Scraggy": [
    "Dark",
    "Fighting"
  ],
  "Scratchet": [
    "Normal",
    "Fighting"
  ],
  "Scream Tail": [
    "Fairy",
    "Psychic"
  ],
  "Scyther": [
    "Bug",
    "Flying"
  ],
  "Seadra": [
    "Water"
  ],
  "Seaking": [
    "Water"
  ],
  "Sealeo": [
    "Ice",
    "Water"
  ],
  "Seedot": [
    "Grass"
  ],
  "Seel": [
    "Water"
  ],
  "Seismitoad": [
    "Water",
    "Ground"
  ],
  "Sentret": [
    "Normal"
  ],
  "Serperior": [
    "Grass"
  ],
  "Servine": [
    "Grass"
  ],
  "Seviper": [
    "Poison"
  ],
  "Sewaddle": [
    "Bug",
    "Grass"
  ],
  "Sharpedo": [
    "Water",
    "Dark"
  ],
  "Sharpedo-Mega": [
    "Water",
    "Dark"
  ],
  "Shaymin": [
    "Grass"
  ],
  "Shaymin-Sky": [
    "Grass",
    "Flying"
  ],
  "Shedinja": [
    "Bug",
    "Ghost"
  ],
  "Shelgon": [
    "Dragon"
  ],
  "Shellder": [
    "Water"
  ],
  "Shellos": [
    "Water"
  ],
  "Shelmet": [
    "Bug"
  ],
  "Shieldon": [
    "Rock",
    "Steel"
  ],
  "Shiftry": [
    "Grass",
    "Dark"
  ],
  "Shiinotic": [
    "Grass",
    "Fairy"
  ],
  "Shinx": [
    "Electric"
  ],
  "Shox": [
    "Normal",
    "Electric"
  ],
  "Shroodle": [
    "Poison",
    "Normal"
  ],
  "Shroomish": [
    "Grass"
  ],
  "Shuckle": [
    "Bug",
    "Rock"
  ],
  "Shuppet": [
    "Ghost"
  ],
  "Sigilyph": [
    "Psychic",
    "Flying"
  ],
  "Silcoon": [
    "Bug"
  ],
  "Silicobra": [
    "Ground"
  ],
  "Silvally": [
    "Normal"
  ],
  "Silvally-Bug": [
    "Bug"
  ],
  "Silvally-Dark": [
    "Dark"
  ],
  "Silvally-Dragon": [
    "Dragon"
  ],
  "Silvally-Electric": [
    "Electric"
  ],
  "Silvally-Fairy": [
    "Fairy"
  ],
  "Silvally-Fighting": [
    "Fighting"
  ],
  "Silvally-Fire": [
    "Fire"
  ],
  "Silvally-Flying": [
    "Flying"
  ],
  "Silvally-Ghost": [
    "Ghost"
  ],
  "Silvally-Grass": [
    "Grass"
  ],
  "Silvally-Ground": [
    "Ground"
  ],
  "Silvally-Ice": [
    "Ice"
  ],
  "Silvally-Poison": [
    "Poison"
  ],
  "Silvally-Psychic": [
    "Psychic"
  ],
  "Silvally-Rock": [
    "Rock"
  ],
  "Silvally-Steel": [
    "Steel"
  ],
  "Silvally-Water": [
    "Water"
  ],
  "Simipour": [
    "Water"
  ],
  "Simisage": [
    "Grass"
  ],
  "Simisear": [
    "Fire"
  ],
  "Sinistcha": [
    "Grass",
    "Ghost"
  ],
  "Sinistcha-Masterpiece": [
    "Grass",
    "Ghost"
  ],
  "Sinistea": [
    "Ghost"
  ],
  "Sinistea-Antique": [
    "Ghost"
  ],
  "Sirfetch’d": [
    "Fighting"
  ],
  "Sizzlipede": [
    "Fire",
    "Bug"
  ],
  "Skarmory": [
    "Steel",
    "Flying"
  ],
  "Skarmory-Mega": [
    "Steel",
    "Flying"
  ],
  "Skeledirge": [
    "Fire",
    "Ghost"
  ],
  "Skiddo": [
    "Grass"
  ],
  "Skiploom": [
    "Grass",
    "Flying"
  ],
  "Skitty": [
    "Normal"
  ],
  "Skorupi": [
    "Poison",
    "Bug"
  ],
  "Skrelp": [
    "Poison",
    "Water"
  ],
  "Skuntank": [
    "Poison",
    "Dark"
  ],
  "Skwovet": [
    "Normal"
  ],
  "Slaking": [
    "Normal"
  ],
  "Slakoth": [
    "Normal"
  ],
  "Sliggoo": [
    "Dragon"
  ],
  "Sliggoo-Hisui": [
    "Steel",
    "Dragon"
  ],
  "Slither Wing": [
    "Bug",
    "Fighting"
  ],
  "Slowbro": [
    "Water",
    "Psychic"
  ],
  "Slowbro-Galar": [
    "Poison",
    "Psychic"
  ],
  "Slowbro-Mega": [
    "Water",
    "Psychic"
  ],
  "Slowking": [
    "Water",
    "Psychic"
  ],
  "Slowking-Galar": [
    "Poison",
    "Psychic"
  ],
  "Slowpoke": [
    "Water",
    "Psychic"
  ],
  "Slowpoke-Galar": [
    "Psychic"
  ],
  "Slugma": [
    "Fire"
  ],
  "Slurpuff": [
    "Fairy"
  ],
  "Smeargle": [
    "Normal"
  ],
  "Smogecko": [
    "Fire"
  ],
  "Smoguana": [
    "Fire",
    "Ground"
  ],
  "Smokomodo": [
    "Fire",
    "Ground"
  ],
  "Smoliv": [
    "Grass",
    "Normal"
  ],
  "Smoochum": [
    "Ice",
    "Psychic"
  ],
  "Snaelstrom": [
    "Water",
    "Bug"
  ],
  "Sneasel": [
    "Dark",
    "Ice"
  ],
  "Sneasel-Hisui": [
    "Fighting",
    "Poison"
  ],
  "Sneasler": [
    "Fighting",
    "Poison"
  ],
  "Snivy": [
    "Grass"
  ],
  "Snom": [
    "Ice",
    "Bug"
  ],
  "Snorlax": [
    "Normal"
  ],
  "Snorlax-Gmax": [
    "Normal"
  ],
  "Snorunt": [
    "Ice"
  ],
  "Snover": [
    "Grass",
    "Ice"
  ],
  "Snubbull": [
    "Fairy"
  ],
  "Snugglow": [
    "Electric",
    "Poison"
  ],
  "Sobble": [
    "Water"
  ],
  "Solgaleo": [
    "Psychic",
    "Steel"
  ],
  "Solosis": [
    "Psychic"
  ],
  "Solotl": [
    "Fire",
    "Dragon"
  ],
  "Solrock": [
    "Rock",
    "Psychic"
  ],
  "Spearow": [
    "Normal",
    "Flying"
  ],
  "Spectrier": [
    "Ghost"
  ],
  "Spewpa": [
    "Bug"
  ],
  "Spheal": [
    "Ice",
    "Water"
  ],
  "Spidops": [
    "Bug"
  ],
  "Spinarak": [
    "Bug",
    "Poison"
  ],
  "Spinda": [
    "Normal"
  ],
  "Spiritomb": [
    "Ghost",
    "Dark"
  ],
  "Spoink": [
    "Psychic"
  ],
  "Sprigatito": [
    "Grass"
  ],
  "Spritzee": [
    "Fairy"
  ],
  "Squawkabilly": [
    "Normal",
    "Flying"
  ],
  "Squawkabilly-Blue": [
    "Normal",
    "Flying"
  ],
  "Squawkabilly-White": [
    "Normal",
    "Flying"
  ],
  "Squawkabilly-Yellow": [
    "Normal",
    "Flying"
  ],
  "Squirtle": [
    "Water"
  ],
  "Stakataka": [
    "Rock",
    "Steel"
  ],
  "Stantler": [
    "Normal"
  ],
  "Staraptor": [
    "Normal",
    "Flying"
  ],
  "Staraptor-Mega": [
    "Fighting",
    "Flying"
  ],
  "Staravia": [
    "Normal",
    "Flying"
  ],
  "Starly": [
    "Normal",
    "Flying"
  ],
  "Starmie": [
    "Water",
    "Psychic"
  ],
  "Starmie-Mega": [
    "Water",
    "Psychic"
  ],
  "Staryu": [
    "Water"
  ],
  "Steelix": [
    "Steel",
    "Ground"
  ],
  "Steelix-Mega": [
    "Steel",
    "Ground"
  ],
  "Steenee": [
    "Grass"
  ],
  "Stonjourner": [
    "Rock"
  ],
  "Stoutland": [
    "Normal"
  ],
  "Stratagem": [
    "Rock"
  ],
  "Stufful": [
    "Normal",
    "Fighting"
  ],
  "Stunfisk": [
    "Ground",
    "Electric"
  ],
  "Stunfisk-Galar": [
    "Ground",
    "Steel"
  ],
  "Stunky": [
    "Poison",
    "Dark"
  ],
  "Sudowoodo": [
    "Rock"
  ],
  "Suicune": [
    "Water"
  ],
  "Sunflora": [
    "Grass"
  ],
  "Sunkern": [
    "Grass"
  ],
  "Surskit": [
    "Bug",
    "Water"
  ],
  "Swablu": [
    "Normal",
    "Flying"
  ],
  "Swadloon": [
    "Bug",
    "Grass"
  ],
  "Swalot": [
    "Poison"
  ],
  "Swampert": [
    "Water",
    "Ground"
  ],
  "Swampert-Mega": [
    "Water",
    "Ground"
  ],
  "Swanna": [
    "Water",
    "Flying"
  ],
  "Swellow": [
    "Normal",
    "Flying"
  ],
  "Swinub": [
    "Ice",
    "Ground"
  ],
  "Swirlix": [
    "Fairy"
  ],
  "Swirlpool": [
    "Water"
  ],
  "Swoobat": [
    "Psychic",
    "Flying"
  ],
  "Syclant": [
    "Ice",
    "Bug"
  ],
  "Syclar": [
    "Ice",
    "Bug"
  ],
  "Sylveon": [
    "Fairy"
  ],
  "Tactite": [
    "Rock"
  ],
  "Tadbulb": [
    "Electric"
  ],
  "Taillow": [
    "Normal",
    "Flying"
  ],
  "Talonflame": [
    "Fire",
    "Flying"
  ],
  "Tandemaus": [
    "Normal"
  ],
  "Tangela": [
    "Grass"
  ],
  "Tangrowth": [
    "Grass"
  ],
  "Tapu Bulu": [
    "Grass",
    "Fairy"
  ],
  "Tapu Fini": [
    "Water",
    "Fairy"
  ],
  "Tapu Koko": [
    "Electric",
    "Fairy"
  ],
  "Tapu Lele": [
    "Psychic",
    "Fairy"
  ],
  "Tarountula": [
    "Bug"
  ],
  "Tatsugiri": [
    "Dragon",
    "Water"
  ],
  "Tatsugiri-Curly-Mega": [
    "Dragon",
    "Water"
  ],
  "Tatsugiri-Droopy": [
    "Dragon",
    "Water"
  ],
  "Tatsugiri-Droopy-Mega": [
    "Dragon",
    "Water"
  ],
  "Tatsugiri-Stretchy": [
    "Dragon",
    "Water"
  ],
  "Tatsugiri-Stretchy-Mega": [
    "Dragon",
    "Water"
  ],
  "Tauros": [
    "Normal"
  ],
  "Tauros-Paldea-Aqua": [
    "Fighting",
    "Water"
  ],
  "Tauros-Paldea-Blaze": [
    "Fighting",
    "Fire"
  ],
  "Tauros-Paldea-Combat": [
    "Fighting"
  ],
  "Teddiursa": [
    "Normal"
  ],
  "Tentacool": [
    "Water",
    "Poison"
  ],
  "Tentacruel": [
    "Water",
    "Poison"
  ],
  "Tepig": [
    "Fire"
  ],
  "Terapagos": [
    "Normal"
  ],
  "Terapagos-Stellar": [
    "Normal"
  ],
  "Terapagos-Terastal": [
    "Normal"
  ],
  "Terrakion": [
    "Rock",
    "Fighting"
  ],
  "Thievul": [
    "Dark"
  ],
  "Throh": [
    "Fighting"
  ],
  "Thundurus": [
    "Electric",
    "Flying"
  ],
  "Thundurus-Therian": [
    "Electric",
    "Flying"
  ],
  "Thwackey": [
    "Grass"
  ],
  "Timburr": [
    "Fighting"
  ],
  "Ting-Lu": [
    "Dark",
    "Ground"
  ],
  "Tinkatink": [
    "Fairy",
    "Steel"
  ],
  "Tinkaton": [
    "Fairy",
    "Steel"
  ],
  "Tinkatuff": [
    "Fairy",
    "Steel"
  ],
  "Tirtouga": [
    "Water",
    "Rock"
  ],
  "Toedscool": [
    "Ground",
    "Grass"
  ],
  "Toedscruel": [
    "Ground",
    "Grass"
  ],
  "Togedemaru": [
    "Electric",
    "Steel"
  ],
  "Togedemaru-Totem": [
    "Electric",
    "Steel"
  ],
  "Togekiss": [
    "Fairy",
    "Flying"
  ],
  "Togepi": [
    "Fairy"
  ],
  "Togetic": [
    "Fairy",
    "Flying"
  ],
  "Tomohawk": [
    "Flying",
    "Fighting"
  ],
  "Torchic": [
    "Fire"
  ],
  "Torkoal": [
    "Fire"
  ],
  "Tornadus": [
    "Flying"
  ],
  "Tornadus-Therian": [
    "Flying"
  ],
  "Torracat": [
    "Fire"
  ],
  "Torterra": [
    "Grass",
    "Ground"
  ],
  "Totodile": [
    "Water"
  ],
  "Toucannon": [
    "Normal",
    "Flying"
  ],
  "Toxapex": [
    "Poison",
    "Water"
  ],
  "Toxel": [
    "Electric",
    "Poison"
  ],
  "Toxicroak": [
    "Poison",
    "Fighting"
  ],
  "Toxtricity": [
    "Electric",
    "Poison"
  ],
  "Toxtricity-Gmax": [
    "Electric",
    "Poison"
  ],
  "Toxtricity-Low-Key": [
    "Electric",
    "Poison"
  ],
  "Toxtricity-Low-Key-Gmax": [
    "Electric",
    "Poison"
  ],
  "Tranquill": [
    "Normal",
    "Flying"
  ],
  "Trapinch": [
    "Ground"
  ],
  "Treecko": [
    "Grass"
  ],
  "Trevenant": [
    "Ghost",
    "Grass"
  ],
  "Tropius": [
    "Grass",
    "Flying"
  ],
  "Trubbish": [
    "Poison"
  ],
  "Trumbeak": [
    "Normal",
    "Flying"
  ],
  "Tsareena": [
    "Grass"
  ],
  "Turtonator": [
    "Fire",
    "Dragon"
  ],
  "Turtwig": [
    "Grass"
  ],
  "Tympole": [
    "Water"
  ],
  "Tynamo": [
    "Electric"
  ],
  "Type: Null": [
    "Normal"
  ],
  "Typhlosion": [
    "Fire"
  ],
  "Typhlosion-Hisui": [
    "Fire",
    "Ghost"
  ],
  "Tyranitar": [
    "Rock",
    "Dark"
  ],
  "Tyranitar-Mega": [
    "Rock",
    "Dark"
  ],
  "Tyrantrum": [
    "Rock",
    "Dragon"
  ],
  "Tyrogue": [
    "Fighting"
  ],
  "Tyrunt": [
    "Rock",
    "Dragon"
  ],
  "Umbreon": [
    "Dark"
  ],
  "Unfezant": [
    "Normal",
    "Flying"
  ],
  "Unown": [
    "Psychic"
  ],
  "Ursaluna": [
    "Ground",
    "Normal"
  ],
  "Ursaluna-Bloodmoon": [
    "Ground",
    "Normal"
  ],
  "Ursaring": [
    "Normal"
  ],
  "Urshifu": [
    "Fighting",
    "Dark"
  ],
  "Urshifu-Gmax": [
    "Fighting",
    "Dark"
  ],
  "Urshifu-Rapid-Strike": [
    "Fighting",
    "Water"
  ],
  "Urshifu-Rapid-Strike-Gmax": [
    "Fighting",
    "Water"
  ],
  "Uxie": [
    "Psychic"
  ],
  "Vanillish": [
    "Ice"
  ],
  "Vanillite": [
    "Ice"
  ],
  "Vanilluxe": [
    "Ice"
  ],
  "Vaporeon": [
    "Water"
  ],
  "Varoom": [
    "Steel",
    "Poison"
  ],
  "Veluza": [
    "Water",
    "Psychic"
  ],
  "Venipede": [
    "Bug",
    "Poison"
  ],
  "Venomicon": [
    "Poison",
    "Flying"
  ],
  "Venomicon-Epilogue": [
    "Poison",
    "Flying"
  ],
  "Venomoth": [
    "Bug",
    "Poison"
  ],
  "Venonat": [
    "Bug",
    "Poison"
  ],
  "Venusaur": [
    "Grass",
    "Poison"
  ],
  "Venusaur-Gmax": [
    "Grass",
    "Poison"
  ],
  "Venusaur-Mega": [
    "Grass",
    "Poison"
  ],
  "Vespiquen": [
    "Bug",
    "Flying"
  ],
  "Vibrava": [
    "Ground",
    "Dragon"
  ],
  "Victini": [
    "Psychic",
    "Fire"
  ],
  "Victreebel": [
    "Grass",
    "Poison"
  ],
  "Victreebel-Mega": [
    "Grass",
    "Poison"
  ],
  "Vigoroth": [
    "Normal"
  ],
  "Vikavolt": [
    "Bug",
    "Electric"
  ],
  "Vikavolt-Totem": [
    "Bug",
    "Electric"
  ],
  "Vileplume": [
    "Grass",
    "Poison"
  ],
  "Virizion": [
    "Grass",
    "Fighting"
  ],
  "Vivillon": [
    "Bug",
    "Flying"
  ],
  "Vivillon-Fancy": [
    "Bug",
    "Flying"
  ],
  "Vivillon-Pokeball": [
    "Bug",
    "Flying"
  ],
  "Volbeat": [
    "Bug"
  ],
  "Volcanion": [
    "Fire",
    "Water"
  ],
  "Volcarona": [
    "Bug",
    "Fire"
  ],
  "Volkraken": [
    "Water",
    "Fire"
  ],
  "Volkritter": [
    "Water",
    "Fire"
  ],
  "Voltorb": [
    "Electric"
  ],
  "Voltorb-Hisui": [
    "Electric",
    "Grass"
  ],
  "Voodoll": [
    "Normal",
    "Dark"
  ],
  "Voodoom": [
    "Fighting",
    "Dark"
  ],
  "Vullaby": [
    "Dark",
    "Flying"
  ],
  "Vulpix": [
    "Fire"
  ],
  "Vulpix-Alola": [
    "Ice"
  ],
  "Wailmer": [
    "Water"
  ],
  "Wailord": [
    "Water"
  ],
  "Walking Wake": [
    "Water",
    "Dragon"
  ],
  "Walrein": [
    "Ice",
    "Water"
  ],
  "Wartortle": [
    "Water"
  ],
  "Watchog": [
    "Normal"
  ],
  "Wattrel": [
    "Electric",
    "Flying"
  ],
  "Weavile": [
    "Dark",
    "Ice"
  ],
  "Weedle": [
    "Bug",
    "Poison"
  ],
  "Weepinbell": [
    "Grass",
    "Poison"
  ],
  "Weezing": [
    "Poison"
  ],
  "Weezing-Galar": [
    "Poison",
    "Fairy"
  ],
  "Whimsicott": [
    "Grass",
    "Fairy"
  ],
  "Whirlipede": [
    "Bug",
    "Poison"
  ],
  "Whiscash": [
    "Water",
    "Ground"
  ],
  "Whismur": [
    "Normal"
  ],
  "Wigglytuff": [
    "Normal",
    "Fairy"
  ],
  "Wiglett": [
    "Water"
  ],
  "Wimpod": [
    "Bug",
    "Water"
  ],
  "Wingull": [
    "Water",
    "Flying"
  ],
  "Wishiwashi": [
    "Water"
  ],
  "Wishiwashi-School": [
    "Water"
  ],
  "Wo-Chien": [
    "Dark",
    "Grass"
  ],
  "Wobbuffet": [
    "Psychic"
  ],
  "Woobat": [
    "Psychic",
    "Flying"
  ],
  "Wooloo": [
    "Normal"
  ],
  "Wooper": [
    "Water",
    "Ground"
  ],
  "Wooper-Paldea": [
    "Poison",
    "Ground"
  ],
  "Wormadam": [
    "Bug",
    "Grass"
  ],
  "Wormadam-Sandy": [
    "Bug",
    "Ground"
  ],
  "Wormadam-Trash": [
    "Bug",
    "Steel"
  ],
  "Wugtrio": [
    "Water"
  ],
  "Wurmple": [
    "Bug"
  ],
  "Wynaut": [
    "Psychic"
  ],
  "Wyrdeer": [
    "Normal",
    "Psychic"
  ],
  "Xatu": [
    "Psychic",
    "Flying"
  ],
  "Xerneas": [
    "Fairy"
  ],
  "Xerneas-Neutral": [
    "Fairy"
  ],
  "Xurkitree": [
    "Electric"
  ],
  "Yamask": [
    "Ghost"
  ],
  "Yamask-Galar": [
    "Ground",
    "Ghost"
  ],
  "Yamper": [
    "Electric"
  ],
  "Yanma": [
    "Bug",
    "Flying"
  ],
  "Yanmega": [
    "Bug",
    "Flying"
  ],
  "Yungoos": [
    "Normal"
  ],
  "Yveltal": [
    "Dark",
    "Flying"
  ],
  "Zacian": [
    "Fairy"
  ],
  "Zacian-Crowned": [
    "Fairy",
    "Steel"
  ],
  "Zamazenta": [
    "Fighting"
  ],
  "Zamazenta-Crowned": [
    "Fighting",
    "Steel"
  ],
  "Zangoose": [
    "Normal"
  ],
  "Zapdos": [
    "Electric",
    "Flying"
  ],
  "Zapdos-Galar": [
    "Fighting",
    "Flying"
  ],
  "Zarude": [
    "Dark",
    "Grass"
  ],
  "Zarude-Dada": [
    "Dark",
    "Grass"
  ],
  "Zebstrika": [
    "Electric"
  ],
  "Zekrom": [
    "Dragon",
    "Electric"
  ],
  "Zeraora": [
    "Electric"
  ],
  "Zeraora-Mega": [
    "Electric"
  ],
  "Zigzagoon": [
    "Normal"
  ],
  "Zigzagoon-Galar": [
    "Dark",
    "Normal"
  ],
  "Zoroark": [
    "Dark"
  ],
  "Zoroark-Hisui": [
    "Normal",
    "Ghost"
  ],
  "Zorua": [
    "Dark"
  ],
  "Zorua-Hisui": [
    "Normal",
    "Ghost"
  ],
  "Zubat": [
    "Poison",
    "Flying"
  ],
  "Zweilous": [
    "Dark",
    "Dragon"
  ],
  "Zygarde": [
    "Dragon",
    "Ground"
  ],
  "Zygarde-10%": [
    "Dragon",
    "Ground"
  ],
  "Zygarde-Complete": [
    "Dragon",
    "Ground"
  ],
  "Zygarde-Mega": [
    "Dragon",
    "Ground"
  ]
};
