// AUTO-GENERATED by scripts/vendor-data.mjs — do not edit by hand.
export const speciesAbilities: Record<string, string[]> = {
  "Ababo": [
    "Own Tempo",
    "Pixilate",
    "Rattled"
  ],
  "Abomasnow": [
    "Snow Warning",
    "Soundproof"
  ],
  "Abomasnow-Mega": [
    "Snow Warning"
  ],
  "Abra": [
    "Inner Focus",
    "Magic Guard",
    "Synchronize"
  ],
  "Absol": [
    "Justified",
    "Pressure",
    "Super Luck"
  ],
  "Absol-Mega": [
    "Magic Bounce"
  ],
  "Absol-Mega-Z": [
    "Magic Bounce"
  ],
  "Accelgor": [
    "Hydration",
    "Sticky Hold",
    "Unburden"
  ],
  "Aegislash": [
    "Stance Change"
  ],
  "Aegislash-Blade": [
    "Stance Change"
  ],
  "Aerodactyl": [
    "Pressure",
    "Rock Head",
    "Unnerve"
  ],
  "Aerodactyl-Mega": [
    "Tough Claws"
  ],
  "Aggron": [
    "Heavy Metal",
    "Rock Head",
    "Sturdy"
  ],
  "Aggron-Mega": [
    "Filter"
  ],
  "Aipom": [
    "Pickup",
    "Run Away",
    "Skill Link"
  ],
  "Alakazam": [
    "Inner Focus",
    "Magic Guard",
    "Synchronize"
  ],
  "Alakazam-Mega": [
    "Trace"
  ],
  "Alcremie": [
    "Aroma Veil",
    "Sweet Veil"
  ],
  "Alcremie-Gmax": [
    "Aroma Veil",
    "Sweet Veil"
  ],
  "Alomomola": [
    "Healer",
    "Hydration",
    "Regenerator"
  ],
  "Altaria": [
    "Cloud Nine",
    "Natural Cure"
  ],
  "Altaria-Mega": [
    "Pixilate"
  ],
  "Amaura": [
    "Refrigerate",
    "Snow Warning"
  ],
  "Ambipom": [
    "Pickup",
    "Skill Link",
    "Technician"
  ],
  "Amoonguss": [
    "Effect Spore",
    "Regenerator"
  ],
  "Ampharos": [
    "Plus",
    "Static"
  ],
  "Ampharos-Mega": [
    "Mold Breaker"
  ],
  "Annihilape": [
    "Defiant",
    "Inner Focus",
    "Vital Spirit"
  ],
  "Anorith": [
    "Battle Armor",
    "Swift Swim"
  ],
  "Appletun": [
    "Gluttony",
    "Ripen",
    "Thick Fat"
  ],
  "Appletun-Gmax": [
    "Gluttony",
    "Ripen",
    "Thick Fat"
  ],
  "Applin": [
    "Bulletproof",
    "Gluttony",
    "Ripen"
  ],
  "Araquanid": [
    "Water Absorb",
    "Water Bubble"
  ],
  "Araquanid-Totem": [
    "Water Bubble"
  ],
  "Arbok": [
    "Intimidate",
    "Shed Skin",
    "Unnerve"
  ],
  "Arboliva": [
    "Harvest",
    "Seed Sower"
  ],
  "Arcanine": [
    "Flash Fire",
    "Intimidate",
    "Justified"
  ],
  "Arcanine-Hisui": [
    "Flash Fire",
    "Intimidate",
    "Rock Head"
  ],
  "Arceus": [
    "Multitype"
  ],
  "Arceus-Bug": [
    "Multitype"
  ],
  "Arceus-Dark": [
    "Multitype"
  ],
  "Arceus-Dragon": [
    "Multitype"
  ],
  "Arceus-Electric": [
    "Multitype"
  ],
  "Arceus-Fairy": [
    "Multitype"
  ],
  "Arceus-Fighting": [
    "Multitype"
  ],
  "Arceus-Fire": [
    "Multitype"
  ],
  "Arceus-Flying": [
    "Multitype"
  ],
  "Arceus-Ghost": [
    "Multitype"
  ],
  "Arceus-Grass": [
    "Multitype"
  ],
  "Arceus-Ground": [
    "Multitype"
  ],
  "Arceus-Ice": [
    "Multitype"
  ],
  "Arceus-Poison": [
    "Multitype"
  ],
  "Arceus-Psychic": [
    "Multitype"
  ],
  "Arceus-Rock": [
    "Multitype"
  ],
  "Arceus-Steel": [
    "Multitype"
  ],
  "Arceus-Water": [
    "Multitype"
  ],
  "Archaludon": [
    "Stalwart",
    "Stamina",
    "Sturdy"
  ],
  "Archen": [
    "Defeatist"
  ],
  "Archeops": [
    "Defeatist"
  ],
  "Arctibax": [
    "Ice Body",
    "Thermal Exchange"
  ],
  "Arctovish": [
    "Ice Body",
    "Slush Rush",
    "Water Absorb"
  ],
  "Arctozolt": [
    "Slush Rush",
    "Static",
    "Volt Absorb"
  ],
  "Argalis": [
    "Compound Eyes",
    "Overcoat",
    "Shed Skin"
  ],
  "Arghonaut": [
    "Technician",
    "Unaware"
  ],
  "Ariados": [
    "Insomnia",
    "Sniper",
    "Swarm"
  ],
  "Armaldo": [
    "Battle Armor",
    "Swift Swim"
  ],
  "Armarouge": [
    "Flash Fire",
    "Weak Armor"
  ],
  "Aromatisse": [
    "Aroma Veil",
    "Healer"
  ],
  "Aron": [
    "Heavy Metal",
    "Rock Head",
    "Sturdy"
  ],
  "Arrokuda": [
    "Propeller Tail",
    "Swift Swim"
  ],
  "Articuno": [
    "Pressure",
    "Snow Cloak"
  ],
  "Articuno-Galar": [
    "Competitive"
  ],
  "Astrolotl": [
    "Magician",
    "Regenerator",
    "Vital Spirit"
  ],
  "Audino": [
    "Healer",
    "Klutz",
    "Regenerator"
  ],
  "Audino-Mega": [
    "Healer"
  ],
  "Aurorus": [
    "Refrigerate",
    "Snow Warning"
  ],
  "Aurumoth": [
    "Light Metal",
    "No Guard",
    "Weak Armor"
  ],
  "Avalugg": [
    "Ice Body",
    "Own Tempo",
    "Sturdy"
  ],
  "Avalugg-Hisui": [
    "Ice Body",
    "Strong Jaw",
    "Sturdy"
  ],
  "Axew": [
    "Mold Breaker",
    "Rivalry",
    "Unnerve"
  ],
  "Azelf": [
    "Levitate"
  ],
  "Azumarill": [
    "Huge Power",
    "Sap Sipper",
    "Thick Fat"
  ],
  "Azurill": [
    "Huge Power",
    "Sap Sipper",
    "Thick Fat"
  ],
  "Bagon": [
    "Rock Head",
    "Sheer Force"
  ],
  "Baltoy": [
    "Levitate"
  ],
  "Banette": [
    "Cursed Body",
    "Frisk",
    "Insomnia"
  ],
  "Banette-Mega": [
    "Prankster"
  ],
  "Barbaracle": [
    "Pickpocket",
    "Sniper",
    "Tough Claws"
  ],
  "Barbaracle-Mega": [
    "Tough Claws"
  ],
  "Barboach": [
    "Anticipation",
    "Hydration",
    "Oblivious"
  ],
  "Barraskewda": [
    "Propeller Tail",
    "Swift Swim"
  ],
  "Basculegion": [
    "Adaptability",
    "Mold Breaker",
    "Swift Swim"
  ],
  "Basculegion-F": [
    "Adaptability",
    "Mold Breaker",
    "Swift Swim"
  ],
  "Basculin": [
    "Adaptability",
    "Mold Breaker",
    "Reckless"
  ],
  "Basculin-Blue-Striped": [
    "Adaptability",
    "Mold Breaker",
    "Rock Head"
  ],
  "Basculin-White-Striped": [
    "Adaptability",
    "Mold Breaker",
    "Rattled"
  ],
  "Bastiodon": [
    "Soundproof",
    "Sturdy"
  ],
  "Baxcalibur": [
    "Ice Body",
    "Thermal Exchange"
  ],
  "Baxcalibur-Mega": [
    "Ice Body",
    "Thermal Exchange"
  ],
  "Bayleef": [
    "Leaf Guard",
    "Overgrow"
  ],
  "Beartic": [
    "Slush Rush",
    "Snow Cloak",
    "Swift Swim"
  ],
  "Beautifly": [
    "Rivalry",
    "Swarm"
  ],
  "Beedrill": [
    "Sniper",
    "Swarm"
  ],
  "Beedrill-Mega": [
    "Adaptability"
  ],
  "Beheeyem": [
    "Analytic",
    "Synchronize",
    "Telepathy"
  ],
  "Beldum": [
    "Clear Body",
    "Light Metal"
  ],
  "Bellibolt": [
    "Damp",
    "Electromorphosis",
    "Static"
  ],
  "Bellossom": [
    "Chlorophyll",
    "Healer"
  ],
  "Bellsprout": [
    "Chlorophyll",
    "Gluttony"
  ],
  "Bergmite": [
    "Ice Body",
    "Own Tempo",
    "Sturdy"
  ],
  "Bewear": [
    "Fluffy",
    "Klutz",
    "Unnerve"
  ],
  "Bibarel": [
    "Moody",
    "Simple",
    "Unaware"
  ],
  "Bidoof": [
    "Moody",
    "Simple",
    "Unaware"
  ],
  "Binacle": [
    "Pickpocket",
    "Sniper",
    "Tough Claws"
  ],
  "Bisharp": [
    "Defiant",
    "Inner Focus",
    "Pressure"
  ],
  "Blacephalon": [
    "Beast Boost"
  ],
  "Blastoise": [
    "Rain Dish",
    "Torrent"
  ],
  "Blastoise-Gmax": [
    "Rain Dish",
    "Torrent"
  ],
  "Blastoise-Mega": [
    "Mega Launcher"
  ],
  "Blaziken": [
    "Blaze",
    "Speed Boost"
  ],
  "Blaziken-Mega": [
    "Speed Boost"
  ],
  "Blipbug": [
    "Compound Eyes",
    "Swarm",
    "Telepathy"
  ],
  "Blissey": [
    "Healer",
    "Natural Cure",
    "Serene Grace"
  ],
  "Blitzle": [
    "Lightning Rod",
    "Motor Drive",
    "Sap Sipper"
  ],
  "Boldore": [
    "Sand Force",
    "Sturdy",
    "Weak Armor"
  ],
  "Boltund": [
    "Competitive",
    "Strong Jaw"
  ],
  "Bombirdier": [
    "Big Pecks",
    "Keen Eye",
    "Rocky Payload"
  ],
  "Bonsly": [
    "Rattled",
    "Rock Head",
    "Sturdy"
  ],
  "Bouffalant": [
    "Reckless",
    "Sap Sipper",
    "Soundproof"
  ],
  "Bounsweet": [
    "Leaf Guard",
    "Oblivious",
    "Sweet Veil"
  ],
  "Braixen": [
    "Blaze",
    "Magician"
  ],
  "Brambleghast": [
    "Infiltrator",
    "Wind Rider"
  ],
  "Bramblin": [
    "Infiltrator",
    "Wind Rider"
  ],
  "Brattler": [
    "Harvest",
    "Infiltrator",
    "Rattled"
  ],
  "Braviary": [
    "Defiant",
    "Keen Eye",
    "Sheer Force"
  ],
  "Braviary-Hisui": [
    "Keen Eye",
    "Sheer Force",
    "Tinted Lens"
  ],
  "Breezi": [
    "Frisk",
    "Own Tempo",
    "Unburden"
  ],
  "Breloom": [
    "Effect Spore",
    "Poison Heal",
    "Technician"
  ],
  "Brionne": [
    "Liquid Voice",
    "Torrent"
  ],
  "Bronzong": [
    "Heatproof",
    "Heavy Metal",
    "Levitate"
  ],
  "Bronzor": [
    "Heatproof",
    "Heavy Metal",
    "Levitate"
  ],
  "Brute Bonnet": [
    "Protosynthesis"
  ],
  "Bruxish": [
    "Dazzling",
    "Strong Jaw",
    "Wonder Skin"
  ],
  "Budew": [
    "Leaf Guard",
    "Natural Cure",
    "Poison Point"
  ],
  "Buizel": [
    "Swift Swim",
    "Water Veil"
  ],
  "Bulbasaur": [
    "Chlorophyll",
    "Overgrow"
  ],
  "Buneary": [
    "Klutz",
    "Limber",
    "Run Away"
  ],
  "Bunnelby": [
    "Cheek Pouch",
    "Huge Power",
    "Pickup"
  ],
  "Burmy": [
    "Overcoat",
    "Shed Skin"
  ],
  "Butterfree": [
    "Compound Eyes",
    "Tinted Lens"
  ],
  "Butterfree-Gmax": [
    "Compound Eyes",
    "Tinted Lens"
  ],
  "Buzzwole": [
    "Beast Boost"
  ],
  "Cacnea": [
    "Sand Veil",
    "Water Absorb"
  ],
  "Cacturne": [
    "Sand Veil",
    "Water Absorb"
  ],
  "Caimanoe": [
    "Heatproof",
    "Light Metal",
    "Water Veil"
  ],
  "Calyrex": [
    "Unnerve"
  ],
  "Calyrex-Ice": [
    "As One (Glastrier)"
  ],
  "Calyrex-Shadow": [
    "As One (Spectrier)"
  ],
  "Camerupt": [
    "Anger Point",
    "Magma Armor",
    "Solid Rock"
  ],
  "Camerupt-Mega": [
    "Sheer Force"
  ],
  "Capsakid": [
    "Chlorophyll",
    "Insomnia",
    "Klutz"
  ],
  "Carbink": [
    "Clear Body",
    "Sturdy"
  ],
  "Caribolt": [
    "Galvanize",
    "Overgrow"
  ],
  "Carkol": [
    "Flame Body",
    "Flash Fire",
    "Steam Engine"
  ],
  "Carnivine": [
    "Levitate"
  ],
  "Carracosta": [
    "Solid Rock",
    "Sturdy",
    "Swift Swim"
  ],
  "Carvanha": [
    "Rough Skin",
    "Speed Boost"
  ],
  "Cascoon": [
    "Shed Skin"
  ],
  "Castform": [
    "Forecast"
  ],
  "Castform-Rainy": [
    "Forecast"
  ],
  "Castform-Snowy": [
    "Forecast"
  ],
  "Castform-Sunny": [
    "Forecast"
  ],
  "Caterpie": [
    "Run Away",
    "Shield Dust"
  ],
  "Cawdet": [
    "Big Pecks",
    "Keen Eye",
    "Volt Absorb"
  ],
  "Cawmodore": [
    "Big Pecks",
    "Intimidate",
    "Volt Absorb"
  ],
  "Celebi": [
    "Natural Cure"
  ],
  "Celesteela": [
    "Beast Boost"
  ],
  "Centiskorch": [
    "Flame Body",
    "Flash Fire",
    "White Smoke"
  ],
  "Centiskorch-Gmax": [
    "Flame Body",
    "Flash Fire",
    "White Smoke"
  ],
  "Ceruledge": [
    "Flash Fire",
    "Weak Armor"
  ],
  "Cetitan": [
    "Sheer Force",
    "Slush Rush",
    "Thick Fat"
  ],
  "Cetoddle": [
    "Sheer Force",
    "Snow Cloak",
    "Thick Fat"
  ],
  "Chandelure": [
    "Flame Body",
    "Flash Fire",
    "Infiltrator"
  ],
  "Chandelure-Mega": [
    "Infiltrator"
  ],
  "Chansey": [
    "Healer",
    "Natural Cure",
    "Serene Grace"
  ],
  "Charcadet": [
    "Flame Body",
    "Flash Fire"
  ],
  "Charizard": [
    "Blaze",
    "Solar Power"
  ],
  "Charizard-Gmax": [
    "Blaze",
    "Solar Power"
  ],
  "Charizard-Mega-X": [
    "Tough Claws"
  ],
  "Charizard-Mega-Y": [
    "Drought"
  ],
  "Charjabug": [
    "Battery"
  ],
  "Charmander": [
    "Blaze",
    "Solar Power"
  ],
  "Charmeleon": [
    "Blaze",
    "Solar Power"
  ],
  "Chatot": [
    "Big Pecks",
    "Keen Eye",
    "Tangled Feet"
  ],
  "Cherrim": [
    "Flower Gift"
  ],
  "Cherrim-Sunshine": [
    "Flower Gift"
  ],
  "Cherubi": [
    "Chlorophyll"
  ],
  "Chesnaught": [
    "Bulletproof",
    "Overgrow"
  ],
  "Chesnaught-Mega": [
    "Bulletproof"
  ],
  "Chespin": [
    "Bulletproof",
    "Overgrow"
  ],
  "Chewtle": [
    "Shell Armor",
    "Strong Jaw",
    "Swift Swim"
  ],
  "Chi-Yu": [
    "Beads of Ruin"
  ],
  "Chien-Pao": [
    "Sword of Ruin"
  ],
  "Chikorita": [
    "Leaf Guard",
    "Overgrow"
  ],
  "Chimchar": [
    "Blaze",
    "Iron Fist"
  ],
  "Chimecho": [
    "Levitate"
  ],
  "Chimecho-Mega": [
    "Levitate"
  ],
  "Chinchou": [
    "Illuminate",
    "Volt Absorb",
    "Water Absorb"
  ],
  "Chingling": [
    "Levitate"
  ],
  "Chromera": [
    "Color Change"
  ],
  "Chuggalong": [
    "Armor Tail",
    "Slow Start",
    "White Smoke"
  ],
  "Chuggon": [
    "Shell Armor",
    "Slow Start",
    "White Smoke"
  ],
  "Cinccino": [
    "Cute Charm",
    "Skill Link",
    "Technician"
  ],
  "Cinderace": [
    "Blaze",
    "Libero"
  ],
  "Cinderace-Gmax": [
    "Blaze",
    "Libero"
  ],
  "Clamperl": [
    "Rattled",
    "Shell Armor"
  ],
  "Clauncher": [
    "Mega Launcher"
  ],
  "Clawitzer": [
    "Mega Launcher"
  ],
  "Claydol": [
    "Levitate"
  ],
  "Clefable": [
    "Cute Charm",
    "Magic Guard",
    "Unaware"
  ],
  "Clefable-Mega": [
    "Magic Bounce"
  ],
  "Clefairy": [
    "Cute Charm",
    "Friend Guard",
    "Magic Guard"
  ],
  "Cleffa": [
    "Cute Charm",
    "Friend Guard",
    "Magic Guard"
  ],
  "Clobbopus": [
    "Limber",
    "Technician"
  ],
  "Clodsire": [
    "Poison Point",
    "Unaware",
    "Water Absorb"
  ],
  "Cloyster": [
    "Overcoat",
    "Shell Armor",
    "Skill Link"
  ],
  "Coalossal": [
    "Flame Body",
    "Flash Fire",
    "Steam Engine"
  ],
  "Coalossal-Gmax": [
    "Flame Body",
    "Flash Fire",
    "Steam Engine"
  ],
  "Cobalion": [
    "Justified"
  ],
  "Cofagrigus": [
    "Mummy"
  ],
  "Colossoil": [
    "Guts",
    "Rebound",
    "Unnerve"
  ],
  "Combee": [
    "Honey Gather",
    "Hustle"
  ],
  "Combusken": [
    "Blaze",
    "Speed Boost"
  ],
  "Comfey": [
    "Flower Veil",
    "Natural Cure",
    "Triage"
  ],
  "Conkeldurr": [
    "Guts",
    "Iron Fist",
    "Sheer Force"
  ],
  "Copperajah": [
    "Heavy Metal",
    "Sheer Force"
  ],
  "Copperajah-Gmax": [
    "Heavy Metal",
    "Sheer Force"
  ],
  "Coribalis": [
    "Poison Heal",
    "Torrent"
  ],
  "Corphish": [
    "Adaptability",
    "Hyper Cutter",
    "Shell Armor"
  ],
  "Corsola": [
    "Hustle",
    "Natural Cure",
    "Regenerator"
  ],
  "Corsola-Galar": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Corviknight": [
    "Mirror Armor",
    "Pressure",
    "Unnerve"
  ],
  "Corviknight-Gmax": [
    "Mirror Armor",
    "Pressure",
    "Unnerve"
  ],
  "Corvisquire": [
    "Big Pecks",
    "Keen Eye",
    "Unnerve"
  ],
  "Cosmoem": [
    "Sturdy"
  ],
  "Cosmog": [
    "Unaware"
  ],
  "Cottonee": [
    "Chlorophyll",
    "Infiltrator",
    "Prankster"
  ],
  "Crabominable": [
    "Anger Point",
    "Hyper Cutter",
    "Iron Fist"
  ],
  "Crabominable-Mega": [
    "Iron Fist"
  ],
  "Crabrawler": [
    "Anger Point",
    "Hyper Cutter",
    "Iron Fist"
  ],
  "Cradily": [
    "Storm Drain",
    "Suction Cups"
  ],
  "Cramorant": [
    "Gulp Missile"
  ],
  "Cramorant-Gorging": [
    "Gulp Missile"
  ],
  "Cramorant-Gulping": [
    "Gulp Missile"
  ],
  "Cranidos": [
    "Mold Breaker",
    "Sheer Force"
  ],
  "Crawdaunt": [
    "Adaptability",
    "Hyper Cutter",
    "Shell Armor"
  ],
  "Cresceidon": [
    "Multiscale",
    "Rough Skin",
    "Water Veil"
  ],
  "Cresselia": [
    "Levitate"
  ],
  "Croagunk": [
    "Anticipation",
    "Dry Skin",
    "Poison Touch"
  ],
  "Crobat": [
    "Infiltrator",
    "Inner Focus"
  ],
  "Crocalor": [
    "Blaze",
    "Unaware"
  ],
  "Croconaw": [
    "Sheer Force",
    "Torrent"
  ],
  "Crucibelle": [
    "Liquid Ooze",
    "Mold Breaker",
    "Regenerator"
  ],
  "Crucibelle-Mega": [
    "Magic Guard"
  ],
  "Crustle": [
    "Shell Armor",
    "Sturdy",
    "Weak Armor"
  ],
  "Cryogonal": [
    "Levitate"
  ],
  "Cubchoo": [
    "Rattled",
    "Slush Rush",
    "Snow Cloak"
  ],
  "Cubone": [
    "Battle Armor",
    "Lightning Rod",
    "Rock Head"
  ],
  "Cufant": [
    "Heavy Metal",
    "Sheer Force"
  ],
  "Cupra": [
    "Keen Eye",
    "Magic Guard",
    "Shield Dust"
  ],
  "Cursola": [
    "Perish Body",
    "Weak Armor"
  ],
  "Cutiefly": [
    "Honey Gather",
    "Shield Dust",
    "Sweet Veil"
  ],
  "Cyclizar": [
    "Regenerator",
    "Shed Skin"
  ],
  "Cyclohm": [
    "Damp",
    "Shield Dust",
    "Static"
  ],
  "Cyndaquil": [
    "Blaze",
    "Flash Fire"
  ],
  "Dachsbun": [
    "Aroma Veil",
    "Well-Baked Body"
  ],
  "Darkrai": [
    "Bad Dreams"
  ],
  "Darkrai-Mega": [
    "Bad Dreams"
  ],
  "Darmanitan": [
    "Sheer Force",
    "Zen Mode"
  ],
  "Darmanitan-Galar": [
    "Gorilla Tactics",
    "Zen Mode"
  ],
  "Darmanitan-Galar-Zen": [
    "Zen Mode"
  ],
  "Darmanitan-Zen": [
    "Zen Mode"
  ],
  "Dartrix": [
    "Long Reach",
    "Overgrow"
  ],
  "Darumaka": [
    "Hustle",
    "Inner Focus"
  ],
  "Darumaka-Galar": [
    "Hustle",
    "Inner Focus"
  ],
  "Decidueye": [
    "Long Reach",
    "Overgrow"
  ],
  "Decidueye-Hisui": [
    "Overgrow",
    "Scrappy"
  ],
  "Dedenne": [
    "Cheek Pouch",
    "Pickup",
    "Plus"
  ],
  "Deerling": [
    "Chlorophyll",
    "Sap Sipper",
    "Serene Grace"
  ],
  "Deino": [
    "Hustle"
  ],
  "Delcatty": [
    "Cute Charm",
    "Normalize",
    "Wonder Skin"
  ],
  "Delibird": [
    "Hustle",
    "Insomnia",
    "Vital Spirit"
  ],
  "Delphox": [
    "Blaze",
    "Magician"
  ],
  "Delphox-Mega": [
    "Levitate"
  ],
  "Deoxys": [
    "Pressure"
  ],
  "Deoxys-Attack": [
    "Pressure"
  ],
  "Deoxys-Defense": [
    "Pressure"
  ],
  "Deoxys-Speed": [
    "Pressure"
  ],
  "Dewgong": [
    "Hydration",
    "Ice Body",
    "Thick Fat"
  ],
  "Dewott": [
    "Shell Armor",
    "Torrent"
  ],
  "Dewpider": [
    "Water Absorb",
    "Water Bubble"
  ],
  "Dhelmise": [
    "Steelworker"
  ],
  "Dialga": [
    "Pressure",
    "Telepathy"
  ],
  "Dialga-Origin": [
    "Pressure",
    "Telepathy"
  ],
  "Diancie": [
    "Clear Body"
  ],
  "Diancie-Mega": [
    "Magic Bounce"
  ],
  "Diggersby": [
    "Cheek Pouch",
    "Huge Power",
    "Pickup"
  ],
  "Diglett": [
    "Arena Trap",
    "Sand Force",
    "Sand Veil"
  ],
  "Diglett-Alola": [
    "Sand Force",
    "Sand Veil",
    "Tangling Hair"
  ],
  "Dipplin": [
    "Gluttony",
    "Sticky Hold",
    "Supersweet Syrup"
  ],
  "Ditto": [
    "Imposter",
    "Limber"
  ],
  "Dodrio": [
    "Early Bird",
    "Run Away",
    "Tangled Feet"
  ],
  "Doduo": [
    "Early Bird",
    "Run Away",
    "Tangled Feet"
  ],
  "Dolliv": [
    "Early Bird",
    "Harvest"
  ],
  "Dondozo": [
    "Oblivious",
    "Unaware",
    "Water Veil"
  ],
  "Donphan": [
    "Sand Veil",
    "Sturdy"
  ],
  "Dorsoil": [
    "Guts",
    "Oblivious",
    "Unnerve"
  ],
  "Dottler": [
    "Compound Eyes",
    "Swarm",
    "Telepathy"
  ],
  "Doublade": [
    "No Guard"
  ],
  "Dracovish": [
    "Sand Rush",
    "Strong Jaw",
    "Water Absorb"
  ],
  "Dracozolt": [
    "Hustle",
    "Sand Rush",
    "Volt Absorb"
  ],
  "Dragalge": [
    "Adaptability",
    "Poison Point",
    "Poison Touch"
  ],
  "Dragalge-Mega": [
    "Regenerator"
  ],
  "Dragapult": [
    "Clear Body",
    "Cursed Body",
    "Infiltrator"
  ],
  "Draggalong": [
    "Armor Tail",
    "Slow Start",
    "White Smoke"
  ],
  "Dragonair": [
    "Marvel Scale",
    "Shed Skin"
  ],
  "Dragonite": [
    "Inner Focus",
    "Multiscale"
  ],
  "Dragonite-Mega": [
    "Multiscale"
  ],
  "Drakloak": [
    "Clear Body",
    "Cursed Body",
    "Infiltrator"
  ],
  "Drampa": [
    "Berserk",
    "Cloud Nine",
    "Sap Sipper"
  ],
  "Drampa-Mega": [
    "Berserk"
  ],
  "Drapion": [
    "Battle Armor",
    "Keen Eye",
    "Sniper"
  ],
  "Dratini": [
    "Marvel Scale",
    "Shed Skin"
  ],
  "Drednaw": [
    "Shell Armor",
    "Strong Jaw",
    "Swift Swim"
  ],
  "Drednaw-Gmax": [
    "Shell Armor",
    "Strong Jaw",
    "Swift Swim"
  ],
  "Dreepy": [
    "Clear Body",
    "Cursed Body",
    "Infiltrator"
  ],
  "Drifblim": [
    "Aftermath",
    "Flare Boost",
    "Unburden"
  ],
  "Drifloon": [
    "Aftermath",
    "Flare Boost",
    "Unburden"
  ],
  "Drilbur": [
    "Mold Breaker",
    "Sand Force",
    "Sand Rush"
  ],
  "Drizzile": [
    "Sniper",
    "Torrent"
  ],
  "Drowzee": [
    "Forewarn",
    "Inner Focus",
    "Insomnia"
  ],
  "Druddigon": [
    "Mold Breaker",
    "Rough Skin",
    "Sheer Force"
  ],
  "Dubwool": [
    "Bulletproof",
    "Fluffy",
    "Steadfast"
  ],
  "Ducklett": [
    "Big Pecks",
    "Hydration",
    "Keen Eye"
  ],
  "Dudunsparce": [
    "Rattled",
    "Run Away",
    "Serene Grace"
  ],
  "Dudunsparce-Three-Segment": [
    "Rattled",
    "Run Away",
    "Serene Grace"
  ],
  "Dugtrio": [
    "Arena Trap",
    "Sand Force",
    "Sand Veil"
  ],
  "Dugtrio-Alola": [
    "Sand Force",
    "Sand Veil",
    "Tangling Hair"
  ],
  "Dunsparce": [
    "Rattled",
    "Run Away",
    "Serene Grace"
  ],
  "Duohm": [
    "Damp",
    "Shield Dust",
    "Static"
  ],
  "Duosion": [
    "Magic Guard",
    "Overcoat",
    "Regenerator"
  ],
  "Duraludon": [
    "Heavy Metal",
    "Light Metal",
    "Stalwart"
  ],
  "Duraludon-Gmax": [
    "Heavy Metal",
    "Light Metal",
    "Stalwart"
  ],
  "Durant": [
    "Hustle",
    "Swarm",
    "Truant"
  ],
  "Dusclops": [
    "Frisk",
    "Pressure"
  ],
  "Dusknoir": [
    "Frisk",
    "Pressure"
  ],
  "Duskull": [
    "Frisk",
    "Levitate"
  ],
  "Dustox": [
    "Compound Eyes",
    "Shield Dust"
  ],
  "Dwebble": [
    "Shell Armor",
    "Sturdy",
    "Weak Armor"
  ],
  "Eelektrik": [
    "Levitate"
  ],
  "Eelektross": [
    "Levitate"
  ],
  "Eelektross-Mega": [
    "Eelevate"
  ],
  "Eevee": [
    "Adaptability",
    "Anticipation",
    "Run Away"
  ],
  "Eevee-Gmax": [
    "Adaptability",
    "Anticipation",
    "Run Away"
  ],
  "Eevee-Starter": [
    "Adaptability",
    "Anticipation",
    "Run Away"
  ],
  "Eiscue": [
    "Ice Face"
  ],
  "Eiscue-Noice": [
    "Ice Face"
  ],
  "Ekans": [
    "Intimidate",
    "Shed Skin",
    "Unnerve"
  ],
  "Eldegoss": [
    "Cotton Down",
    "Effect Spore",
    "Regenerator"
  ],
  "Electabuzz": [
    "Static",
    "Vital Spirit"
  ],
  "Electivire": [
    "Motor Drive",
    "Vital Spirit"
  ],
  "Electrelk": [
    "Galvanize",
    "Overgrow"
  ],
  "Electrike": [
    "Lightning Rod",
    "Minus",
    "Static"
  ],
  "Electrode": [
    "Aftermath",
    "Soundproof",
    "Static"
  ],
  "Electrode-Hisui": [
    "Aftermath",
    "Soundproof",
    "Static"
  ],
  "Elekid": [
    "Static",
    "Vital Spirit"
  ],
  "Elgyem": [
    "Analytic",
    "Synchronize",
    "Telepathy"
  ],
  "Embirch": [
    "Chlorophyll",
    "Leaf Guard",
    "Reckless"
  ],
  "Emboar": [
    "Blaze",
    "Reckless"
  ],
  "Emboar-Mega": [
    "Mold Breaker"
  ],
  "Emolga": [
    "Motor Drive",
    "Static"
  ],
  "Empoleon": [
    "Competitive",
    "Torrent"
  ],
  "Enamorus": [
    "Contrary",
    "Cute Charm"
  ],
  "Enamorus-Therian": [
    "Overcoat"
  ],
  "Entei": [
    "Inner Focus",
    "Pressure"
  ],
  "Equilibra": [
    "Bulletproof",
    "Justified",
    "Levitate"
  ],
  "Escavalier": [
    "Overcoat",
    "Shell Armor",
    "Swarm"
  ],
  "Espathra": [
    "Frisk",
    "Opportunist",
    "Speed Boost"
  ],
  "Espeon": [
    "Magic Bounce",
    "Synchronize"
  ],
  "Espurr": [
    "Infiltrator",
    "Keen Eye",
    "Own Tempo"
  ],
  "Eternatus": [
    "Pressure"
  ],
  "Eternatus-Eternamax": [
    "Pressure"
  ],
  "Excadrill": [
    "Mold Breaker",
    "Sand Force",
    "Sand Rush"
  ],
  "Excadrill-Mega": [
    "Piercing Drill"
  ],
  "Exeggcute": [
    "Chlorophyll",
    "Harvest"
  ],
  "Exeggutor": [
    "Chlorophyll",
    "Harvest"
  ],
  "Exeggutor-Alola": [
    "Frisk",
    "Harvest"
  ],
  "Exploud": [
    "Scrappy",
    "Soundproof"
  ],
  "Falinks": [
    "Battle Armor",
    "Defiant"
  ],
  "Falinks-Mega": [
    "Defiant"
  ],
  "Farfetch’d": [
    "Defiant",
    "Inner Focus",
    "Keen Eye"
  ],
  "Farfetch’d-Galar": [
    "Scrappy",
    "Steadfast"
  ],
  "Farigiraf": [
    "Armor Tail",
    "Cud Chew",
    "Sap Sipper"
  ],
  "Fawnifer": [
    "Lightning Rod",
    "Overgrow"
  ],
  "Fearow": [
    "Keen Eye",
    "Sniper"
  ],
  "Feebas": [
    "Adaptability",
    "Oblivious",
    "Swift Swim"
  ],
  "Fennekin": [
    "Blaze",
    "Magician"
  ],
  "Feraligatr": [
    "Sheer Force",
    "Torrent"
  ],
  "Feraligatr-Mega": [
    "Dragonize"
  ],
  "Ferroseed": [
    "Iron Barbs"
  ],
  "Ferrothorn": [
    "Anticipation",
    "Iron Barbs"
  ],
  "Fezandipiti": [
    "Technician",
    "Toxic Chain"
  ],
  "Fidgit": [
    "Frisk",
    "Persistent",
    "Vital Spirit"
  ],
  "Fidough": [
    "Klutz",
    "Own Tempo"
  ],
  "Finizen": [
    "Water Veil"
  ],
  "Finneon": [
    "Storm Drain",
    "Swift Swim",
    "Water Veil"
  ],
  "Flaaffy": [
    "Plus",
    "Static"
  ],
  "Flabébé": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Flamigo": [
    "Costar",
    "Scrappy",
    "Tangled Feet"
  ],
  "Flapple": [
    "Gluttony",
    "Hustle",
    "Ripen"
  ],
  "Flapple-Gmax": [
    "Gluttony",
    "Hustle",
    "Ripen"
  ],
  "Flarelm": [
    "Battle Armor",
    "Rock Head",
    "White Smoke"
  ],
  "Flareon": [
    "Flash Fire",
    "Guts"
  ],
  "Fletchinder": [
    "Flame Body",
    "Gale Wings"
  ],
  "Fletchling": [
    "Big Pecks",
    "Gale Wings"
  ],
  "Flittle": [
    "Anticipation",
    "Frisk",
    "Speed Boost"
  ],
  "Floatoy": [
    "Heatproof",
    "Swift Swim",
    "Water Veil"
  ],
  "Floatzel": [
    "Swift Swim",
    "Water Veil"
  ],
  "Floette": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Floette-Eternal": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Floette-Mega": [
    "Fairy Aura"
  ],
  "Floragato": [
    "Overgrow",
    "Protean"
  ],
  "Florges": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Flox": [
    "Cud Chew",
    "Static",
    "Sticky Hold"
  ],
  "Flutter Mane": [
    "Protosynthesis"
  ],
  "Flygon": [
    "Levitate"
  ],
  "Fomantis": [
    "Contrary",
    "Leaf Guard"
  ],
  "Foongus": [
    "Effect Spore",
    "Regenerator"
  ],
  "Forretress": [
    "Overcoat",
    "Sturdy"
  ],
  "Fraxure": [
    "Mold Breaker",
    "Rivalry",
    "Unnerve"
  ],
  "Frigibax": [
    "Ice Body",
    "Thermal Exchange"
  ],
  "Frillish": [
    "Cursed Body",
    "Damp",
    "Water Absorb"
  ],
  "Froakie": [
    "Protean",
    "Torrent"
  ],
  "Frogadier": [
    "Protean",
    "Torrent"
  ],
  "Froslass": [
    "Cursed Body",
    "Snow Cloak"
  ],
  "Froslass-Mega": [
    "Snow Warning"
  ],
  "Frosmoth": [
    "Ice Scales",
    "Shield Dust"
  ],
  "Fuecoco": [
    "Blaze",
    "Unaware"
  ],
  "Furfrou": [
    "Fur Coat"
  ],
  "Furret": [
    "Frisk",
    "Keen Eye",
    "Run Away"
  ],
  "Gabite": [
    "Rough Skin",
    "Sand Veil"
  ],
  "Gallade": [
    "Justified",
    "Sharpness",
    "Steadfast"
  ],
  "Gallade-Mega": [
    "Inner Focus"
  ],
  "Galvantula": [
    "Compound Eyes",
    "Swarm",
    "Unnerve"
  ],
  "Garbodor": [
    "Aftermath",
    "Stench",
    "Weak Armor"
  ],
  "Garbodor-Gmax": [
    "Aftermath",
    "Stench",
    "Weak Armor"
  ],
  "Garchomp": [
    "Rough Skin",
    "Sand Veil"
  ],
  "Garchomp-Mega": [
    "Sand Force"
  ],
  "Garchomp-Mega-Z": [
    "Sand Force"
  ],
  "Gardevoir": [
    "Synchronize",
    "Telepathy",
    "Trace"
  ],
  "Gardevoir-Mega": [
    "Pixilate"
  ],
  "Garganacl": [
    "Clear Body",
    "Purifying Salt",
    "Sturdy"
  ],
  "Gastly": [
    "Levitate"
  ],
  "Gastrodon": [
    "Sand Force",
    "Sticky Hold",
    "Storm Drain"
  ],
  "Genesect": [
    "Download"
  ],
  "Genesect-Burn": [
    "Download"
  ],
  "Genesect-Chill": [
    "Download"
  ],
  "Genesect-Douse": [
    "Download"
  ],
  "Genesect-Shock": [
    "Download"
  ],
  "Gengar": [
    "Cursed Body"
  ],
  "Gengar-Gmax": [
    "Cursed Body"
  ],
  "Gengar-Mega": [
    "Shadow Tag"
  ],
  "Geodude": [
    "Rock Head",
    "Sand Veil",
    "Sturdy"
  ],
  "Geodude-Alola": [
    "Galvanize",
    "Magnet Pull",
    "Sturdy"
  ],
  "Gholdengo": [
    "Good as Gold"
  ],
  "Gible": [
    "Rough Skin",
    "Sand Veil"
  ],
  "Gigalith": [
    "Sand Force",
    "Sand Stream",
    "Sturdy"
  ],
  "Gimmighoul": [
    "Rattled"
  ],
  "Gimmighoul-Roaming": [
    "Run Away"
  ],
  "Girafarig": [
    "Early Bird",
    "Inner Focus",
    "Sap Sipper"
  ],
  "Giratina": [
    "Pressure",
    "Telepathy"
  ],
  "Giratina-Origin": [
    "Levitate"
  ],
  "Glaceon": [
    "Ice Body",
    "Snow Cloak"
  ],
  "Glalie": [
    "Ice Body",
    "Inner Focus",
    "Moody"
  ],
  "Glalie-Mega": [
    "Refrigerate"
  ],
  "Glameow": [
    "Keen Eye",
    "Limber",
    "Own Tempo"
  ],
  "Glastrier": [
    "Chilling Neigh"
  ],
  "Gligar": [
    "Hyper Cutter",
    "Immunity",
    "Sand Veil"
  ],
  "Glimmet": [
    "Corrosion",
    "Toxic Debris"
  ],
  "Glimmora": [
    "Corrosion",
    "Toxic Debris"
  ],
  "Glimmora-Mega": [
    "Adaptability"
  ],
  "Gliscor": [
    "Hyper Cutter",
    "Poison Heal",
    "Sand Veil"
  ],
  "Gloom": [
    "Chlorophyll",
    "Stench"
  ],
  "Gogoat": [
    "Grass Pelt",
    "Sap Sipper"
  ],
  "Golbat": [
    "Infiltrator",
    "Inner Focus"
  ],
  "Goldeen": [
    "Lightning Rod",
    "Swift Swim",
    "Water Veil"
  ],
  "Golduck": [
    "Cloud Nine",
    "Damp",
    "Swift Swim"
  ],
  "Golem": [
    "Rock Head",
    "Sand Veil",
    "Sturdy"
  ],
  "Golem-Alola": [
    "Galvanize",
    "Magnet Pull",
    "Sturdy"
  ],
  "Golett": [
    "Iron Fist",
    "Klutz",
    "No Guard"
  ],
  "Golisopod": [
    "Emergency Exit"
  ],
  "Golisopod-Mega": [
    "Emergency Exit"
  ],
  "Golurk": [
    "Iron Fist",
    "Klutz",
    "No Guard"
  ],
  "Golurk-Mega": [
    "Unseen Fist"
  ],
  "Goodra": [
    "Gooey",
    "Hydration",
    "Sap Sipper"
  ],
  "Goodra-Hisui": [
    "Gooey",
    "Sap Sipper",
    "Shell Armor"
  ],
  "Goomy": [
    "Gooey",
    "Hydration",
    "Sap Sipper"
  ],
  "Gorebyss": [
    "Hydration",
    "Swift Swim"
  ],
  "Gossifleur": [
    "Cotton Down",
    "Effect Spore",
    "Regenerator"
  ],
  "Gothita": [
    "Competitive",
    "Frisk",
    "Shadow Tag"
  ],
  "Gothitelle": [
    "Competitive",
    "Frisk",
    "Shadow Tag"
  ],
  "Gothorita": [
    "Competitive",
    "Frisk",
    "Shadow Tag"
  ],
  "Gouging Fire": [
    "Protosynthesis"
  ],
  "Gourgeist": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Large": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Small": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Super": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Grafaiai": [
    "Poison Touch",
    "Prankster",
    "Unburden"
  ],
  "Granbull": [
    "Intimidate",
    "Quick Feet",
    "Rattled"
  ],
  "Grapploct": [
    "Limber",
    "Technician"
  ],
  "Graveler": [
    "Rock Head",
    "Sand Veil",
    "Sturdy"
  ],
  "Graveler-Alola": [
    "Galvanize",
    "Magnet Pull",
    "Sturdy"
  ],
  "Great Tusk": [
    "Protosynthesis"
  ],
  "Greavard": [
    "Fluffy",
    "Pickup"
  ],
  "Greedent": [
    "Cheek Pouch",
    "Gluttony"
  ],
  "Greninja": [
    "Battle Bond",
    "Protean",
    "Torrent"
  ],
  "Greninja-Ash": [
    "Battle Bond"
  ],
  "Greninja-Bond": [
    "Battle Bond"
  ],
  "Greninja-Mega": [
    "Protean"
  ],
  "Grimer": [
    "Poison Touch",
    "Stench",
    "Sticky Hold"
  ],
  "Grimer-Alola": [
    "Gluttony",
    "Poison Touch",
    "Power of Alchemy"
  ],
  "Grimmsnarl": [
    "Frisk",
    "Pickpocket",
    "Prankster"
  ],
  "Grimmsnarl-Gmax": [
    "Frisk",
    "Pickpocket",
    "Prankster"
  ],
  "Grookey": [
    "Grassy Surge",
    "Overgrow"
  ],
  "Grotle": [
    "Overgrow",
    "Shell Armor"
  ],
  "Groudon": [
    "Drought"
  ],
  "Groudon-Primal": [
    "Desolate Land"
  ],
  "Grovyle": [
    "Overgrow",
    "Unburden"
  ],
  "Growlithe": [
    "Flash Fire",
    "Intimidate",
    "Justified"
  ],
  "Growlithe-Hisui": [
    "Flash Fire",
    "Intimidate",
    "Rock Head"
  ],
  "Grubbin": [
    "Swarm"
  ],
  "Grumpig": [
    "Gluttony",
    "Own Tempo",
    "Thick Fat"
  ],
  "Gulpin": [
    "Gluttony",
    "Liquid Ooze",
    "Sticky Hold"
  ],
  "Gumshoos": [
    "Adaptability",
    "Stakeout",
    "Strong Jaw"
  ],
  "Gumshoos-Totem": [
    "Adaptability"
  ],
  "Gurdurr": [
    "Guts",
    "Iron Fist",
    "Sheer Force"
  ],
  "Guzzlord": [
    "Beast Boost"
  ],
  "Gyarados": [
    "Intimidate",
    "Moxie"
  ],
  "Gyarados-Mega": [
    "Mold Breaker"
  ],
  "Hakamo-o": [
    "Bulletproof",
    "Overcoat",
    "Soundproof"
  ],
  "Happiny": [
    "Friend Guard",
    "Natural Cure",
    "Serene Grace"
  ],
  "Hariyama": [
    "Guts",
    "Sheer Force",
    "Thick Fat"
  ],
  "Hatenna": [
    "Anticipation",
    "Healer",
    "Magic Bounce"
  ],
  "Hatterene": [
    "Anticipation",
    "Healer",
    "Magic Bounce"
  ],
  "Hatterene-Gmax": [
    "Anticipation",
    "Healer",
    "Magic Bounce"
  ],
  "Hattrem": [
    "Anticipation",
    "Healer",
    "Magic Bounce"
  ],
  "Haunter": [
    "Levitate"
  ],
  "Hawlucha": [
    "Limber",
    "Mold Breaker",
    "Unburden"
  ],
  "Hawlucha-Mega": [
    "No Guard"
  ],
  "Haxorus": [
    "Mold Breaker",
    "Rivalry",
    "Unnerve"
  ],
  "Heatmor": [
    "Flash Fire",
    "Gluttony",
    "White Smoke"
  ],
  "Heatran": [
    "Flame Body",
    "Flash Fire"
  ],
  "Heatran-Mega": [
    "Flame Body",
    "Flash Fire"
  ],
  "Heliolisk": [
    "Dry Skin",
    "Sand Veil",
    "Solar Power"
  ],
  "Helioptile": [
    "Dry Skin",
    "Sand Veil",
    "Solar Power"
  ],
  "Hemogoblin": [
    "Intimidate",
    "Own Tempo",
    "Pixilate"
  ],
  "Heracross": [
    "Guts",
    "Moxie",
    "Swarm"
  ],
  "Heracross-Mega": [
    "Skill Link"
  ],
  "Herdier": [
    "Intimidate",
    "Sand Rush",
    "Scrappy"
  ],
  "Hippopotas": [
    "Sand Force",
    "Sand Stream"
  ],
  "Hippowdon": [
    "Sand Force",
    "Sand Stream"
  ],
  "Hitmonchan": [
    "Inner Focus",
    "Iron Fist",
    "Keen Eye"
  ],
  "Hitmonlee": [
    "Limber",
    "Reckless",
    "Unburden"
  ],
  "Hitmontop": [
    "Intimidate",
    "Steadfast",
    "Technician"
  ],
  "Ho-Oh": [
    "Pressure",
    "Regenerator"
  ],
  "Honchkrow": [
    "Insomnia",
    "Moxie",
    "Super Luck"
  ],
  "Honedge": [
    "No Guard"
  ],
  "Hoopa": [
    "Magician"
  ],
  "Hoopa-Unbound": [
    "Magician"
  ],
  "Hoothoot": [
    "Insomnia",
    "Keen Eye",
    "Tinted Lens"
  ],
  "Hoppip": [
    "Chlorophyll",
    "Infiltrator",
    "Leaf Guard"
  ],
  "Horsea": [
    "Damp",
    "Sniper",
    "Swift Swim"
  ],
  "Houndoom": [
    "Early Bird",
    "Flash Fire",
    "Unnerve"
  ],
  "Houndoom-Mega": [
    "Solar Power"
  ],
  "Houndour": [
    "Early Bird",
    "Flash Fire",
    "Unnerve"
  ],
  "Houndstone": [
    "Fluffy",
    "Sand Rush"
  ],
  "Huntail": [
    "Swift Swim",
    "Water Veil"
  ],
  "Hydrapple": [
    "Regenerator",
    "Sticky Hold",
    "Supersweet Syrup"
  ],
  "Hydreigon": [
    "Levitate"
  ],
  "Hypno": [
    "Forewarn",
    "Inner Focus",
    "Insomnia"
  ],
  "Igglybuff": [
    "Competitive",
    "Cute Charm",
    "Friend Guard"
  ],
  "Illumise": [
    "Oblivious",
    "Prankster",
    "Tinted Lens"
  ],
  "Impidimp": [
    "Frisk",
    "Pickpocket",
    "Prankster"
  ],
  "Incineroar": [
    "Blaze",
    "Intimidate"
  ],
  "Indeedee": [
    "Inner Focus",
    "Psychic Surge",
    "Synchronize"
  ],
  "Indeedee-F": [
    "Own Tempo",
    "Psychic Surge",
    "Synchronize"
  ],
  "Infernape": [
    "Blaze",
    "Iron Fist"
  ],
  "Inkay": [
    "Contrary",
    "Infiltrator",
    "Suction Cups"
  ],
  "Inteleon": [
    "Sniper",
    "Torrent"
  ],
  "Inteleon-Gmax": [
    "Sniper",
    "Torrent"
  ],
  "Iron Boulder": [
    "Quark Drive"
  ],
  "Iron Bundle": [
    "Quark Drive"
  ],
  "Iron Crown": [
    "Quark Drive"
  ],
  "Iron Hands": [
    "Quark Drive"
  ],
  "Iron Jugulis": [
    "Quark Drive"
  ],
  "Iron Leaves": [
    "Quark Drive"
  ],
  "Iron Moth": [
    "Quark Drive"
  ],
  "Iron Thorns": [
    "Quark Drive"
  ],
  "Iron Treads": [
    "Quark Drive"
  ],
  "Iron Valiant": [
    "Quark Drive"
  ],
  "Ivysaur": [
    "Chlorophyll",
    "Overgrow"
  ],
  "Jangmo-o": [
    "Bulletproof",
    "Overcoat",
    "Soundproof"
  ],
  "Jellicent": [
    "Cursed Body",
    "Damp",
    "Water Absorb"
  ],
  "Jigglypuff": [
    "Competitive",
    "Cute Charm",
    "Friend Guard"
  ],
  "Jirachi": [
    "Serene Grace"
  ],
  "Jolteon": [
    "Quick Feet",
    "Volt Absorb"
  ],
  "Joltik": [
    "Compound Eyes",
    "Swarm",
    "Unnerve"
  ],
  "Jumbao": [
    "Drought",
    "Overcoat",
    "Trace"
  ],
  "Jumpluff": [
    "Chlorophyll",
    "Infiltrator",
    "Leaf Guard"
  ],
  "Justyke": [
    "Bulletproof",
    "Justified",
    "Levitate"
  ],
  "Jynx": [
    "Dry Skin",
    "Forewarn",
    "Oblivious"
  ],
  "Kabuto": [
    "Battle Armor",
    "Swift Swim",
    "Weak Armor"
  ],
  "Kabutops": [
    "Battle Armor",
    "Swift Swim",
    "Weak Armor"
  ],
  "Kadabra": [
    "Inner Focus",
    "Magic Guard",
    "Synchronize"
  ],
  "Kakuna": [
    "Shed Skin"
  ],
  "Kangaskhan": [
    "Early Bird",
    "Inner Focus",
    "Scrappy"
  ],
  "Kangaskhan-Mega": [
    "Parental Bond"
  ],
  "Karrablast": [
    "No Guard",
    "Shed Skin",
    "Swarm"
  ],
  "Kartana": [
    "Beast Boost"
  ],
  "Kecleon": [
    "Color Change",
    "Protean"
  ],
  "Keldeo": [
    "Justified"
  ],
  "Keldeo-Resolute": [
    "Justified"
  ],
  "Kerfluffle": [
    "Aroma Veil",
    "Friend Guard",
    "Natural Cure"
  ],
  "Kilowattrel": [
    "Competitive",
    "Volt Absorb",
    "Wind Power"
  ],
  "Kingambit": [
    "Defiant",
    "Pressure",
    "Supreme Overlord"
  ],
  "Kingdra": [
    "Damp",
    "Sniper",
    "Swift Swim"
  ],
  "Kingler": [
    "Hyper Cutter",
    "Sheer Force",
    "Shell Armor"
  ],
  "Kingler-Gmax": [
    "Hyper Cutter",
    "Sheer Force",
    "Shell Armor"
  ],
  "Kirlia": [
    "Synchronize",
    "Telepathy",
    "Trace"
  ],
  "Kitsunoh": [
    "Frisk",
    "Limber",
    "Trace"
  ],
  "Klang": [
    "Clear Body",
    "Minus",
    "Plus"
  ],
  "Klawf": [
    "Anger Shell",
    "Regenerator",
    "Shell Armor"
  ],
  "Kleavor": [
    "Sharpness",
    "Sheer Force",
    "Swarm"
  ],
  "Klefki": [
    "Magician",
    "Prankster"
  ],
  "Klink": [
    "Clear Body",
    "Minus",
    "Plus"
  ],
  "Klinklang": [
    "Clear Body",
    "Minus",
    "Plus"
  ],
  "Koffing": [
    "Levitate",
    "Neutralizing Gas",
    "Stench"
  ],
  "Komala": [
    "Comatose"
  ],
  "Kommo-o": [
    "Bulletproof",
    "Overcoat",
    "Soundproof"
  ],
  "Kommo-o-Totem": [
    "Overcoat"
  ],
  "Koraidon": [
    "Orichalcum Pulse"
  ],
  "Krabby": [
    "Hyper Cutter",
    "Sheer Force",
    "Shell Armor"
  ],
  "Kricketot": [
    "Run Away",
    "Shed Skin"
  ],
  "Kricketune": [
    "Swarm",
    "Technician"
  ],
  "Krilowatt": [
    "Magic Guard",
    "Minus",
    "Trace"
  ],
  "Krokorok": [
    "Anger Point",
    "Intimidate",
    "Moxie"
  ],
  "Krookodile": [
    "Anger Point",
    "Intimidate",
    "Moxie"
  ],
  "Kubfu": [
    "Inner Focus"
  ],
  "Kyogre": [
    "Drizzle"
  ],
  "Kyogre-Primal": [
    "Primordial Sea"
  ],
  "Kyurem": [
    "Pressure"
  ],
  "Kyurem-Black": [
    "Teravolt"
  ],
  "Kyurem-White": [
    "Turboblaze"
  ],
  "Lairon": [
    "Heavy Metal",
    "Rock Head",
    "Sturdy"
  ],
  "Lampent": [
    "Flame Body",
    "Flash Fire",
    "Infiltrator"
  ],
  "Landorus": [
    "Sand Force",
    "Sheer Force"
  ],
  "Landorus-Therian": [
    "Intimidate"
  ],
  "Lanturn": [
    "Illuminate",
    "Volt Absorb",
    "Water Absorb"
  ],
  "Lapras": [
    "Hydration",
    "Shell Armor",
    "Water Absorb"
  ],
  "Lapras-Gmax": [
    "Hydration",
    "Shell Armor",
    "Water Absorb"
  ],
  "Larvesta": [
    "Flame Body",
    "Swarm"
  ],
  "Larvitar": [
    "Guts",
    "Sand Veil"
  ],
  "Latias": [
    "Levitate"
  ],
  "Latias-Mega": [
    "Levitate"
  ],
  "Latios": [
    "Levitate"
  ],
  "Latios-Mega": [
    "Levitate"
  ],
  "Leafeon": [
    "Chlorophyll",
    "Leaf Guard"
  ],
  "Leavanny": [
    "Chlorophyll",
    "Overcoat",
    "Swarm"
  ],
  "Lechonk": [
    "Aroma Veil",
    "Gluttony",
    "Thick Fat"
  ],
  "Ledian": [
    "Early Bird",
    "Iron Fist",
    "Swarm"
  ],
  "Ledyba": [
    "Early Bird",
    "Rattled",
    "Swarm"
  ],
  "Lickilicky": [
    "Cloud Nine",
    "Oblivious",
    "Own Tempo"
  ],
  "Lickitung": [
    "Cloud Nine",
    "Oblivious",
    "Own Tempo"
  ],
  "Liepard": [
    "Limber",
    "Prankster",
    "Unburden"
  ],
  "Lileep": [
    "Storm Drain",
    "Suction Cups"
  ],
  "Lilligant": [
    "Chlorophyll",
    "Leaf Guard",
    "Own Tempo"
  ],
  "Lilligant-Hisui": [
    "Chlorophyll",
    "Hustle",
    "Leaf Guard"
  ],
  "Lillipup": [
    "Pickup",
    "Run Away",
    "Vital Spirit"
  ],
  "Linoone": [
    "Gluttony",
    "Pickup",
    "Quick Feet"
  ],
  "Linoone-Galar": [
    "Gluttony",
    "Pickup",
    "Quick Feet"
  ],
  "Litleo": [
    "Moxie",
    "Rivalry",
    "Unnerve"
  ],
  "Litten": [
    "Blaze",
    "Intimidate"
  ],
  "Litwick": [
    "Flame Body",
    "Flash Fire",
    "Infiltrator"
  ],
  "Lokix": [
    "Swarm",
    "Tinted Lens"
  ],
  "Lombre": [
    "Own Tempo",
    "Rain Dish",
    "Swift Swim"
  ],
  "Lopunny": [
    "Cute Charm",
    "Klutz",
    "Limber"
  ],
  "Lopunny-Mega": [
    "Scrappy"
  ],
  "Lotad": [
    "Own Tempo",
    "Rain Dish",
    "Swift Swim"
  ],
  "Loudred": [
    "Scrappy",
    "Soundproof"
  ],
  "Lucario": [
    "Inner Focus",
    "Justified",
    "Steadfast"
  ],
  "Lucario-Mega": [
    "Adaptability"
  ],
  "Lucario-Mega-Z": [
    "Adaptability"
  ],
  "Ludicolo": [
    "Own Tempo",
    "Rain Dish",
    "Swift Swim"
  ],
  "Lugia": [
    "Multiscale",
    "Pressure"
  ],
  "Lumineon": [
    "Storm Drain",
    "Swift Swim",
    "Water Veil"
  ],
  "Lunala": [
    "Shadow Shield"
  ],
  "Lunatone": [
    "Levitate"
  ],
  "Lurantis": [
    "Contrary",
    "Leaf Guard"
  ],
  "Lurantis-Totem": [
    "Leaf Guard"
  ],
  "Luvdisc": [
    "Hydration",
    "Swift Swim"
  ],
  "Luxio": [
    "Guts",
    "Intimidate",
    "Rivalry"
  ],
  "Luxray": [
    "Guts",
    "Intimidate",
    "Rivalry"
  ],
  "Lycanroc": [
    "Keen Eye",
    "Sand Rush",
    "Steadfast"
  ],
  "Lycanroc-Dusk": [
    "Tough Claws"
  ],
  "Lycanroc-Midnight": [
    "Keen Eye",
    "No Guard",
    "Vital Spirit"
  ],
  "Mabosstiff": [
    "Guard Dog",
    "Intimidate",
    "Stakeout"
  ],
  "Machamp": [
    "Guts",
    "No Guard",
    "Steadfast"
  ],
  "Machamp-Gmax": [
    "Guts",
    "No Guard",
    "Steadfast"
  ],
  "Machoke": [
    "Guts",
    "No Guard",
    "Steadfast"
  ],
  "Machop": [
    "Guts",
    "No Guard",
    "Steadfast"
  ],
  "Magby": [
    "Flame Body",
    "Vital Spirit"
  ],
  "Magcargo": [
    "Flame Body",
    "Magma Armor",
    "Weak Armor"
  ],
  "Magearna": [
    "Soul-Heart"
  ],
  "Magearna-Mega": [
    "Soul-Heart"
  ],
  "Magearna-Original": [
    "Soul-Heart"
  ],
  "Magearna-Original-Mega": [
    "Soul-Heart"
  ],
  "Magikarp": [
    "Rattled",
    "Swift Swim"
  ],
  "Magmar": [
    "Flame Body",
    "Vital Spirit"
  ],
  "Magmortar": [
    "Flame Body",
    "Vital Spirit"
  ],
  "Magnemite": [
    "Analytic",
    "Magnet Pull",
    "Sturdy"
  ],
  "Magneton": [
    "Analytic",
    "Magnet Pull",
    "Sturdy"
  ],
  "Magnezone": [
    "Analytic",
    "Magnet Pull",
    "Sturdy"
  ],
  "Makuhita": [
    "Guts",
    "Sheer Force",
    "Thick Fat"
  ],
  "Malaconda": [
    "Drought",
    "Harvest",
    "Infiltrator"
  ],
  "Malamar": [
    "Contrary",
    "Infiltrator",
    "Suction Cups"
  ],
  "Malamar-Mega": [
    "Contrary"
  ],
  "Mamoswine": [
    "Oblivious",
    "Snow Cloak",
    "Thick Fat"
  ],
  "Manaphy": [
    "Hydration"
  ],
  "Mandibuzz": [
    "Big Pecks",
    "Overcoat",
    "Weak Armor"
  ],
  "Manectric": [
    "Lightning Rod",
    "Minus",
    "Static"
  ],
  "Manectric-Mega": [
    "Intimidate"
  ],
  "Mankey": [
    "Anger Point",
    "Defiant",
    "Vital Spirit"
  ],
  "Mantine": [
    "Swift Swim",
    "Water Absorb",
    "Water Veil"
  ],
  "Mantyke": [
    "Swift Swim",
    "Water Absorb",
    "Water Veil"
  ],
  "Maractus": [
    "Chlorophyll",
    "Storm Drain",
    "Water Absorb"
  ],
  "Mareanie": [
    "Limber",
    "Merciless",
    "Regenerator"
  ],
  "Mareep": [
    "Plus",
    "Static"
  ],
  "Marill": [
    "Huge Power",
    "Sap Sipper",
    "Thick Fat"
  ],
  "Marowak": [
    "Battle Armor",
    "Lightning Rod",
    "Rock Head"
  ],
  "Marowak-Alola": [
    "Cursed Body",
    "Lightning Rod",
    "Rock Head"
  ],
  "Marowak-Alola-Totem": [
    "Rock Head"
  ],
  "Marshadow": [
    "Technician"
  ],
  "Marshtomp": [
    "Damp",
    "Torrent"
  ],
  "Maschiff": [
    "Intimidate",
    "Run Away",
    "Stakeout"
  ],
  "Masquerain": [
    "Intimidate",
    "Unnerve"
  ],
  "Maushold": [
    "Cheek Pouch",
    "Friend Guard",
    "Technician"
  ],
  "Maushold-Four": [
    "Cheek Pouch",
    "Friend Guard",
    "Technician"
  ],
  "Mawile": [
    "Hyper Cutter",
    "Intimidate",
    "Sheer Force"
  ],
  "Mawile-Mega": [
    "Huge Power"
  ],
  "Medicham": [
    "Pure Power",
    "Telepathy"
  ],
  "Medicham-Mega": [
    "Pure Power"
  ],
  "Meditite": [
    "Pure Power",
    "Telepathy"
  ],
  "Meganium": [
    "Leaf Guard",
    "Overgrow"
  ],
  "Meganium-Mega": [
    "Mega Sol"
  ],
  "Melmetal": [
    "Iron Fist"
  ],
  "Melmetal-Gmax": [
    "Iron Fist"
  ],
  "Meloetta": [
    "Serene Grace"
  ],
  "Meloetta-Pirouette": [
    "Serene Grace"
  ],
  "Meltan": [
    "Magnet Pull"
  ],
  "Meowscarada": [
    "Overgrow",
    "Protean"
  ],
  "Meowstic": [
    "Infiltrator",
    "Keen Eye",
    "Prankster"
  ],
  "Meowstic-F": [
    "Competitive",
    "Infiltrator",
    "Keen Eye"
  ],
  "Meowstic-F-Mega": [
    "Trace"
  ],
  "Meowstic-M-Mega": [
    "Trace"
  ],
  "Meowth": [
    "Pickup",
    "Technician",
    "Unnerve"
  ],
  "Meowth-Alola": [
    "Pickup",
    "Rattled",
    "Technician"
  ],
  "Meowth-Galar": [
    "Pickup",
    "Tough Claws",
    "Unnerve"
  ],
  "Meowth-Gmax": [
    "Pickup",
    "Technician",
    "Unnerve"
  ],
  "Mesprit": [
    "Levitate"
  ],
  "Metagross": [
    "Clear Body",
    "Light Metal"
  ],
  "Metagross-Mega": [
    "Tough Claws"
  ],
  "Metang": [
    "Clear Body",
    "Light Metal"
  ],
  "Metapod": [
    "Shed Skin"
  ],
  "Mew": [
    "Synchronize"
  ],
  "Mewtwo": [
    "Pressure",
    "Unnerve"
  ],
  "Mewtwo-Mega-X": [
    "Steadfast"
  ],
  "Mewtwo-Mega-Y": [
    "Insomnia"
  ],
  "Miasmaw": [
    "Compound Eyes",
    "Hyper Cutter",
    "Neutralizing Gas"
  ],
  "Miasmite": [
    "Compound Eyes",
    "Hyper Cutter",
    "Neutralizing Gas"
  ],
  "Mienfoo": [
    "Inner Focus",
    "Reckless",
    "Regenerator"
  ],
  "Mienshao": [
    "Inner Focus",
    "Reckless",
    "Regenerator"
  ],
  "Mightyena": [
    "Intimidate",
    "Moxie",
    "Quick Feet"
  ],
  "Milcery": [
    "Aroma Veil",
    "Sweet Veil"
  ],
  "Milotic": [
    "Competitive",
    "Cute Charm",
    "Marvel Scale"
  ],
  "Miltank": [
    "Sap Sipper",
    "Scrappy",
    "Thick Fat"
  ],
  "Mime Jr.": [
    "Filter",
    "Soundproof",
    "Technician"
  ],
  "Mimikyu": [
    "Disguise"
  ],
  "Mimikyu-Busted": [
    "Disguise"
  ],
  "Mimikyu-Busted-Totem": [
    "Disguise"
  ],
  "Mimikyu-Totem": [
    "Disguise"
  ],
  "Minccino": [
    "Cute Charm",
    "Skill Link",
    "Technician"
  ],
  "Minior": [
    "Shields Down"
  ],
  "Minior-Meteor": [
    "Shields Down"
  ],
  "Minun": [
    "Minus",
    "Volt Absorb"
  ],
  "Miraidon": [
    "Hadron Engine"
  ],
  "Misdreavus": [
    "Levitate"
  ],
  "Mismagius": [
    "Levitate"
  ],
  "MissingNo.": [],
  "Mollux": [
    "Dry Skin",
    "Illuminate"
  ],
  "Moltres": [
    "Flame Body",
    "Pressure"
  ],
  "Moltres-Galar": [
    "Berserk"
  ],
  "Monferno": [
    "Blaze",
    "Iron Fist"
  ],
  "Monohm": [
    "Damp",
    "Shield Dust",
    "Static"
  ],
  "Morelull": [
    "Effect Spore",
    "Illuminate",
    "Rain Dish"
  ],
  "Morgrem": [
    "Frisk",
    "Pickpocket",
    "Prankster"
  ],
  "Morpeko": [
    "Hunger Switch"
  ],
  "Morpeko-Hangry": [
    "Hunger Switch"
  ],
  "Mothim": [
    "Swarm",
    "Tinted Lens"
  ],
  "Mr. Mime": [
    "Filter",
    "Soundproof",
    "Technician"
  ],
  "Mr. Mime-Galar": [
    "Ice Body",
    "Screen Cleaner",
    "Vital Spirit"
  ],
  "Mr. Rime": [
    "Ice Body",
    "Screen Cleaner",
    "Tangled Feet"
  ],
  "Mudbray": [
    "Inner Focus",
    "Own Tempo",
    "Stamina"
  ],
  "Mudkip": [
    "Damp",
    "Torrent"
  ],
  "Mudsdale": [
    "Inner Focus",
    "Own Tempo",
    "Stamina"
  ],
  "Muk": [
    "Poison Touch",
    "Stench",
    "Sticky Hold"
  ],
  "Muk-Alola": [
    "Gluttony",
    "Poison Touch",
    "Power of Alchemy"
  ],
  "Mumbao": [
    "Overcoat",
    "Solar Power",
    "Trace"
  ],
  "Munchlax": [
    "Gluttony",
    "Pickup",
    "Thick Fat"
  ],
  "Munkidori": [
    "Frisk",
    "Toxic Chain"
  ],
  "Munna": [
    "Forewarn",
    "Synchronize",
    "Telepathy"
  ],
  "Murkrow": [
    "Insomnia",
    "Prankster",
    "Super Luck"
  ],
  "Musharna": [
    "Forewarn",
    "Synchronize",
    "Telepathy"
  ],
  "Nacli": [
    "Clear Body",
    "Purifying Salt",
    "Sturdy"
  ],
  "Naclstack": [
    "Clear Body",
    "Purifying Salt",
    "Sturdy"
  ],
  "Naganadel": [
    "Beast Boost"
  ],
  "Natu": [
    "Early Bird",
    "Magic Bounce",
    "Synchronize"
  ],
  "Naviathan": [
    "Guts",
    "Heatproof",
    "Light Metal"
  ],
  "Necrozma": [
    "Prism Armor"
  ],
  "Necrozma-Dawn-Wings": [
    "Prism Armor"
  ],
  "Necrozma-Dusk-Mane": [
    "Prism Armor"
  ],
  "Necrozma-Ultra": [
    "Neuroforce"
  ],
  "Necturine": [
    "Anticipation",
    "Telepathy"
  ],
  "Necturna": [
    "Forewarn",
    "Telepathy"
  ],
  "Nickit": [
    "Run Away",
    "Stakeout",
    "Unburden"
  ],
  "Nidoking": [
    "Poison Point",
    "Rivalry",
    "Sheer Force"
  ],
  "Nidoqueen": [
    "Poison Point",
    "Rivalry",
    "Sheer Force"
  ],
  "Nidoran-F": [
    "Hustle",
    "Poison Point",
    "Rivalry"
  ],
  "Nidoran-M": [
    "Hustle",
    "Poison Point",
    "Rivalry"
  ],
  "Nidorina": [
    "Hustle",
    "Poison Point",
    "Rivalry"
  ],
  "Nidorino": [
    "Hustle",
    "Poison Point",
    "Rivalry"
  ],
  "Nihilego": [
    "Beast Boost"
  ],
  "Nincada": [
    "Compound Eyes",
    "Run Away"
  ],
  "Ninetales": [
    "Drought",
    "Flash Fire"
  ],
  "Ninetales-Alola": [
    "Snow Cloak",
    "Snow Warning"
  ],
  "Ninjask": [
    "Infiltrator",
    "Speed Boost"
  ],
  "Noctowl": [
    "Insomnia",
    "Keen Eye",
    "Tinted Lens"
  ],
  "Nohface": [
    "Frisk",
    "Limber",
    "Unnerve"
  ],
  "Noibat": [
    "Frisk",
    "Infiltrator",
    "Telepathy"
  ],
  "Noivern": [
    "Frisk",
    "Infiltrator",
    "Telepathy"
  ],
  "Nosepass": [
    "Magnet Pull",
    "Sand Force",
    "Sturdy"
  ],
  "Numel": [
    "Oblivious",
    "Own Tempo",
    "Simple"
  ],
  "Nuzleaf": [
    "Chlorophyll",
    "Early Bird",
    "Pickpocket"
  ],
  "Nymble": [
    "Swarm",
    "Tinted Lens"
  ],
  "Obliteryx": [
    "Analytic",
    "Opportunist"
  ],
  "Obstagoon": [
    "Defiant",
    "Guts",
    "Reckless"
  ],
  "Octillery": [
    "Moody",
    "Sniper",
    "Suction Cups"
  ],
  "Oddish": [
    "Chlorophyll",
    "Run Away"
  ],
  "Ogerpon": [
    "Defiant"
  ],
  "Ogerpon-Cornerstone": [
    "Sturdy"
  ],
  "Ogerpon-Cornerstone-Tera": [
    "Embody Aspect (Cornerstone)"
  ],
  "Ogerpon-Hearthflame": [
    "Mold Breaker"
  ],
  "Ogerpon-Hearthflame-Tera": [
    "Embody Aspect (Hearthflame)"
  ],
  "Ogerpon-Teal-Tera": [
    "Embody Aspect (Teal)"
  ],
  "Ogerpon-Wellspring": [
    "Water Absorb"
  ],
  "Ogerpon-Wellspring-Tera": [
    "Embody Aspect (Wellspring)"
  ],
  "Oinkologne": [
    "Gluttony",
    "Lingering Aroma",
    "Thick Fat"
  ],
  "Oinkologne-F": [
    "Aroma Veil",
    "Gluttony",
    "Thick Fat"
  ],
  "Okidogi": [
    "Guard Dog",
    "Toxic Chain"
  ],
  "Omanyte": [
    "Shell Armor",
    "Swift Swim",
    "Weak Armor"
  ],
  "Omastar": [
    "Shell Armor",
    "Swift Swim",
    "Weak Armor"
  ],
  "Onix": [
    "Rock Head",
    "Sturdy",
    "Weak Armor"
  ],
  "Oranguru": [
    "Inner Focus",
    "Symbiosis",
    "Telepathy"
  ],
  "Orbeetle": [
    "Frisk",
    "Swarm",
    "Telepathy"
  ],
  "Orbeetle-Gmax": [
    "Frisk",
    "Swarm",
    "Telepathy"
  ],
  "Oricorio": [
    "Dancer"
  ],
  "Oricorio-Pa'u": [
    "Dancer"
  ],
  "Oricorio-Pom-Pom": [
    "Dancer"
  ],
  "Oricorio-Sensu": [
    "Dancer"
  ],
  "Orthworm": [
    "Earth Eater",
    "Sand Veil"
  ],
  "Oshawott": [
    "Shell Armor",
    "Torrent"
  ],
  "Overqwil": [
    "Intimidate",
    "Poison Point",
    "Swift Swim"
  ],
  "Pachirisu": [
    "Pickup",
    "Run Away",
    "Volt Absorb"
  ],
  "Pajantom": [
    "Comatose"
  ],
  "Palafin": [
    "Zero to Hero"
  ],
  "Palafin-Hero": [
    "Zero to Hero"
  ],
  "Palkia": [
    "Pressure",
    "Telepathy"
  ],
  "Palkia-Origin": [
    "Pressure",
    "Telepathy"
  ],
  "Palossand": [
    "Sand Veil",
    "Water Compaction"
  ],
  "Palpitoad": [
    "Hydration",
    "Swift Swim",
    "Water Absorb"
  ],
  "Pancham": [
    "Iron Fist",
    "Mold Breaker",
    "Scrappy"
  ],
  "Pangoro": [
    "Iron Fist",
    "Mold Breaker",
    "Scrappy"
  ],
  "Panpour": [
    "Gluttony",
    "Torrent"
  ],
  "Pansage": [
    "Gluttony",
    "Overgrow"
  ],
  "Pansear": [
    "Blaze",
    "Gluttony"
  ],
  "Paras": [
    "Damp",
    "Dry Skin",
    "Effect Spore"
  ],
  "Parasect": [
    "Damp",
    "Dry Skin",
    "Effect Spore"
  ],
  "Passimian": [
    "Defiant",
    "Receiver"
  ],
  "Patrat": [
    "Analytic",
    "Keen Eye",
    "Run Away"
  ],
  "Pawmi": [
    "Iron Fist",
    "Natural Cure",
    "Static"
  ],
  "Pawmo": [
    "Iron Fist",
    "Natural Cure",
    "Volt Absorb"
  ],
  "Pawmot": [
    "Iron Fist",
    "Natural Cure",
    "Volt Absorb"
  ],
  "Pawniard": [
    "Defiant",
    "Inner Focus",
    "Pressure"
  ],
  "Pecharunt": [
    "Poison Puppeteer"
  ],
  "Pelipper": [
    "Drizzle",
    "Keen Eye",
    "Rain Dish"
  ],
  "Perrserker": [
    "Battle Armor",
    "Steely Spirit",
    "Tough Claws"
  ],
  "Persian": [
    "Limber",
    "Technician",
    "Unnerve"
  ],
  "Persian-Alola": [
    "Fur Coat",
    "Rattled",
    "Technician"
  ],
  "Petilil": [
    "Chlorophyll",
    "Leaf Guard",
    "Own Tempo"
  ],
  "Phanpy": [
    "Pickup",
    "Sand Veil"
  ],
  "Phantump": [
    "Frisk",
    "Harvest",
    "Natural Cure"
  ],
  "Pheromosa": [
    "Beast Boost"
  ],
  "Phione": [
    "Hydration"
  ],
  "Pichu": [
    "Lightning Rod",
    "Static"
  ],
  "Pichu-Spiky-eared": [
    "Static"
  ],
  "Pidgeot": [
    "Big Pecks",
    "Keen Eye",
    "Tangled Feet"
  ],
  "Pidgeot-Mega": [
    "No Guard"
  ],
  "Pidgeotto": [
    "Big Pecks",
    "Keen Eye",
    "Tangled Feet"
  ],
  "Pidgey": [
    "Big Pecks",
    "Keen Eye",
    "Tangled Feet"
  ],
  "Pidove": [
    "Big Pecks",
    "Rivalry",
    "Super Luck"
  ],
  "Pignite": [
    "Blaze",
    "Thick Fat"
  ],
  "Pikachu": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Alola": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Belle": [
    "Lightning Rod"
  ],
  "Pikachu-Cosplay": [
    "Lightning Rod"
  ],
  "Pikachu-Gmax": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Hoenn": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Kalos": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Libre": [
    "Lightning Rod"
  ],
  "Pikachu-Original": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Partner": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-PhD": [
    "Lightning Rod"
  ],
  "Pikachu-Pop-Star": [
    "Lightning Rod"
  ],
  "Pikachu-Rock-Star": [
    "Lightning Rod"
  ],
  "Pikachu-Sinnoh": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Starter": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-Unova": [
    "Lightning Rod",
    "Static"
  ],
  "Pikachu-World": [
    "Lightning Rod",
    "Static"
  ],
  "Pikipek": [
    "Keen Eye",
    "Pickup",
    "Skill Link"
  ],
  "Piloswine": [
    "Oblivious",
    "Snow Cloak",
    "Thick Fat"
  ],
  "Pincurchin": [
    "Electric Surge",
    "Lightning Rod"
  ],
  "Pineco": [
    "Overcoat",
    "Sturdy"
  ],
  "Pinsir": [
    "Hyper Cutter",
    "Mold Breaker",
    "Moxie"
  ],
  "Pinsir-Mega": [
    "Aerilate"
  ],
  "Piplup": [
    "Competitive",
    "Torrent"
  ],
  "Plasmanta": [
    "Storm Drain",
    "Telepathy",
    "Vital Spirit"
  ],
  "Pluffle": [
    "Aroma Veil",
    "Friend Guard",
    "Natural Cure"
  ],
  "Plusle": [
    "Lightning Rod",
    "Plus"
  ],
  "Poipole": [
    "Beast Boost"
  ],
  "Pokestar Black Belt": [
    "Huge Power"
  ],
  "Pokestar Black Door": [
    "Early Bird"
  ],
  "Pokestar Brycen-Man": [
    "Levitate"
  ],
  "Pokestar F-00": [
    "Volt Absorb"
  ],
  "Pokestar F-002": [
    "Reckless"
  ],
  "Pokestar Giant": [
    "Huge Power"
  ],
  "Pokestar Humanoid": [
    "Insomnia"
  ],
  "Pokestar MT": [
    "Analytic"
  ],
  "Pokestar MT2": [
    "Flash Fire"
  ],
  "Pokestar Monster": [
    "Pressure"
  ],
  "Pokestar Smeargle": [
    "Moody",
    "Own Tempo",
    "Technician"
  ],
  "Pokestar Spirit": [
    "Wonder Guard"
  ],
  "Pokestar Transport": [
    "Motor Drive"
  ],
  "Pokestar UFO": [
    "Levitate"
  ],
  "Pokestar UFO-2": [
    "Levitate"
  ],
  "Pokestar UFO-PropU2": [
    "Levitate"
  ],
  "Pokestar White Door": [
    "Blaze"
  ],
  "Politoed": [
    "Damp",
    "Drizzle",
    "Water Absorb"
  ],
  "Poliwag": [
    "Damp",
    "Swift Swim",
    "Water Absorb"
  ],
  "Poliwhirl": [
    "Damp",
    "Swift Swim",
    "Water Absorb"
  ],
  "Poliwrath": [
    "Damp",
    "Swift Swim",
    "Water Absorb"
  ],
  "Poltchageist": [
    "Heatproof",
    "Hospitality"
  ],
  "Poltchageist-Artisan": [
    "Heatproof",
    "Hospitality"
  ],
  "Polteageist": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Polteageist-Antique": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Ponyta": [
    "Flame Body",
    "Flash Fire",
    "Run Away"
  ],
  "Ponyta-Galar": [
    "Anticipation",
    "Pastel Veil",
    "Run Away"
  ],
  "Poochyena": [
    "Quick Feet",
    "Rattled",
    "Run Away"
  ],
  "Popplio": [
    "Liquid Voice",
    "Torrent"
  ],
  "Porygon": [
    "Analytic",
    "Download",
    "Trace"
  ],
  "Porygon-Z": [
    "Adaptability",
    "Analytic",
    "Download"
  ],
  "Porygon2": [
    "Analytic",
    "Download",
    "Trace"
  ],
  "Primarina": [
    "Liquid Voice",
    "Torrent"
  ],
  "Primeape": [
    "Anger Point",
    "Defiant",
    "Vital Spirit"
  ],
  "Prinplup": [
    "Competitive",
    "Torrent"
  ],
  "Privatyke": [
    "Technician",
    "Unaware"
  ],
  "Probopass": [
    "Magnet Pull",
    "Sand Force",
    "Sturdy"
  ],
  "Protowatt": [
    "Magic Guard",
    "Minus",
    "Trace"
  ],
  "Psyduck": [
    "Cloud Nine",
    "Damp",
    "Swift Swim"
  ],
  "Pumpkaboo": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Pumpkaboo-Large": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Pumpkaboo-Small": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Pumpkaboo-Super": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Pupitar": [
    "Shed Skin"
  ],
  "Purrloin": [
    "Limber",
    "Prankster",
    "Unburden"
  ],
  "Purugly": [
    "Defiant",
    "Own Tempo",
    "Thick Fat"
  ],
  "Pyroak": [
    "Battle Armor",
    "Contrary",
    "Rock Head"
  ],
  "Pyroar": [
    "Moxie",
    "Rivalry",
    "Unnerve"
  ],
  "Pyroar-Mega": [
    "Fire Mane"
  ],
  "Pyukumuku": [
    "Innards Out",
    "Unaware"
  ],
  "Quagsire": [
    "Damp",
    "Unaware",
    "Water Absorb"
  ],
  "Quaquaval": [
    "Moxie",
    "Torrent"
  ],
  "Quaxly": [
    "Moxie",
    "Torrent"
  ],
  "Quaxwell": [
    "Moxie",
    "Torrent"
  ],
  "Quilava": [
    "Blaze",
    "Flash Fire"
  ],
  "Quilladin": [
    "Bulletproof",
    "Overgrow"
  ],
  "Qwilfish": [
    "Intimidate",
    "Poison Point",
    "Swift Swim"
  ],
  "Qwilfish-Hisui": [
    "Intimidate",
    "Poison Point",
    "Swift Swim"
  ],
  "Raboot": [
    "Blaze",
    "Libero"
  ],
  "Rabsca": [
    "Synchronize",
    "Telepathy"
  ],
  "Raging Bolt": [
    "Protosynthesis"
  ],
  "Raichu": [
    "Lightning Rod",
    "Static"
  ],
  "Raichu-Alola": [
    "Surge Surfer"
  ],
  "Raichu-Mega-X": [
    "Electric Surge"
  ],
  "Raichu-Mega-Y": [
    "No Guard"
  ],
  "Raikou": [
    "Inner Focus",
    "Pressure"
  ],
  "Ralts": [
    "Synchronize",
    "Telepathy",
    "Trace"
  ],
  "Ramnarok": [
    "No Guard"
  ],
  "Ramnarok-Radiant": [
    "No Guard"
  ],
  "Rampardos": [
    "Mold Breaker",
    "Sheer Force"
  ],
  "Rapidash": [
    "Flame Body",
    "Flash Fire",
    "Run Away"
  ],
  "Rapidash-Galar": [
    "Anticipation",
    "Pastel Veil",
    "Run Away"
  ],
  "Raticate": [
    "Guts",
    "Hustle",
    "Run Away"
  ],
  "Raticate-Alola": [
    "Gluttony",
    "Hustle",
    "Thick Fat"
  ],
  "Raticate-Alola-Totem": [
    "Thick Fat"
  ],
  "Rattata": [
    "Guts",
    "Hustle",
    "Run Away"
  ],
  "Rattata-Alola": [
    "Gluttony",
    "Hustle",
    "Thick Fat"
  ],
  "Rayquaza": [
    "Air Lock"
  ],
  "Rayquaza-Mega": [
    "Delta Stream"
  ],
  "Rebble": [
    "Levitate",
    "Sniper",
    "Solid Rock"
  ],
  "Regice": [
    "Clear Body",
    "Ice Body"
  ],
  "Regidrago": [
    "Dragon's Maw"
  ],
  "Regieleki": [
    "Transistor"
  ],
  "Regigigas": [
    "Slow Start"
  ],
  "Regirock": [
    "Clear Body",
    "Sturdy"
  ],
  "Registeel": [
    "Clear Body",
    "Light Metal"
  ],
  "Relicanth": [
    "Rock Head",
    "Sturdy",
    "Swift Swim"
  ],
  "Rellor": [
    "Compound Eyes",
    "Shed Skin"
  ],
  "Remoraid": [
    "Hustle",
    "Moody",
    "Sniper"
  ],
  "Reshiram": [
    "Turboblaze"
  ],
  "Reuniclus": [
    "Magic Guard",
    "Overcoat",
    "Regenerator"
  ],
  "Revavroom": [
    "Filter",
    "Overcoat"
  ],
  "Revenankh": [
    "Air Lock",
    "Shed Skin",
    "Triage"
  ],
  "Rhydon": [
    "Lightning Rod",
    "Reckless",
    "Rock Head"
  ],
  "Rhyhorn": [
    "Lightning Rod",
    "Reckless",
    "Rock Head"
  ],
  "Rhyperior": [
    "Lightning Rod",
    "Reckless",
    "Solid Rock"
  ],
  "Ribombee": [
    "Honey Gather",
    "Shield Dust",
    "Sweet Veil"
  ],
  "Ribombee-Totem": [
    "Sweet Veil"
  ],
  "Rillaboom": [
    "Grassy Surge",
    "Overgrow"
  ],
  "Rillaboom-Gmax": [
    "Grassy Surge",
    "Overgrow"
  ],
  "Riolu": [
    "Inner Focus",
    "Prankster",
    "Steadfast"
  ],
  "Roaring Moon": [
    "Protosynthesis"
  ],
  "Rockruff": [
    "Keen Eye",
    "Own Tempo",
    "Steadfast",
    "Vital Spirit"
  ],
  "Rockruff-Dusk": [
    "Own Tempo"
  ],
  "Roggenrola": [
    "Sand Force",
    "Sturdy",
    "Weak Armor"
  ],
  "Rolycoly": [
    "Flash Fire",
    "Heatproof",
    "Steam Engine"
  ],
  "Rookidee": [
    "Big Pecks",
    "Keen Eye",
    "Unnerve"
  ],
  "Roselia": [
    "Leaf Guard",
    "Natural Cure",
    "Poison Point"
  ],
  "Roserade": [
    "Natural Cure",
    "Poison Point",
    "Technician"
  ],
  "Rotom": [
    "Levitate"
  ],
  "Rotom-Fan": [
    "Levitate"
  ],
  "Rotom-Frost": [
    "Levitate"
  ],
  "Rotom-Heat": [
    "Levitate"
  ],
  "Rotom-Mow": [
    "Levitate"
  ],
  "Rotom-Wash": [
    "Levitate"
  ],
  "Rowlet": [
    "Long Reach",
    "Overgrow"
  ],
  "Rufflet": [
    "Hustle",
    "Keen Eye",
    "Sheer Force"
  ],
  "Runerigus": [
    "Wandering Spirit"
  ],
  "Sableye": [
    "Keen Eye",
    "Prankster",
    "Stall"
  ],
  "Sableye-Mega": [
    "Magic Bounce"
  ],
  "Saharaja": [
    "Sand Spit",
    "Serene Grace",
    "Water Absorb"
  ],
  "Saharascal": [
    "Pickpocket",
    "Sand Spit",
    "Water Absorb"
  ],
  "Salamence": [
    "Intimidate",
    "Moxie"
  ],
  "Salamence-Mega": [
    "Aerilate"
  ],
  "Salandit": [
    "Corrosion",
    "Oblivious"
  ],
  "Salazzle": [
    "Corrosion",
    "Oblivious"
  ],
  "Salazzle-Totem": [
    "Corrosion"
  ],
  "Samurott": [
    "Shell Armor",
    "Torrent"
  ],
  "Samurott-Hisui": [
    "Sharpness",
    "Torrent"
  ],
  "Sandaconda": [
    "Sand Spit",
    "Sand Veil",
    "Shed Skin"
  ],
  "Sandaconda-Gmax": [
    "Sand Spit",
    "Sand Veil",
    "Shed Skin"
  ],
  "Sandile": [
    "Anger Point",
    "Intimidate",
    "Moxie"
  ],
  "Sandshrew": [
    "Sand Rush",
    "Sand Veil"
  ],
  "Sandshrew-Alola": [
    "Slush Rush",
    "Snow Cloak"
  ],
  "Sandslash": [
    "Sand Rush",
    "Sand Veil"
  ],
  "Sandslash-Alola": [
    "Slush Rush",
    "Snow Cloak"
  ],
  "Sandy Shocks": [
    "Protosynthesis"
  ],
  "Sandygast": [
    "Sand Veil",
    "Water Compaction"
  ],
  "Sawk": [
    "Inner Focus",
    "Mold Breaker",
    "Sturdy"
  ],
  "Sawsbuck": [
    "Chlorophyll",
    "Sap Sipper",
    "Serene Grace"
  ],
  "Scatterbug": [
    "Compound Eyes",
    "Friend Guard",
    "Shield Dust"
  ],
  "Scattervein": [
    "Intimidate",
    "Own Tempo",
    "Pixilate"
  ],
  "Sceptile": [
    "Overgrow",
    "Unburden"
  ],
  "Sceptile-Mega": [
    "Lightning Rod"
  ],
  "Scizor": [
    "Light Metal",
    "Swarm",
    "Technician"
  ],
  "Scizor-Mega": [
    "Technician"
  ],
  "Scolipede": [
    "Poison Point",
    "Speed Boost",
    "Swarm"
  ],
  "Scolipede-Mega": [
    "Shell Armor"
  ],
  "Scorbunny": [
    "Blaze",
    "Libero"
  ],
  "Scovillain": [
    "Chlorophyll",
    "Insomnia",
    "Moody"
  ],
  "Scovillain-Mega": [
    "Spicy Spray"
  ],
  "Scrafty": [
    "Intimidate",
    "Moxie",
    "Shed Skin"
  ],
  "Scrafty-Mega": [
    "Intimidate"
  ],
  "Scraggy": [
    "Intimidate",
    "Moxie",
    "Shed Skin"
  ],
  "Scratchet": [
    "Prankster",
    "Scrappy",
    "Vital Spirit"
  ],
  "Scream Tail": [
    "Protosynthesis"
  ],
  "Scyther": [
    "Steadfast",
    "Swarm",
    "Technician"
  ],
  "Seadra": [
    "Damp",
    "Poison Point",
    "Sniper"
  ],
  "Seaking": [
    "Lightning Rod",
    "Swift Swim",
    "Water Veil"
  ],
  "Sealeo": [
    "Ice Body",
    "Oblivious",
    "Thick Fat"
  ],
  "Seedot": [
    "Chlorophyll",
    "Early Bird",
    "Pickpocket"
  ],
  "Seel": [
    "Hydration",
    "Ice Body",
    "Thick Fat"
  ],
  "Seismitoad": [
    "Poison Touch",
    "Swift Swim",
    "Water Absorb"
  ],
  "Sentret": [
    "Frisk",
    "Keen Eye",
    "Run Away"
  ],
  "Serperior": [
    "Contrary",
    "Overgrow"
  ],
  "Servine": [
    "Contrary",
    "Overgrow"
  ],
  "Seviper": [
    "Infiltrator",
    "Shed Skin"
  ],
  "Sewaddle": [
    "Chlorophyll",
    "Overcoat",
    "Swarm"
  ],
  "Sharpedo": [
    "Rough Skin",
    "Speed Boost"
  ],
  "Sharpedo-Mega": [
    "Strong Jaw"
  ],
  "Shaymin": [
    "Natural Cure"
  ],
  "Shaymin-Sky": [
    "Serene Grace"
  ],
  "Shedinja": [
    "Wonder Guard"
  ],
  "Shelgon": [
    "Overcoat",
    "Rock Head"
  ],
  "Shellder": [
    "Overcoat",
    "Shell Armor",
    "Skill Link"
  ],
  "Shellos": [
    "Sand Force",
    "Sticky Hold",
    "Storm Drain"
  ],
  "Shelmet": [
    "Hydration",
    "Overcoat",
    "Shell Armor"
  ],
  "Shieldon": [
    "Soundproof",
    "Sturdy"
  ],
  "Shiftry": [
    "Chlorophyll",
    "Pickpocket",
    "Wind Rider"
  ],
  "Shiinotic": [
    "Effect Spore",
    "Illuminate",
    "Rain Dish"
  ],
  "Shinx": [
    "Guts",
    "Intimidate",
    "Rivalry"
  ],
  "Shox": [
    "Cud Chew",
    "Electromorphosis",
    "Sticky Hold"
  ],
  "Shroodle": [
    "Pickpocket",
    "Prankster",
    "Unburden"
  ],
  "Shroomish": [
    "Effect Spore",
    "Poison Heal",
    "Quick Feet"
  ],
  "Shuckle": [
    "Contrary",
    "Gluttony",
    "Sturdy"
  ],
  "Shuppet": [
    "Cursed Body",
    "Frisk",
    "Insomnia"
  ],
  "Sigilyph": [
    "Magic Guard",
    "Tinted Lens",
    "Wonder Skin"
  ],
  "Silcoon": [
    "Shed Skin"
  ],
  "Silicobra": [
    "Sand Spit",
    "Sand Veil",
    "Shed Skin"
  ],
  "Silvally": [
    "RKS System"
  ],
  "Silvally-Bug": [
    "RKS System"
  ],
  "Silvally-Dark": [
    "RKS System"
  ],
  "Silvally-Dragon": [
    "RKS System"
  ],
  "Silvally-Electric": [
    "RKS System"
  ],
  "Silvally-Fairy": [
    "RKS System"
  ],
  "Silvally-Fighting": [
    "RKS System"
  ],
  "Silvally-Fire": [
    "RKS System"
  ],
  "Silvally-Flying": [
    "RKS System"
  ],
  "Silvally-Ghost": [
    "RKS System"
  ],
  "Silvally-Grass": [
    "RKS System"
  ],
  "Silvally-Ground": [
    "RKS System"
  ],
  "Silvally-Ice": [
    "RKS System"
  ],
  "Silvally-Poison": [
    "RKS System"
  ],
  "Silvally-Psychic": [
    "RKS System"
  ],
  "Silvally-Rock": [
    "RKS System"
  ],
  "Silvally-Steel": [
    "RKS System"
  ],
  "Silvally-Water": [
    "RKS System"
  ],
  "Simipour": [
    "Gluttony",
    "Torrent"
  ],
  "Simisage": [
    "Gluttony",
    "Overgrow"
  ],
  "Simisear": [
    "Blaze",
    "Gluttony"
  ],
  "Sinistcha": [
    "Heatproof",
    "Hospitality"
  ],
  "Sinistcha-Masterpiece": [
    "Heatproof",
    "Hospitality"
  ],
  "Sinistea": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Sinistea-Antique": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Sirfetch’d": [
    "Scrappy",
    "Steadfast"
  ],
  "Sizzlipede": [
    "Flame Body",
    "Flash Fire",
    "White Smoke"
  ],
  "Skarmory": [
    "Keen Eye",
    "Sturdy",
    "Weak Armor"
  ],
  "Skarmory-Mega": [
    "Stalwart"
  ],
  "Skeledirge": [
    "Blaze",
    "Unaware"
  ],
  "Skiddo": [
    "Grass Pelt",
    "Sap Sipper"
  ],
  "Skiploom": [
    "Chlorophyll",
    "Infiltrator",
    "Leaf Guard"
  ],
  "Skitty": [
    "Cute Charm",
    "Normalize",
    "Wonder Skin"
  ],
  "Skorupi": [
    "Battle Armor",
    "Keen Eye",
    "Sniper"
  ],
  "Skrelp": [
    "Adaptability",
    "Poison Point",
    "Poison Touch"
  ],
  "Skuntank": [
    "Aftermath",
    "Keen Eye",
    "Stench"
  ],
  "Skwovet": [
    "Cheek Pouch",
    "Gluttony"
  ],
  "Slaking": [
    "Truant"
  ],
  "Slakoth": [
    "Truant"
  ],
  "Sliggoo": [
    "Gooey",
    "Hydration",
    "Sap Sipper"
  ],
  "Sliggoo-Hisui": [
    "Gooey",
    "Sap Sipper",
    "Shell Armor"
  ],
  "Slither Wing": [
    "Protosynthesis"
  ],
  "Slowbro": [
    "Oblivious",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowbro-Galar": [
    "Own Tempo",
    "Quick Draw",
    "Regenerator"
  ],
  "Slowbro-Mega": [
    "Shell Armor"
  ],
  "Slowking": [
    "Oblivious",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowking-Galar": [
    "Curious Medicine",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowpoke": [
    "Oblivious",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowpoke-Galar": [
    "Gluttony",
    "Own Tempo",
    "Regenerator"
  ],
  "Slugma": [
    "Flame Body",
    "Magma Armor",
    "Weak Armor"
  ],
  "Slurpuff": [
    "Sweet Veil",
    "Unburden"
  ],
  "Smeargle": [
    "Moody",
    "Own Tempo",
    "Technician"
  ],
  "Smogecko": [
    "Blaze",
    "Technician"
  ],
  "Smoguana": [
    "Blaze",
    "Technician"
  ],
  "Smokomodo": [
    "Blaze",
    "Technician"
  ],
  "Smoliv": [
    "Early Bird",
    "Harvest"
  ],
  "Smoochum": [
    "Forewarn",
    "Hydration",
    "Oblivious"
  ],
  "Snaelstrom": [
    "Poison Heal",
    "Torrent"
  ],
  "Sneasel": [
    "Inner Focus",
    "Keen Eye",
    "Pickpocket"
  ],
  "Sneasel-Hisui": [
    "Inner Focus",
    "Keen Eye",
    "Pickpocket"
  ],
  "Sneasler": [
    "Poison Touch",
    "Pressure",
    "Unburden"
  ],
  "Snivy": [
    "Contrary",
    "Overgrow"
  ],
  "Snom": [
    "Ice Scales",
    "Shield Dust"
  ],
  "Snorlax": [
    "Gluttony",
    "Immunity",
    "Thick Fat"
  ],
  "Snorlax-Gmax": [
    "Gluttony",
    "Immunity",
    "Thick Fat"
  ],
  "Snorunt": [
    "Ice Body",
    "Inner Focus",
    "Moody"
  ],
  "Snover": [
    "Snow Warning",
    "Soundproof"
  ],
  "Snubbull": [
    "Intimidate",
    "Rattled",
    "Run Away"
  ],
  "Snugglow": [
    "Storm Drain",
    "Telepathy",
    "Vital Spirit"
  ],
  "Sobble": [
    "Sniper",
    "Torrent"
  ],
  "Solgaleo": [
    "Full Metal Body"
  ],
  "Solosis": [
    "Magic Guard",
    "Overcoat",
    "Regenerator"
  ],
  "Solotl": [
    "Magician",
    "Regenerator",
    "Vital Spirit"
  ],
  "Solrock": [
    "Levitate"
  ],
  "Spearow": [
    "Keen Eye",
    "Sniper"
  ],
  "Spectrier": [
    "Grim Neigh"
  ],
  "Spewpa": [
    "Friend Guard",
    "Shed Skin"
  ],
  "Spheal": [
    "Ice Body",
    "Oblivious",
    "Thick Fat"
  ],
  "Spidops": [
    "Insomnia",
    "Stakeout"
  ],
  "Spinarak": [
    "Insomnia",
    "Sniper",
    "Swarm"
  ],
  "Spinda": [
    "Contrary",
    "Own Tempo",
    "Tangled Feet"
  ],
  "Spiritomb": [
    "Infiltrator",
    "Pressure"
  ],
  "Spoink": [
    "Gluttony",
    "Own Tempo",
    "Thick Fat"
  ],
  "Sprigatito": [
    "Overgrow",
    "Protean"
  ],
  "Spritzee": [
    "Aroma Veil",
    "Healer"
  ],
  "Squawkabilly": [
    "Guts",
    "Hustle",
    "Intimidate"
  ],
  "Squawkabilly-Blue": [
    "Guts",
    "Hustle",
    "Intimidate"
  ],
  "Squawkabilly-White": [
    "Hustle",
    "Intimidate",
    "Sheer Force"
  ],
  "Squawkabilly-Yellow": [
    "Hustle",
    "Intimidate",
    "Sheer Force"
  ],
  "Squirtle": [
    "Rain Dish",
    "Torrent"
  ],
  "Stakataka": [
    "Beast Boost"
  ],
  "Stantler": [
    "Frisk",
    "Intimidate",
    "Sap Sipper"
  ],
  "Staraptor": [
    "Intimidate",
    "Reckless"
  ],
  "Staraptor-Mega": [
    "Contrary"
  ],
  "Staravia": [
    "Intimidate",
    "Reckless"
  ],
  "Starly": [
    "Keen Eye",
    "Reckless"
  ],
  "Starmie": [
    "Analytic",
    "Illuminate",
    "Natural Cure"
  ],
  "Starmie-Mega": [
    "Huge Power"
  ],
  "Staryu": [
    "Analytic",
    "Illuminate",
    "Natural Cure"
  ],
  "Steelix": [
    "Rock Head",
    "Sheer Force",
    "Sturdy"
  ],
  "Steelix-Mega": [
    "Sand Force"
  ],
  "Steenee": [
    "Leaf Guard",
    "Oblivious",
    "Sweet Veil"
  ],
  "Stonjourner": [
    "Power Spot"
  ],
  "Stoutland": [
    "Intimidate",
    "Sand Rush",
    "Scrappy"
  ],
  "Stratagem": [
    "Levitate",
    "Sniper",
    "Technician"
  ],
  "Stufful": [
    "Cute Charm",
    "Fluffy",
    "Klutz"
  ],
  "Stunfisk": [
    "Limber",
    "Sand Veil",
    "Static"
  ],
  "Stunfisk-Galar": [
    "Mimicry"
  ],
  "Stunky": [
    "Aftermath",
    "Keen Eye",
    "Stench"
  ],
  "Sudowoodo": [
    "Rattled",
    "Rock Head",
    "Sturdy"
  ],
  "Suicune": [
    "Inner Focus",
    "Pressure"
  ],
  "Sunflora": [
    "Chlorophyll",
    "Early Bird",
    "Solar Power"
  ],
  "Sunkern": [
    "Chlorophyll",
    "Early Bird",
    "Solar Power"
  ],
  "Surskit": [
    "Rain Dish",
    "Swift Swim"
  ],
  "Swablu": [
    "Cloud Nine",
    "Natural Cure"
  ],
  "Swadloon": [
    "Chlorophyll",
    "Leaf Guard",
    "Overcoat"
  ],
  "Swalot": [
    "Gluttony",
    "Liquid Ooze",
    "Sticky Hold"
  ],
  "Swampert": [
    "Damp",
    "Torrent"
  ],
  "Swampert-Mega": [
    "Swift Swim"
  ],
  "Swanna": [
    "Big Pecks",
    "Hydration",
    "Keen Eye"
  ],
  "Swellow": [
    "Guts",
    "Scrappy"
  ],
  "Swinub": [
    "Oblivious",
    "Snow Cloak",
    "Thick Fat"
  ],
  "Swirlix": [
    "Sweet Veil",
    "Unburden"
  ],
  "Swirlpool": [
    "Poison Heal",
    "Torrent"
  ],
  "Swoobat": [
    "Klutz",
    "Simple",
    "Unaware"
  ],
  "Syclant": [
    "Compound Eyes",
    "Ice Body",
    "Mountaineer"
  ],
  "Syclar": [
    "Compound Eyes",
    "Ice Body",
    "Snow Cloak"
  ],
  "Sylveon": [
    "Cute Charm",
    "Pixilate"
  ],
  "Tactite": [
    "Levitate",
    "Sniper",
    "Technician"
  ],
  "Tadbulb": [
    "Damp",
    "Own Tempo",
    "Static"
  ],
  "Taillow": [
    "Guts",
    "Scrappy"
  ],
  "Talonflame": [
    "Flame Body",
    "Gale Wings"
  ],
  "Tandemaus": [
    "Own Tempo",
    "Pickup",
    "Run Away"
  ],
  "Tangela": [
    "Chlorophyll",
    "Leaf Guard",
    "Regenerator"
  ],
  "Tangrowth": [
    "Chlorophyll",
    "Leaf Guard",
    "Regenerator"
  ],
  "Tapu Bulu": [
    "Grassy Surge",
    "Telepathy"
  ],
  "Tapu Fini": [
    "Misty Surge",
    "Telepathy"
  ],
  "Tapu Koko": [
    "Electric Surge",
    "Telepathy"
  ],
  "Tapu Lele": [
    "Psychic Surge",
    "Telepathy"
  ],
  "Tarountula": [
    "Insomnia",
    "Stakeout"
  ],
  "Tatsugiri": [
    "Commander",
    "Storm Drain"
  ],
  "Tatsugiri-Curly-Mega": [
    "Commander",
    "Storm Drain"
  ],
  "Tatsugiri-Droopy": [
    "Commander",
    "Storm Drain"
  ],
  "Tatsugiri-Droopy-Mega": [
    "Commander",
    "Storm Drain"
  ],
  "Tatsugiri-Stretchy": [
    "Commander",
    "Storm Drain"
  ],
  "Tatsugiri-Stretchy-Mega": [
    "Commander",
    "Storm Drain"
  ],
  "Tauros": [
    "Anger Point",
    "Intimidate",
    "Sheer Force"
  ],
  "Tauros-Paldea-Aqua": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Tauros-Paldea-Blaze": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Tauros-Paldea-Combat": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Teddiursa": [
    "Honey Gather",
    "Pickup",
    "Quick Feet"
  ],
  "Tentacool": [
    "Clear Body",
    "Liquid Ooze",
    "Rain Dish"
  ],
  "Tentacruel": [
    "Clear Body",
    "Liquid Ooze",
    "Rain Dish"
  ],
  "Tepig": [
    "Blaze",
    "Thick Fat"
  ],
  "Terapagos": [
    "Tera Shift"
  ],
  "Terapagos-Stellar": [
    "Teraform Zero"
  ],
  "Terapagos-Terastal": [
    "Tera Shell"
  ],
  "Terrakion": [
    "Justified"
  ],
  "Thievul": [
    "Run Away",
    "Stakeout",
    "Unburden"
  ],
  "Throh": [
    "Guts",
    "Inner Focus",
    "Mold Breaker"
  ],
  "Thundurus": [
    "Defiant",
    "Prankster"
  ],
  "Thundurus-Therian": [
    "Volt Absorb"
  ],
  "Thwackey": [
    "Grassy Surge",
    "Overgrow"
  ],
  "Timburr": [
    "Guts",
    "Iron Fist",
    "Sheer Force"
  ],
  "Ting-Lu": [
    "Vessel of Ruin"
  ],
  "Tinkatink": [
    "Mold Breaker",
    "Own Tempo",
    "Pickpocket"
  ],
  "Tinkaton": [
    "Mold Breaker",
    "Own Tempo",
    "Pickpocket"
  ],
  "Tinkatuff": [
    "Mold Breaker",
    "Own Tempo",
    "Pickpocket"
  ],
  "Tirtouga": [
    "Solid Rock",
    "Sturdy",
    "Swift Swim"
  ],
  "Toedscool": [
    "Mycelium Might"
  ],
  "Toedscruel": [
    "Mycelium Might"
  ],
  "Togedemaru": [
    "Iron Barbs",
    "Lightning Rod",
    "Sturdy"
  ],
  "Togedemaru-Totem": [
    "Sturdy"
  ],
  "Togekiss": [
    "Hustle",
    "Serene Grace",
    "Super Luck"
  ],
  "Togepi": [
    "Hustle",
    "Serene Grace",
    "Super Luck"
  ],
  "Togetic": [
    "Hustle",
    "Serene Grace",
    "Super Luck"
  ],
  "Tomohawk": [
    "Intimidate",
    "Justified",
    "Prankster"
  ],
  "Torchic": [
    "Blaze",
    "Speed Boost"
  ],
  "Torkoal": [
    "Drought",
    "Shell Armor",
    "White Smoke"
  ],
  "Tornadus": [
    "Defiant",
    "Prankster"
  ],
  "Tornadus-Therian": [
    "Regenerator"
  ],
  "Torracat": [
    "Blaze",
    "Intimidate"
  ],
  "Torterra": [
    "Overgrow",
    "Shell Armor"
  ],
  "Totodile": [
    "Sheer Force",
    "Torrent"
  ],
  "Toucannon": [
    "Keen Eye",
    "Sheer Force",
    "Skill Link"
  ],
  "Toxapex": [
    "Limber",
    "Merciless",
    "Regenerator"
  ],
  "Toxel": [
    "Klutz",
    "Rattled",
    "Static"
  ],
  "Toxicroak": [
    "Anticipation",
    "Dry Skin",
    "Poison Touch"
  ],
  "Toxtricity": [
    "Plus",
    "Punk Rock",
    "Technician"
  ],
  "Toxtricity-Gmax": [
    "Plus",
    "Punk Rock",
    "Technician"
  ],
  "Toxtricity-Low-Key": [
    "Minus",
    "Punk Rock",
    "Technician"
  ],
  "Toxtricity-Low-Key-Gmax": [
    "Minus",
    "Punk Rock",
    "Technician"
  ],
  "Tranquill": [
    "Big Pecks",
    "Rivalry",
    "Super Luck"
  ],
  "Trapinch": [
    "Arena Trap",
    "Hyper Cutter",
    "Sheer Force"
  ],
  "Treecko": [
    "Overgrow",
    "Unburden"
  ],
  "Trevenant": [
    "Frisk",
    "Harvest",
    "Natural Cure"
  ],
  "Tropius": [
    "Chlorophyll",
    "Harvest",
    "Solar Power"
  ],
  "Trubbish": [
    "Aftermath",
    "Stench",
    "Sticky Hold"
  ],
  "Trumbeak": [
    "Keen Eye",
    "Pickup",
    "Skill Link"
  ],
  "Tsareena": [
    "Leaf Guard",
    "Queenly Majesty",
    "Sweet Veil"
  ],
  "Turtonator": [
    "Shell Armor"
  ],
  "Turtwig": [
    "Overgrow",
    "Shell Armor"
  ],
  "Tympole": [
    "Hydration",
    "Swift Swim",
    "Water Absorb"
  ],
  "Tynamo": [
    "Levitate"
  ],
  "Type: Null": [
    "Battle Armor"
  ],
  "Typhlosion": [
    "Blaze",
    "Flash Fire"
  ],
  "Typhlosion-Hisui": [
    "Blaze",
    "Frisk"
  ],
  "Tyranitar": [
    "Sand Stream",
    "Unnerve"
  ],
  "Tyranitar-Mega": [
    "Sand Stream"
  ],
  "Tyrantrum": [
    "Rock Head",
    "Strong Jaw"
  ],
  "Tyrogue": [
    "Guts",
    "Steadfast",
    "Vital Spirit"
  ],
  "Tyrunt": [
    "Strong Jaw",
    "Sturdy"
  ],
  "Umbreon": [
    "Inner Focus",
    "Synchronize"
  ],
  "Unfezant": [
    "Big Pecks",
    "Rivalry",
    "Super Luck"
  ],
  "Unown": [
    "Levitate"
  ],
  "Ursaluna": [
    "Bulletproof",
    "Guts",
    "Unnerve"
  ],
  "Ursaluna-Bloodmoon": [
    "Mind's Eye"
  ],
  "Ursaring": [
    "Guts",
    "Quick Feet",
    "Unnerve"
  ],
  "Urshifu": [
    "Unseen Fist"
  ],
  "Urshifu-Gmax": [
    "Unseen Fist"
  ],
  "Urshifu-Rapid-Strike": [
    "Unseen Fist"
  ],
  "Urshifu-Rapid-Strike-Gmax": [
    "Unseen Fist"
  ],
  "Uxie": [
    "Levitate"
  ],
  "Vanillish": [
    "Ice Body",
    "Snow Cloak",
    "Weak Armor"
  ],
  "Vanillite": [
    "Ice Body",
    "Snow Cloak",
    "Weak Armor"
  ],
  "Vanilluxe": [
    "Ice Body",
    "Snow Warning",
    "Weak Armor"
  ],
  "Vaporeon": [
    "Hydration",
    "Water Absorb"
  ],
  "Varoom": [
    "Overcoat",
    "Slow Start"
  ],
  "Veluza": [
    "Mold Breaker",
    "Sharpness"
  ],
  "Venipede": [
    "Poison Point",
    "Speed Boost",
    "Swarm"
  ],
  "Venomicon": [
    "Power of Alchemy",
    "Stamina"
  ],
  "Venomicon-Epilogue": [
    "Tinted Lens"
  ],
  "Venomoth": [
    "Shield Dust",
    "Tinted Lens",
    "Wonder Skin"
  ],
  "Venonat": [
    "Compound Eyes",
    "Run Away",
    "Tinted Lens"
  ],
  "Venusaur": [
    "Chlorophyll",
    "Overgrow"
  ],
  "Venusaur-Gmax": [
    "Chlorophyll",
    "Overgrow"
  ],
  "Venusaur-Mega": [
    "Thick Fat"
  ],
  "Vespiquen": [
    "Pressure",
    "Unnerve"
  ],
  "Vibrava": [
    "Levitate"
  ],
  "Victini": [
    "Victory Star"
  ],
  "Victreebel": [
    "Chlorophyll",
    "Gluttony"
  ],
  "Victreebel-Mega": [
    "Innards Out"
  ],
  "Vigoroth": [
    "Vital Spirit"
  ],
  "Vikavolt": [
    "Levitate"
  ],
  "Vikavolt-Totem": [
    "Levitate"
  ],
  "Vileplume": [
    "Chlorophyll",
    "Effect Spore"
  ],
  "Virizion": [
    "Justified"
  ],
  "Vivillon": [
    "Compound Eyes",
    "Friend Guard",
    "Shield Dust"
  ],
  "Vivillon-Fancy": [
    "Compound Eyes",
    "Friend Guard",
    "Shield Dust"
  ],
  "Vivillon-Pokeball": [
    "Compound Eyes",
    "Friend Guard",
    "Shield Dust"
  ],
  "Volbeat": [
    "Illuminate",
    "Prankster",
    "Swarm"
  ],
  "Volcanion": [
    "Water Absorb"
  ],
  "Volcarona": [
    "Flame Body",
    "Swarm"
  ],
  "Volkraken": [
    "Analytic",
    "Infiltrator",
    "Pressure"
  ],
  "Volkritter": [
    "Anticipation",
    "Infiltrator",
    "Unnerve"
  ],
  "Voltorb": [
    "Aftermath",
    "Soundproof",
    "Static"
  ],
  "Voltorb-Hisui": [
    "Aftermath",
    "Soundproof",
    "Static"
  ],
  "Voodoll": [
    "Cursed Body",
    "Lightning Rod",
    "Volt Absorb"
  ],
  "Voodoom": [
    "Cursed Body",
    "Lightning Rod",
    "Volt Absorb"
  ],
  "Vullaby": [
    "Big Pecks",
    "Overcoat",
    "Weak Armor"
  ],
  "Vulpix": [
    "Drought",
    "Flash Fire"
  ],
  "Vulpix-Alola": [
    "Snow Cloak",
    "Snow Warning"
  ],
  "Wailmer": [
    "Oblivious",
    "Pressure",
    "Water Veil"
  ],
  "Wailord": [
    "Oblivious",
    "Pressure",
    "Water Veil"
  ],
  "Walking Wake": [
    "Protosynthesis"
  ],
  "Walrein": [
    "Ice Body",
    "Oblivious",
    "Thick Fat"
  ],
  "Wartortle": [
    "Rain Dish",
    "Torrent"
  ],
  "Watchog": [
    "Analytic",
    "Illuminate",
    "Keen Eye"
  ],
  "Wattrel": [
    "Competitive",
    "Volt Absorb",
    "Wind Power"
  ],
  "Weavile": [
    "Pickpocket",
    "Pressure"
  ],
  "Weedle": [
    "Run Away",
    "Shield Dust"
  ],
  "Weepinbell": [
    "Chlorophyll",
    "Gluttony"
  ],
  "Weezing": [
    "Levitate",
    "Neutralizing Gas",
    "Stench"
  ],
  "Weezing-Galar": [
    "Levitate",
    "Misty Surge",
    "Neutralizing Gas"
  ],
  "Whimsicott": [
    "Chlorophyll",
    "Infiltrator",
    "Prankster"
  ],
  "Whirlipede": [
    "Poison Point",
    "Speed Boost",
    "Swarm"
  ],
  "Whiscash": [
    "Anticipation",
    "Hydration",
    "Oblivious"
  ],
  "Whismur": [
    "Rattled",
    "Soundproof"
  ],
  "Wigglytuff": [
    "Competitive",
    "Cute Charm",
    "Frisk"
  ],
  "Wiglett": [
    "Gooey",
    "Rattled",
    "Sand Veil"
  ],
  "Wimpod": [
    "Wimp Out"
  ],
  "Wingull": [
    "Hydration",
    "Keen Eye",
    "Rain Dish"
  ],
  "Wishiwashi": [
    "Schooling"
  ],
  "Wishiwashi-School": [
    "Schooling"
  ],
  "Wo-Chien": [
    "Tablets of Ruin"
  ],
  "Wobbuffet": [
    "Shadow Tag",
    "Telepathy"
  ],
  "Woobat": [
    "Klutz",
    "Simple",
    "Unaware"
  ],
  "Wooloo": [
    "Bulletproof",
    "Fluffy",
    "Run Away"
  ],
  "Wooper": [
    "Damp",
    "Unaware",
    "Water Absorb"
  ],
  "Wooper-Paldea": [
    "Poison Point",
    "Unaware",
    "Water Absorb"
  ],
  "Wormadam": [
    "Anticipation",
    "Overcoat"
  ],
  "Wormadam-Sandy": [
    "Anticipation",
    "Overcoat"
  ],
  "Wormadam-Trash": [
    "Anticipation",
    "Overcoat"
  ],
  "Wugtrio": [
    "Gooey",
    "Rattled",
    "Sand Veil"
  ],
  "Wurmple": [
    "Run Away",
    "Shield Dust"
  ],
  "Wynaut": [
    "Shadow Tag",
    "Telepathy"
  ],
  "Wyrdeer": [
    "Frisk",
    "Intimidate",
    "Sap Sipper"
  ],
  "Xatu": [
    "Early Bird",
    "Magic Bounce",
    "Synchronize"
  ],
  "Xerneas": [
    "Fairy Aura"
  ],
  "Xerneas-Neutral": [
    "Fairy Aura"
  ],
  "Xurkitree": [
    "Beast Boost"
  ],
  "Yamask": [
    "Mummy"
  ],
  "Yamask-Galar": [
    "Wandering Spirit"
  ],
  "Yamper": [
    "Ball Fetch",
    "Rattled"
  ],
  "Yanma": [
    "Compound Eyes",
    "Frisk",
    "Speed Boost"
  ],
  "Yanmega": [
    "Frisk",
    "Speed Boost",
    "Tinted Lens"
  ],
  "Yungoos": [
    "Adaptability",
    "Stakeout",
    "Strong Jaw"
  ],
  "Yveltal": [
    "Dark Aura"
  ],
  "Zacian": [
    "Intrepid Sword"
  ],
  "Zacian-Crowned": [
    "Intrepid Sword"
  ],
  "Zamazenta": [
    "Dauntless Shield"
  ],
  "Zamazenta-Crowned": [
    "Dauntless Shield"
  ],
  "Zangoose": [
    "Immunity",
    "Toxic Boost"
  ],
  "Zapdos": [
    "Pressure",
    "Static"
  ],
  "Zapdos-Galar": [
    "Defiant"
  ],
  "Zarude": [
    "Leaf Guard"
  ],
  "Zarude-Dada": [
    "Leaf Guard"
  ],
  "Zebstrika": [
    "Lightning Rod",
    "Motor Drive",
    "Sap Sipper"
  ],
  "Zekrom": [
    "Teravolt"
  ],
  "Zeraora": [
    "Volt Absorb"
  ],
  "Zeraora-Mega": [
    "Volt Absorb"
  ],
  "Zigzagoon": [
    "Gluttony",
    "Pickup",
    "Quick Feet"
  ],
  "Zigzagoon-Galar": [
    "Gluttony",
    "Pickup",
    "Quick Feet"
  ],
  "Zoroark": [
    "Illusion"
  ],
  "Zoroark-Hisui": [
    "Illusion"
  ],
  "Zorua": [
    "Illusion"
  ],
  "Zorua-Hisui": [
    "Illusion"
  ],
  "Zubat": [
    "Infiltrator",
    "Inner Focus"
  ],
  "Zweilous": [
    "Hustle"
  ],
  "Zygarde": [
    "Aura Break",
    "Power Construct"
  ],
  "Zygarde-10%": [
    "Aura Break",
    "Power Construct"
  ],
  "Zygarde-Complete": [
    "Power Construct"
  ],
  "Zygarde-Mega": [
    "Aura Break"
  ]
};
